Add checking of checkpoints in compare_uda.

diff --git a/Packages/Uintah/scripts/regression_tester b/Packages/Uintah/scripts/regression_tester
--- a/Packages/Uintah/scripts/regression_tester
+++ b/Packages/Uintah/scripts/regression_tester
@@ -342,29 +342,44 @@ run_test () {
 
 
 compare_results () {
-#    cd $results
-    
+
     # Inside of the component directory find the location of the 
     # gold standard uda and pass it to compare_uda
     
     uda_tmp=`echo $uda |tr "[/]" "[ ]"`  # eliminate "/" from $uda
     goldStandard=`find $test_dir/$DIR/$CASE/$n -maxdepth 3 -type d -name $uda_tmp`
+
     echo "Comparing $uda results against '$goldStandard'"
-    
-    echo "Running command: ../compare_uda $compare_uda_options gs: $goldStandard ud: $uda"
-    echo "../compare_uda $compare_uda_options  $goldStandard $uda" > $n.compare 2>&1
+        
+    echo   "Running command: ../compare_uda $compare_uda_options gs: $goldStandard ud: $uda"
+    echo "../compare_uda $compare_uda_options  $goldStandard' $uda'" > $n.compare 2>&1
     ../compare_uda $compare_uda_options $goldStandard $uda >> $n.compare 2>&1
-    
-#    compare=`grep "passed" $n.compare`
-  
+        
     if [ $? -eq 0 ]; then 
         echo "Sucess running compare_uda . . ."
-#        cd ..
+        compare=true
+    else
+        echo; echo "FAILURE running compare_uda . . ."   
+	cat $n.compare
+        compare=false
+    fi
+    
+    echo; echo   "Running command: ../compare_uda $compare_uda_options gs: $goldStandard/checkpoints ud: $uda/checkpoints"
+    echo "../compare_uda $compare_uda_options  $goldStandard/checkpoints $uda/checkpoints" > $n.compare 2>&1
+    ../compare_uda $compare_uda_options $goldStandard/checkpoints $uda/checkpoints > $n.compare_checkpoints 2>&1
+
+    if [ $? -eq 0 ]; then
+        echo "Success running compare_uda on checkpoints . . ."
+        compare=true
+    else
+        echo; echo "FAILURE running compare_uda on checkpoints . . ."
+        cat $n.compare_checkpoints
+        compare=false
+    fi
+    
+    if [ $compare == true ] ; then
         return 0
     else
-        echo; echo "FAILURE running compare_uda . . ."
-#        cd ..
-	cat $n.compare
         return 1
     fi
 }
@@ -380,27 +395,36 @@ run_restart () {
 
         echo; echo "Running: $MPI sus $opts -restart -t 0 -copy $uda_new.000"
         $MPI ../sus $opts -restart -t 0 -copy $uda_new.000 &> $n.out_restart
-        success=`grep "successfully" $n.out_restart`
-        if test -n "$success"; then 
-            echo $success
+        if [ $? -eq 0 ] ; then
+            echo "Sus: going down successfully"
+            echo
             echo "Comparing restart results"
             echo "compare_uda $uda_new.000 $uda_new.001"
             ../compare_uda $uda_new.000 $uda_new.001 &> $n.compare_restart
-            compare=`grep "passed" $n.compare_restart`
-            if test -n "$compare"; then
-                echo $compare
+            if [ $? -eq 0 ]; then
+                echo "compare restart passed . . . "
 		run_restart_return=0
             else
                 echo; echo "FAILURE running compare_uda on restart test . . ."
 		run_restart_return=1
             fi
+            echo
+            echo "Comparing restart results for checkpoints"
+            echo "compare_uda $uda_new.000/checkpoints $uda_new.001/checkpoints"
+            ../compare_uda $uda_new.000/checkpoints $uda_new.001/checkpoints &> $n.compare_restart_checkpoints
+            if [ $? -eq 0 ]; then
+                echo "compare restart checkpoints passed . . ."
+                run_restart_checkpoints=0
+            else
+                echo; echo "FAILURE running compare_uda on restart checkpoints"
+                run_restart_checkpoints=1
+            fi
         else
             echo; echo "FAILURE running sus . . ."
 	    run_restart_return=1
         fi
-#        cd ..
     fi
-    return $run_restart_return
+    return $run_restart_return && $run_restart_checkpoints
 }
 
 input_file () {
