Added highwater memory test

diff --git a/Packages/Uintah/Test/helpers/mem_leak_check b/Packages/Uintah/Test/helpers/mem_leak_check
--- a/Packages/Uintah/Test/helpers/mem_leak_check
+++ b/Packages/Uintah/Test/helpers/mem_leak_check
@@ -2,16 +2,33 @@
 
 TEST=$1
 MALLOC_STATS=$2
-TMPDIR=$3
-ERRORS_TO=$4
+COMPARISON_MALLOC_STATS=$3
+TMPDIR=$4
+ERRORS_TO=$5
 
 if [ ! -f $MALLOC_STATS ]; then
     echo "No malloc_stats output found.  Can't do memory leak test."
     exit 5
 fi
 
-grep 'src' $MALLOC_STATS > $TMPDIR/scinew_malloc_stats
+error=0
+
+grep '\.' $MALLOC_STATS > $TMPDIR/scinew_malloc_stats
 retval=$?
+if [ $retval == "0" ]; then
+    echo "Here are the object allocated with scinew but not deleted." > $TMPDIR/mem_error.txt
+    echo > $TMPDIR/mem_error.txt
+    cat $TMPDIR/scinew_malloc_stats >> $TMPDIR/mem_error.txt
+    error=1
+else
+    if [ ! -f $COMPARISON_MALLOC_STATS ]; then
+	cp $MALLOC_STATS $COMPARISON_MALLOC_STATS
+	exit -1
+    fi
+
+    highwater_check.pl $MALLOC_STATS $COMPARISON_MALLOC_STATS > $TMPDIR/mem_error.txt
+    error=$?
+fi
 
 if [ $retval == "0" ]; then
     echo "Memory leak test failed for $TEST."
@@ -21,15 +38,14 @@ Subject: *** Automated Memory Leak Alert ***
 To: $ERRORS_TO
 
 Memory leak test failed for $TEST.  
-Here are the object allocated with scinew but not deleted. 
 
 EOF
-        cat $TMPDIR/scinew_malloc_stats >> $TMPDIR/error.msg
+        cat $TMPDIR/mem_error.txt >> $TMPDIR/error.msg
 	/usr/lib/sendmail "$ERRORS_TO" < $TMPDIR/error.msg
         echo "Mail sent"
     fi
     exit 1
 fi
 
-exit 0
+exit $?
 
