always chgrp to csafe

diff --git a/Packages/Uintah/Test/helpers/replace_gold_standard b/Packages/Uintah/Test/helpers/replace_gold_standard
--- a/Packages/Uintah/Test/helpers/replace_gold_standard
+++ b/Packages/Uintah/Test/helpers/replace_gold_standard
@@ -47,6 +47,13 @@ if [ $yesno == "y" -o $yesno == "yes" ]; then
   if [ $? != "0" ]; then
     echo "No restart_malloc_stats -- ok"
   fi
+
+  echo "chgrp -R csafe $gold_standard_dir/$testname"
+  chgrp -R csafe "$gold_standard_dir/$testname"
+  if [ $? != "0" ]; then
+    echo "failed"
+    exit 1
+  fi
   echo "chmod -R g+w $gold_standard_dir/$testname"
   chmod -R g+w "$gold_standard_dir/$testname"
   if [ $? != "0" ]; then
