Correctly check for SCISock header files

diff --git a/v1_22_0/src/configure b/v1_22_0/src/configure
--- a/v1_22_0/src/configure
+++ b/v1_22_0/src/configure
@@ -21472,9 +21472,11 @@ fi
 _sci_optional=optional
 if test "$with_scisock"; then
   _sci_lib="$with_scisock/lib"
+  _sci_inc="$with_scisock/include"
   _sci_optional=specific
 else
   _sci_lib="$sci_thirdparty_libs"
+  _sci_inc="$sci_thirdparty_includes"
 fi
 
 
@@ -21512,8 +21514,8 @@ fi
 ##
 ## arg 1 : SCISOCK
 ## arg 2 : SCISock library
-## arg 3 :
-## arg 4 :
+## arg 3 : NetConnectionC.h NetInterfaceC.h unp.h
+## arg 4 : $_sci_inc
 ## arg 5 : scisock unp
 ## arg 6 : $_sci_lib
 ## arg 7 :
@@ -21553,7 +21555,47 @@ echo "$as_me: error: Last parameter of SCI-TRY-LINK for SCISock library must be:
    { (exit 1); exit 1; }; }
 fi
 
-# If  (the -I paths) is blank, do nothing, else do the for statement.
+# If $_sci_inc (the -I paths) is blank, do nothing, else do the for statement.
+
+for inc in $_sci_inc; do
+
+  if test "$inc" = "/usr/include" || test "$inc" = "-I/usr/include"; then
+     echo ""
+     { { echo "$as_me:$LINENO: error: Please do not specify /usr/include as the location for SCISOCK include files." >&5
+echo "$as_me: error: Please do not specify /usr/include as the location for SCISOCK include files." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  # Make sure it doesn't have any thing but -I
+  #   The following "sed" replaces anything that starts with a '-' with nothing (blank).
+  has_minus_faltivec=no
+  has_minus=`echo $inc | sed 's/-.*//'`
+  if test -z "$has_minus"; then
+     has_minus_i=`echo $inc | sed 's/-I.*//'`
+     has_minus_faltivec=`echo $inc | sed 's/-faltivec//'`
+     if test -n "$has_minus_i" && test -n "$has_minus_faltivec"; then
+        # Has some other -?.
+        if test "$debugging" = "yes"; then
+          echo
+          { echo "$as_me:$LINENO: WARNING: Only -I options are allowed in arg 4 ($_sci_inc) of SCISOCK check.  Skipping $inc." >&5
+echo "$as_me: WARNING: Only -I options are allowed in arg 4 ($_sci_inc) of SCISOCK check.  Skipping $inc." >&2;}
+        fi
+        continue
+     fi
+  fi
+
+  the_inc=`echo $inc | grep "\-I"`
+  if test -z "$the_inc" && test "$has_minus_faltivec" = "no"; then
+     # If the include arg does not already have -I on it.
+     if test -d $inc; then
+        # If the directory exists
+        _sci_includes="$_sci_includes -I$inc"
+     fi
+  else
+     # It already has -I so just add it directly.
+     _sci_includes="$_sci_includes $inc"
+  fi
+done
 
 ### Take care of arg 5 (the list of libs)
 
@@ -21671,10 +21713,10 @@ echo "$as_me: error: For specific SCI-TRY-LINK test for SCISOCK only one library
    { (exit 1); exit 1; }; }
   fi
   # and only one include path:
-  ### Determine if there is only one item in
+  ### Determine if there is only one item in $_sci_inc
   __sci_pass=false
   __sci_first_time=true
-  for value in "" ; do
+  for value in "" $_sci_inc; do
     if test "$value" = ""; then
       continue
     fi
@@ -21686,8 +21728,8 @@ echo "$as_me: error: For specific SCI-TRY-LINK test for SCISOCK only one library
     fi
   done
   if test $__sci_pass != "true"; then
-       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for SCISOCK only one include path may be specified for arg 4 (you had: ).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: For specific SCI-TRY-LINK test for SCISOCK only one include path may be specified for arg 4 (you had: ).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
+       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for SCISOCK only one include path may be specified for arg 4 (you had: $_sci_inc).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
+echo "$as_me: error: For specific SCI-TRY-LINK test for SCISOCK only one include path may be specified for arg 4 (you had: $_sci_inc).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
@@ -21706,7 +21748,7 @@ LIBS="$_sci_libs  $LIBS"
 __extern_c="no"
 __sci_pound_includes=""
 
-for inc in "" ; do
+for inc in "" NetConnectionC.h NetInterfaceC.h unp.h; do
     if test "$inc" = "extern_C"; then
        __sci_pound_includes="extern \"C\" {"
        __extern_c=yes
@@ -21874,11 +21916,11 @@ rm -f conftest.err conftest.$ac_objext \
 if test "$_sci_optional" = "specific"; then
 #echo specific
   # Make sure the exact includes were found
-  for i in "" ; do
-#echo looking for /$i
-    if test ! -e /$i; then
-     { { echo "$as_me:$LINENO: error: Specificly requested SCISOCK include file '/$i' was not found" >&5
-echo "$as_me: error: Specificly requested SCISOCK include file '/$i' was not found" >&2;}
+  for i in "" NetConnectionC.h NetInterfaceC.h unp.h; do
+#echo looking for $_sci_inc/$i
+    if test ! -e $_sci_inc/$i; then
+     { { echo "$as_me:$LINENO: error: Specificly requested SCISOCK include file '$_sci_inc/$i' was not found" >&5
+echo "$as_me: error: Specificly requested SCISOCK include file '$_sci_inc/$i' was not found" >&2;}
    { (exit 1); exit 1; }; }
     fi
   done
