Minor fixes to Nektar section of configure

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -502,15 +502,18 @@ AC_SUBST(ITCL_WIDGETS)
 echo -n "Looking for Pre-built Nektar... "
 
 AC_ARG_WITH(with_nektar,
-	[  --with-nektar=DIR		Use the globus installation in DIR],
+	[  --with-nektar=DIR		Use the nektar installation in DIR],
 	[with_nektar="$withval"],
 	[with_nektar=${with_nektar='no'}])
 
-if ! test "$with_nextar" = "no"; then
+if ! test "$with_nektar" = "no"; then
   NEKTAR_PREFIX=${with_nektar}
   NEKTAR_INCLUDE_DIR="${NEKTAR_PREFIX}/include"
-  NEKTAR_LIB_DIR="${NEKTAR_PREFIX/lib"
+  NEKTAR_LIB_DIR="${NEKTAR_PREFIX}/lib"
   NEKTAR_LIB_FLAG="-lhybridopt -lvec"
+  echo ${NEKTAR_PREFIX}
+else
+  echo "not found"
 fi
 
 ##-- Find etags ------------------------------------------------------------
@@ -724,6 +727,9 @@ AC_OUTPUT(Makefile \
 
 #
 # $Log$
+# Revision 1.63  2000/08/10 14:29:34  jehall
+# Minor fixes to Nektar section of configure
+#
 # Revision 1.62  2000/08/10 03:33:36  yarden
 # add --with-nektar
 #
