M    configure.ac M    configure
- Allow --without-hypre and --without-petsc (to turn off hypre/petsc).
  Note, for historical reasons (Ie, I think we just didn't do it),
  none of the other configure options (I belive) support --without.
  It probably would be nice to add them in.

M    CCA/Components/Solvers/AMR/sub.mk
M    CCA/Components/Solvers/sub.mk

- Indentation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -41727,62 +41727,69 @@ echo "$as_me: error: PETSC_ARCH environment var is not set.  Please set." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-# Make sure we have either mpi or mpi-uni, blas, and lapack
-# It seems that under AIX and OSF, the libs that cover blas also cover lapack
-if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") && test "$HAVE_BLAS" = "yes" &&
-   (test "$PETSC_ARCH" = "aix5.1.0.0" || test "$PETSC_ARCH" = "dec" ||
-    test "$HAVE_LAPACK" = "yes"); then
+# Handle --without option
 
-  _sci_lib_dir=
-  _sci_inc=
+if test "$with_petsc" == "no"; then
+  { echo "$as_me:$LINENO: WARNING: \"PETSc disabled.\" " >&5
+echo "$as_me: WARNING: \"PETSc disabled.\" " >&2;}
+else
 
-  for petsc_arch in "$PETSC_ARCH" linux-gnu linux-gnu-c-opt; do
-    if test "$HAVE_PETSC" = "yes"; then
-      break
-    fi
+  # Make sure we have either mpi or mpi-uni, blas, and lapack
+  # It seems that under AIX and OSF, the libs that cover blas also cover lapack
+  if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") && test "$HAVE_BLAS" = "yes" &&
+     (test "$PETSC_ARCH" = "aix5.1.0.0" || test "$PETSC_ARCH" = "dec" ||
+      test "$HAVE_LAPACK" = "yes"); then
 
-    PETSC_SUB=lib/libO
+    _sci_lib_dir=
+    _sci_inc=
 
-    if test "$with_petsc"; then
-
-      ####################################################
-      # The newer (2.3+) versions of petsc don't use the libO anymore...
-      have23=`echo "$with_petsc" | grep "2.3."`
-      if test -z "$have23" ; then
-         petsc_version_major=`grep PETSC_VERSION_MAJOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
-         petsc_version_minor=`grep PETSC_VERSION_MINOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
-         if test "$petsc_version_major" -eq 2 ; then
-            if test "$petsc_version_minor" -eq 3 ; then
-               have23=true
-            fi
-         fi
+    for petsc_arch in "$PETSC_ARCH" linux-gnu linux-gnu-c-opt; do
+      if test "$HAVE_PETSC" = "yes"; then
+        break
       fi
-      if test "$have23"; then
-         PETSC_SUB=lib
+
+      PETSC_SUB=lib/libO
+
+      if test "$with_petsc"; then
+
+        ####################################################
+        # The newer (2.3+) versions of petsc don't use the libO anymore...
+        have23=`echo "$with_petsc" | grep "2.3."`
+        if test -z "$have23" ; then
+           petsc_version_major=`grep PETSC_VERSION_MAJOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
+           petsc_version_minor=`grep PETSC_VERSION_MINOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
+           if test "$petsc_version_major" -eq 2 ; then
+              if test "$petsc_version_minor" -eq 3 ; then
+                 have23=true
+              fi
+           fi
+        fi
+        if test "$have23"; then
+           PETSC_SUB=lib
+        fi
+        ####################################################
+
+        _sci_lib_dir="$with_petsc/$PETSC_SUB/$petsc_arch"
+        _sci_inc="$with_petsc/bmake/$petsc_arch $with_petsc/include"
+      else
+        # Modify _sci_dirs to have correct path information:
+        for i in $sci_thirdparty_dir; do
+          if test ! -d "$i"; then
+            continue
+          fi
+
+          #this is where the lib actually lives
+          if test ! -d "$i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"; then
+            continue
+          fi
+
+          _sci_lib_dir="$_sci_lib_dir $i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"
+          _sci_inc="$_sci_inc $i/$PETSC_VERSION_DIR/include $i/$PETSC_VERSION_DIR/bmake/$petsc_arch"
+        done
       fi
-      ####################################################
 
-      _sci_lib_dir="$with_petsc/$PETSC_SUB/$petsc_arch"
-      _sci_inc="$with_petsc/bmake/$petsc_arch $with_petsc/include"
-    else
-      # Modify _sci_dirs to have correct path information:
-      for i in $sci_thirdparty_dir; do
-        if test ! -d "$i"; then
-          continue
-        fi
-
-        #this is where the lib actually lives
-        if test ! -d "$i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"; then
-          continue
-        fi
-
-        _sci_lib_dir="$_sci_lib_dir $i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"
-        _sci_inc="$_sci_inc $i/$PETSC_VERSION_DIR/include $i/$PETSC_VERSION_DIR/bmake/$petsc_arch"
-      done
-    fi
-
-    # For Petsc 2.2 use this line below:   petsc petscvec petscmat petscdm petscsnes petscts petscksp $LAPACK_LIB_FLAG $BLAS_LIB_FLAG $M_LIB_FLAG $MPI_LIB_FLAG $F_LIB_DIR_FLAG $F_LIB_FLAG $DL_LIB_FLAG,
-    # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
+      # For Petsc 2.2 use this line below:   petsc petscvec petscmat petscdm petscsnes petscts petscksp $LAPACK_LIB_FLAG $BLAS_LIB_FLAG $M_LIB_FLAG $MPI_LIB_FLAG $F_LIB_DIR_FLAG $F_LIB_FLAG $DL_LIB_FLAG,
+      # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
 
 
 ##
@@ -42268,33 +42275,33 @@ _sci_includes=''
 
 
 
-    if test "$HAVE_PETSC" = "yes" ; then
-      DEF_PETSC="#define HAVE_PETSC 1"
-    fi
-  done
-  if test "$with_petsc" && test ! "$DEF_PETSC"; then
-    echo
-    { { echo "$as_me:$LINENO: error: One or more of the PETSc components is missing." >&5
+      if test "$HAVE_PETSC" = "yes" ; then
+        DEF_PETSC="#define HAVE_PETSC 1"
+      fi
+    done
+    if test "$with_petsc" && test ! "$DEF_PETSC"; then
+      echo
+      { { echo "$as_me:$LINENO: error: One or more of the PETSc components is missing." >&5
 echo "$as_me: error: One or more of the PETSc components is missing." >&2;}
    { (exit 1); exit 1; }; }
-    echo
-  fi
-
-  #  --  search for uni-petsc  --------------------------------------------
-
-  if test "$HAVE_PETSC" != "yes" ; then
-
-    # Only check for uni petsc if petsc not found.
-    _sci_lib=""
-    _sci_inc=""
-
-    if test "$with_unipetsc"; then
-      _sci_lib="$with_unipetsc/$PETSC_SUB/$PETSC_ARCH"
-      _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
+      echo
     fi
 
-    # For petsc 2.2 use this line below:  petsc petscvec petscmat petscdm petscsnes petscts petscksp,
-    # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
+    #  --  search for uni-petsc  --------------------------------------------
+
+    if test "$HAVE_PETSC" != "yes" ; then
+
+      # Only check for uni petsc if petsc not found.
+      _sci_lib=""
+      _sci_inc=""
+
+      if test "$with_unipetsc"; then
+        _sci_lib="$with_unipetsc/$PETSC_SUB/$PETSC_ARCH"
+        _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
+      fi
+
+      # For petsc 2.2 use this line below:  petsc petscvec petscmat petscdm petscsnes petscts petscksp,
+      # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
 
 ##
 ## SCI_TRY_LINK (PETSC_UNI):  petsc-uni libraries and headers
@@ -42779,10 +42786,10 @@ _sci_includes=''
 
 
 
-    if test "$HAVE_PETSC_UNI" = "yes" ; then
-      DEF_PETSC_UNI="#define PETSC_UNI 1"
-    else
-      # Give it a shot on the old petsc-uni version
+      if test "$HAVE_PETSC_UNI" = "yes" ; then
+        DEF_PETSC_UNI="#define PETSC_UNI 1"
+      else
+        # Give it a shot on the old petsc-uni version
 
 ##
 ## SCI_TRY_LINK (PETSC_UNI):  petsc libraries and headers - old2
@@ -43266,33 +43273,34 @@ _sci_includes=''
 ##
 
 
-      if test "$HAVE_PETSC_UNI" = "yes" ; then
-        DEF_PETSC_UNI="#define PETSC_UNI 1"
+        if test "$HAVE_PETSC_UNI" = "yes" ; then
+          DEF_PETSC_UNI="#define PETSC_UNI 1"
+        fi
+      fi
+
+      if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
+        echo
+        { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
+echo "$as_me: error: One or more of the UNI-PETSC components is missing." >&2;}
+   { (exit 1); exit 1; }; }
+        echo
       fi
     fi
 
-    if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
-      echo
-      { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
-echo "$as_me: error: One or more of the UNI-PETSC components is missing." >&2;}
-   { (exit 1); exit 1; }; }
-      echo
-    fi
-  fi
-
-else
-  { echo "$as_me:$LINENO: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&5
+  else
+    { echo "$as_me:$LINENO: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&5
 echo "$as_me: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&2;}
-  { echo "$as_me:$LINENO: WARNING: HAVE_MPI: $HAVE_MPI" >&5
+    { echo "$as_me:$LINENO: WARNING: HAVE_MPI: $HAVE_MPI" >&5
 echo "$as_me: WARNING: HAVE_MPI: $HAVE_MPI" >&2;}
-  { echo "$as_me:$LINENO: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&5
+    { echo "$as_me:$LINENO: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&5
 echo "$as_me: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&2;}
-  { echo "$as_me:$LINENO: WARNING: HAVE_BLAS: $HAVE_BLAS" >&5
+    { echo "$as_me:$LINENO: WARNING: HAVE_BLAS: $HAVE_BLAS" >&5
 echo "$as_me: WARNING: HAVE_BLAS: $HAVE_BLAS" >&2;}
-  { echo "$as_me:$LINENO: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&5
+    { echo "$as_me:$LINENO: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&5
 echo "$as_me: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&2;}
-  { echo "$as_me:$LINENO: WARNING: Not configuring PETSc." >&5
+    { echo "$as_me:$LINENO: WARNING: Not configuring PETSc." >&5
 echo "$as_me: WARNING: Not configuring PETSc." >&2;}
+  fi
 fi
 
 
@@ -45404,24 +45412,29 @@ _sci_lib=
 _sci_inc=
 _sci_optional=optional
 
-if test "$with_hypre" = "yes"; then
-  _sci_optional=required
-elif test "$with_hypre"; then
-  _sci_lib="$with_hypre/lib"
-  _sci_inc="$with_hypre/include"
-  _sci_optional=specific
-fi
+# Handle --without option
+if test "$with_hypre" = "no"; then
+   { echo "$as_me:$LINENO: WARNING: \"Hypre is turned off.\" " >&5
+echo "$as_me: WARNING: \"Hypre is turned off.\" " >&2;}
+else
+   if test "$with_hypre" = "yes"; then
+      _sci_optional=required
+   elif test "$with_hypre"; then
+      _sci_lib="$with_hypre/lib"
+      _sci_inc="$with_hypre/include"
+      _sci_optional=specific
+   fi
 
-# # We used to also check for HYPRE_blas, but hypre 1.9 doesn't have it,
-# # so we aren't going to check for it in any version.  If the other 3
-# # libs exist, we will assume that HYPRE_blas is there if it is needed.
-# SCI_TRY_LINK(HYPRE,HYPRE libraries and headers,HYPRE.h,$_sci_inc,
-#                          HYPRE_struct_mv HYPRE_struct_ls HYPRE_sstruct_mv HYPRE_sstruct_ls HYPRE_LSI HYPRE_superlu HYPRE_utilities,
-#                          $_sci_lib,-lm,,$_sci_optional)
+   # # We used to also check for HYPRE_blas, but hypre 1.9 doesn't have it,
+   # # so we aren't going to check for it in any version.  If the other 3
+   # # libs exist, we will assume that HYPRE_blas is there if it is needed.
+   # SCI_TRY_LINK(HYPRE,HYPRE libraries and headers,HYPRE.h,$_sci_inc,
+   #                          HYPRE_struct_mv HYPRE_struct_ls HYPRE_sstruct_mv HYPRE_sstruct_ls HYPRE_LSI HYPRE_superlu HYPRE_utilities,
+   #                          $_sci_lib,-lm,,$_sci_optional)
 
-# We should just be able to link vs. libHYPRE.so...
-#   Also, libHYPRE has some C++ stuff in it, so we need to be in C++ mode...
-ac_ext=cpp
+   # We should just be able to link vs. libHYPRE.so...
+   #   Also, libHYPRE has some C++ stuff in it, so we need to be in C++ mode...
+   ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -45910,22 +45923,23 @@ _sci_includes=''
 ##
 
 
-ac_ext=c
+   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-if test "$HAVE_HYPRE" = "yes" ; then
-  DEF_HYPRE="#define HAVE_HYPRE 1"
-fi
+   if test "$HAVE_HYPRE" = "yes" ; then
+      DEF_HYPRE="#define HAVE_HYPRE 1"
+   fi
 
-if test "$with_hypre" && test ! "$DEF_HYPRE"; then
-  echo
-  { { echo "$as_me:$LINENO: error: One or more of the HYPRE components is missing." >&5
+   if test "$with_hypre" && test ! "$DEF_HYPRE"; then
+      echo
+      { { echo "$as_me:$LINENO: error: One or more of the HYPRE components is missing." >&5
 echo "$as_me: error: One or more of the HYPRE components is missing." >&2;}
    { (exit 1); exit 1; }; }
+   fi
 fi
 
 
