M    configure M    configure.ac
- Cleaned up use of IMPORTANT_WARNINGS (is now an easy to use function)
- Turn on Wasatch automatically if all required libs are found
  - Print error message if user explicitly calls for Wasatch and libs not found.
- Warn user when they specify 'optimize' but don't turn off assertions.
- Allow boost to be in /usr (but don't place -L/usr/lib and -I/usr/include 
    into the build system (as this can polute other things).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -726,7 +726,6 @@ BUILD_ARCHES
 BUILD_ICE
 BUILD_MPM
 BUILD_RADIATION
-BUILD_WASATCH
 DEF_ARCHES
 DEF_ICE
 DEF_MPM
@@ -901,6 +900,7 @@ DEF_TABPROPS
 INC_TABPROPS_H
 TABPROPS_LIB_FLAG
 TABPROPS_LIB_DIR_FLAG
+BUILD_WASATCH
 HAVE_HYPRE
 DEF_HYPRE
 INC_HYPRE_H
@@ -1521,7 +1521,8 @@ Optional Features:
                           Force all new'd and malloc'd memory to be initialied
                           to the value given - defaults to 127.
 --enable-assertion-level=N
-                          Use assertion level N (0-3)
+                          Use assertion level N (0-3) (Where 0 turns off
+                          assertions, and 3 turns on all assertions.)
 --enable-scinew-line-numbers
                           Have SCI malloc store the file and line that calls
                           'scinew'
@@ -2070,13 +2071,18 @@ WOFF_NUMBERS=
 
 ##
 ## Used to store warnings that should be redisplayed to the user at the
-## end of configure in hopes that the user actually sees them.  Note,
-## the syntax and use of IMPORTANT_WARNINGS is somewhat picky.  See the
-## 'Check for 64 vs 80 bit floating point number' section below for an
-## example of its use.  (Make sure to increment NUM_IMPORTANT_WARNINGS.)
+## end of configure in hopes that the user actually sees them.
+##
+## Use 'add_important_warning()' to add a warning.
 ##
 declare -a IMPORTANT_WARNINGS
 NUM_IMPORTANT_WARNINGS=0
+add_important_warning()
+{
+   # Note: need '[[' below to get autoconf to create a single '[' in the actual configure file.
+   IMPORTANT_WARNINGS[$NUM_IMPORTANT_WARNINGS]=$1
+   ((NUM_IMPORTANT_WARNINGS++))
+}
 
 ## Clean up files that could be left around if configure was
 ## interrupted (by control-c, ^c) because I do not know how to add
@@ -2301,6 +2307,18 @@ fi
 ##  initialize the recognized argument lists
 sci_arg_with_list="--no-create --no-recursion"
 sci_arg_enable_list=""
+
+##  --------------------------------------------------------------------
+##  ------------------  optional variable intialization  ---------------
+##  --------------------------------------------------------------------
+
+# Setting variables to 'no' isn't required, but is useful in displaying
+# some error condition information to the user.
+HAVE_HDF5="no"
+HAVE_BOOST="no"
+HAVE_TABPROPS="no"
+HAVE_SPATIALOPS="no"
+HAVE_EXPRLIB="no"
 
 ##  --------------------------------------------------------------------
 ##  ------------------  check for all arguments     --------------------
@@ -6882,6 +6900,13 @@ else
 echo "${ECHO_T}yes ($optimize) " >&6; }
 fi
 
+# Check to see if assertions are off but optimize is on... and warn user if so...
+if test "$optimize" != "no"; then
+  if test "$ASSERTION_LEVEL" != "0"; then
+    add_important_warning "FYI: You specified an optimized build, but have not turned off assertions... (Use: --enable-assertion-level=0 for fastest performance.)"
+  fi
+fi
+
 if test ! -e "`type $CC | sed 's%^.* /%/%'`"; then
 
 ## SCI_MSG_ERROR
@@ -6977,11 +7002,8 @@ if test "$with_fortran" = no; then
             DEF_NO_FORTRAN="#define NO_FORTRAN";
             NO_FORTRAN="yes";
 fi
-if test "$USE_WASATCH" = yes; then BUILD_WASATCH=yes; fi
-if test "$BUILD_WASATCH" = no; then DEF_WASATCH="#define NO_WASATCH"; fi
 
 # NO_FORTRAN is used in configVars.mk[.in] and DEF_NO_FORTRAN is used in uintah_testdefs.h.in
-
 
 
 
@@ -7406,9 +7428,7 @@ echo "$as_me: WARNING: Floating point - usually 64 vs 80 bit - register precissi
 echo "$as_me: WARNING: Disabling use of floating point registers with '-ffloat-store' compiler flag. " >&2;}
    { echo "$as_me:$LINENO: WARNING: ----------------------------------------------------------------------------------------- " >&5
 echo "$as_me: WARNING: ----------------------------------------------------------------------------------------- " >&2;}
-   # Note: need '[[' below to get autoconf to create a single '[' in the actual configure file.
-   IMPORTANT_WARNINGS[$NUM_IMPORTANT_WARNINGS]="Automatically added -ffloat-store compiler option to C/CXXFLAGS."
-   ((NUM_IMPORTANT_WARNINGS++))
+   add_important_warning "Automatically added -ffloat-store compiler option to C/CXXFLAGS."
    CFLAGS="$CFLAGS -ffloat-store"
    CXXFLAGS="$CXXFLAGS -ffloat-store"
    # Verify that the compiler accepts the -ffloat-store flag:
@@ -45096,8 +45116,11 @@ echo "$as_me: error: $BOOST_LIB_DIR/$short_name lib does not exist!" >&2;}
   { echo "$as_me:$LINENO: result: Found Boost" >&5
 echo "${ECHO_T}Found Boost" >&6; }
   DEF_BOOST="#define HAVE_BOOST 1"
-  INC_BOOST_H="-I$with_boost/include"
-  BOOST_LIB_DIR_FLAG="-L$with_boost/lib"
+  if test "$with_boost" != "/usr"; then
+    # If with_boost points to /usr, then we don't need to explicitly point to it...
+    INC_BOOST_H="-I$with_boost/include"
+    BOOST_LIB_DIR_FLAG="-L$with_boost/lib"
+  fi
   HAVE_BOOST="yes"
 fi
 
@@ -45261,6 +45284,37 @@ fi
 
 
 
+
+
+##  --  Determine whether we can use WASATCH OR NOT ----------------------
+
+if test "$USE_WASATCH" = yes; then
+  if test "$HAVE_HDF5" == "yes" &&
+     test "$HAVE_BOOST" == "yes" &&
+     test "$HAVE_TABPROPS" == "yes" &&
+     test "$HAVE_SPATIALOPS" == "yes" &&
+     test "$HAVE_EXPRLIB" == "yes"; then
+    BUILD_WASATCH=yes
+  else
+    { { echo "$as_me:$LINENO: error: You specified the use of the Wasatch component but do not have all the of the prereqs: HDF5 ($HAVE_HDF5); Boost ($HAVE_BOOST); TabProps ($HAVE_TABPROPS); SpatialOps ($HAVE_SPATIALOPS); and ExprLib ($HAVE_EXPRLIB)." >&5
+echo "$as_me: error: You specified the use of the Wasatch component but do not have all the of the prereqs: HDF5 ($HAVE_HDF5); Boost ($HAVE_BOOST); TabProps ($HAVE_TABPROPS); SpatialOps ($HAVE_SPATIALOPS); and ExprLib ($HAVE_EXPRLIB)." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+else
+  if test "$HAVE_HDF5" == "yes" &&
+     test "$HAVE_BOOST" == "yes" &&
+     test "$HAVE_TABPROPS" == "yes" &&
+     test "$HAVE_SPATIALOPS" == "yes" &&
+     test "$HAVE_EXPRLIB" == "yes"; then
+    BUILD_WASATCH=yes
+    { echo "$as_me:$LINENO: WARNING: All prereqs satisfied" >&5
+echo "$as_me: WARNING: All prereqs satisfied" >&2;}
+  fi
+fi
+
+if test "$BUILD_WASATCH" = no; then
+  DEF_WASATCH="#define NO_WASATCH";
+fi
 
 
 ##  --  search for hypre stuff  ------------------------------------------
@@ -46604,7 +46658,6 @@ BUILD_ARCHES!$BUILD_ARCHES$ac_delim
 BUILD_ICE!$BUILD_ICE$ac_delim
 BUILD_MPM!$BUILD_MPM$ac_delim
 BUILD_RADIATION!$BUILD_RADIATION$ac_delim
-BUILD_WASATCH!$BUILD_WASATCH$ac_delim
 DEF_ARCHES!$DEF_ARCHES$ac_delim
 DEF_ICE!$DEF_ICE$ac_delim
 DEF_MPM!$DEF_MPM$ac_delim
@@ -46619,6 +46672,7 @@ SOFLAGS!$SOFLAGS$ac_delim
 IS_STATIC_BUILD!$IS_STATIC_BUILD$ac_delim
 SO_OR_ARCHIVE_EXTENSION!$SO_OR_ARCHIVE_EXTENSION$ac_delim
 DEF_MALLOC_TRACE!$DEF_MALLOC_TRACE$ac_delim
+INC_MALLOC_TRACE_H!$INC_MALLOC_TRACE_H$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -46660,7 +46714,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-INC_MALLOC_TRACE_H!$INC_MALLOC_TRACE_H$ac_delim
 MALLOC_TRACE_LIB_FLAG!$MALLOC_TRACE_LIB_FLAG$ac_delim
 MALLOC_TRACE_LIB_DIR_FLAG!$MALLOC_TRACE_LIB_DIR_FLAG$ac_delim
 MALLOC_TRACE_LIB_MPI_FLAG!$MALLOC_TRACE_LIB_MPI_FLAG$ac_delim
@@ -46757,6 +46810,7 @@ HAVE_CBLAS!$HAVE_CBLAS$ac_delim
 INC_BLAS_H!$INC_BLAS_H$ac_delim
 BLAS_LIB_FLAG!$BLAS_LIB_FLAG$ac_delim
 BLAS_LIB_DIR_FLAG!$BLAS_LIB_DIR_FLAG$ac_delim
+DEF_BLAS!$DEF_BLAS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -46798,7 +46852,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-DEF_BLAS!$DEF_BLAS$ac_delim
 DEF_CBLAS!$DEF_CBLAS$ac_delim
 HAVE_LAPACK!$HAVE_LAPACK$ac_delim
 DEF_LAPACK!$DEF_LAPACK$ac_delim
@@ -46861,6 +46914,7 @@ DEF_TABPROPS!$DEF_TABPROPS$ac_delim
 INC_TABPROPS_H!$INC_TABPROPS_H$ac_delim
 TABPROPS_LIB_FLAG!$TABPROPS_LIB_FLAG$ac_delim
 TABPROPS_LIB_DIR_FLAG!$TABPROPS_LIB_DIR_FLAG$ac_delim
+BUILD_WASATCH!$BUILD_WASATCH$ac_delim
 HAVE_HYPRE!$HAVE_HYPRE$ac_delim
 DEF_HYPRE!$DEF_HYPRE$ac_delim
 INC_HYPRE_H!$INC_HYPRE_H$ac_delim
