Fixed Freetype check.  Cleaned up some stuff, some syncing with branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15917,7 +15917,7 @@ _sci_includes=''
 # -- tk --
 if test -f "$_sci_lib/tkConfig.sh"; then
   . $_sci_lib/tkConfig.sh;
-  _sci_tk_inc="$_sci_inc $TK_SRC_DIR/generic"
+  _sci_tk_inc="$_sci_inc $TK_SRC_DIR/generic $TK_SRC_DIR/unix"
 fi
 
 # Note: TK_DEFS (used below to help resolve tk issues) comes from tkConfig.sh
@@ -27987,7 +27987,7 @@ if test "$HAVE_BLAS" != "yes"; then
   # if HAVE_BLAS is yes at this point, then atlas has been found and we
   # don't want to check for blas.
 
-  if test "$with_blas"; then
+  if test "$with_blas" && test "$with_blas" != "yes"; then
     _sci_lib="$with_blas/lib"
     _sci_inc="$with_blas/include"
     _sci_specific=yes
@@ -42327,16 +42327,14 @@ echo $ECHO_N "checking for $_sci_optional freetype... $ECHO_C" >&6
 
 found_freetype_config="no"
 
-for dir in "" $_sci_lib; do
+if test -e $_sci_lib/../bin/freetype-config; then
+    found_freetype_config="yes"
+    echo
+    echo "$as_me:$LINENO: result: Using $_sci_lib/../bin/freetype-config to set freetype variables." >&5
+echo "${ECHO_T}Using $_sci_lib/../bin/freetype-config to set freetype variables." >&6
 
-   if test -e $dir/../bin/freetype-config; then
-       found_freetype_config="yes"
-       echo
-       echo "$as_me:$LINENO: result: Using $dir/../bin/freetype-config to set freetype variables." >&5
-echo "${ECHO_T}Using $dir/../bin/freetype-config to set freetype variables." >&6
-
-       includes=`$dir/../bin/freetype-config --cflags`
-       FREETYPE_LIB_FLAG=`$dir/../bin/freetype-config --libs`
+    includes=`$_sci_lib/../bin/freetype-config --cflags`
+    FREETYPE_LIB_FLAG=`$_sci_lib/../bin/freetype-config --libs`
 
 
 ##
@@ -42376,7 +42374,7 @@ echo "${ECHO_T}Using $dir/../bin/freetype-config to set freetype variables." >&6
 ## arg 3 : ft2build.h
 ## arg 4 : $_sci_inc
 ## arg 5 : $FREETYPE_LIB_FLAG
-## arg 6 : $dir
+## arg 6 : $_sci_lib
 ## arg 7 : $includes
 ## arg 8 : <Can't expand it here as it may be multiple lines and cause sh problems.>
 ## arg 9 : $_sci_optional
@@ -42512,9 +42510,9 @@ fi
 
 ### Take care of arg 6 (the list of lib paths)
 
-if test -n "$dir"; then
+if test -n "$_sci_lib"; then
 
-   for path in "" $dir; do
+   for path in "" $_sci_lib; do
 
       if test -z "$path"; then
          # SGI sh needs the "" in the for statement... so skip it here.
@@ -42550,12 +42548,12 @@ fi
 
 if test "$_sci_optional" = "specific"; then
   # If 'specific' then only one lib is allowed:
-  ### Determine if there is only one item in $dir (I don't know of a better way to do this.)
+  ### Determine if there is only one item in $_sci_lib (I don't know of a better way to do this.)
   __sci_pass=false
   __sci_first_time=true
 
   # Must have the "" for the SGI sh.
-  for value in "" $dir; do
+  for value in "" $_sci_lib; do
     if test "$value" = ""; then
       continue
     fi
@@ -42567,8 +42565,8 @@ if test "$_sci_optional" = "specific"; then
     fi
   done
   if test $__sci_pass != "true"; then
-       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for FREETYPE only one library path may be specified for arg 6 (you had: $dir).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: For specific SCI-TRY-LINK test for FREETYPE only one library path may be specified for arg 6 (you had: $dir).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
+       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for FREETYPE only one library path may be specified for arg 6 (you had: $_sci_lib).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
+echo "$as_me: error: For specific SCI-TRY-LINK test for FREETYPE only one library path may be specified for arg 6 (you had: $_sci_lib).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
    { (exit 1); exit 1; }; }
   fi
   # and only one include path:
@@ -42665,7 +42663,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-eval LIB_DIR_FREETYPE='"$dir"'
+eval LIB_DIR_FREETYPE='"$_sci_lib"'
 
 # Remove any bad (/usr/lib) lib paths and the thirdparty lib path
 _final_dirs=
@@ -42793,10 +42791,10 @@ echo "$as_me: error: Specifically requested FREETYPE include file '$_sci_inc/$i'
     if test -z "$has_minus"; then
        i=`echo $i | sed 's/-l//g'`
     fi
-echo looking for $dir/$i
-    if test ! -e $dir/lib$i.so && test ! -e $dir/lib$i.a; then
-     { { echo "$as_me:$LINENO: error: Specifically requested FREETYPE library file '$dir/$i' (.so or .a) was not found" >&5
-echo "$as_me: error: Specifically requested FREETYPE library file '$dir/$i' (.so or .a) was not found" >&2;}
+echo looking for $_sci_lib/$i
+    if test ! -e $_sci_lib/lib$i.so && test ! -e $_sci_lib/lib$i.a; then
+     { { echo "$as_me:$LINENO: error: Specifically requested FREETYPE library file '$_sci_lib/$i' (.so or .a) was not found" >&5
+echo "$as_me: error: Specifically requested FREETYPE library file '$_sci_lib/$i' (.so or .a) was not found" >&2;}
    { (exit 1); exit 1; }; }
     fi
   done
@@ -42818,12 +42816,10 @@ _sci_includes=''
 
 
 
-       INC_FREETYPE_H="$INC_FREETYPE_H $includes"
+    INC_FREETYPE_H="$INC_FREETYPE_H $includes"
 
-       DEF_FREETYPE="#define HAVE_FREETYPE 1"
-       break
-    fi
-done
+    DEF_FREETYPE="#define HAVE_FREETYPE 1"
+fi
 
 if test "$found_freetype_config" = "no"; then
    echo "$as_me:$LINENO: result: no." >&5
@@ -44969,14 +44965,11 @@ if test "$sci_required_hdf5" = "yes"; then
 
   _sci_optional=required
   if test "$with_hdf5"; then
-    _sci_lib="$with_hdf5/lib"			# user defined directory
-    _sci_inc="$with_hdf5/include"
-    _sci_optional=specific
-  else
-#   _sci_lib="/usr/local/lib"			# default directory
-#   _sci_inc="/usr/local/include"
-    _sci_lib="$sci_thirdparty_lib"
-    _sci_inc="$sci_thirdparty_include"
+    if test "$with_hdf5" != "yes"; then
+      _sci_lib="$with_hdf5/lib"			# user defined directory
+      _sci_inc="$with_hdf5/include"
+      _sci_optional=specific
+    fi
   fi
 
 
