Fix teem check when rtrt enabled.  Grep for png_write_info instead of just png.  Removed spurious ;

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -28263,327 +28263,30 @@ if test "$sci_required_teem" = "yes"; then
     _sci_lib="$sci_thirdparty_libs"
     _sci_inc="$sci_thirdparty_includes"
   fi
+  _sci_optional=required
 
-  if test "$sci_required_rtrt" = "yes"; then
-
-##
-## SCI_TRY_LINK:
-##
-## arguments mean:
-## arg 1 : variable base name i.e. MATH
-## arg 2 : checking message
-## arg 3 : includes that arg 6 needs to compile
-## arg 4 : include path -I (Only one may be given)
-## arg 5 : list of libs to link against (note, this script adds -l to each name.)
-## arg 6 : lib paths (note, this script adds -L to each name.)
-## arg 7 : extra link flags
-## arg 8 : body of code to compile. can be empty
-## arg 9 : 'optional' or 'required' or 'specific' required argument
-##             If specific, then SCI_TRY_LINK will take only one lib
-##             path and one include path and will verify that the
-##             libs/includes are in that path.
-##
-## after execution of macro, the following will be defined:
-##      Variable            Value
-##      --------            -----
-##      LIB_DIR_TEEM        => lib path
-##      TEEM_LIB_DIR_FLAG   => all the -L's
-##      TEEM_LIB_FLAG       => all the -l's
-##      HAVE_TEEM           => yes or no
-##      INC_TEEM_H          => all the -I's
-##      HAVE_TEEM_H         => yes or no
-
-if test 9 != 9; then
-     { { echo "$as_me:$LINENO: error: Wrong number of parameters (9) for SCI-TRY-LINK for teem library and headers.  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: Wrong number of parameters (9) for SCI-TRY-LINK for teem library and headers.  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-
-echo "$as_me:$LINENO: checking for teem library and headers (optional)" >&5
-echo $ECHO_N "checking for teem library and headers (optional)... $ECHO_C" >&6
-_sci_savelibs=$LIBS
-_sci_saveldflags=$LDFLAGS
-_sci_savecflags=$CFLAGS
-_sci_savecxxflags=$CXXFLAGS
-
-_sci_includes=
-
-if test "optional" != "optional" -a "optional" != "required" -a "optional" != "specific"; then
-     { { echo "$as_me:$LINENO: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had optional.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had optional.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-# If $_sci_inc (the -I paths) is blank, do nothing, else do the for statement.
-
-for i in $_sci_inc; do
-  if test "$i" = "/usr/include"; then
-     echo ""
-     { { echo "$as_me:$LINENO: error: Please do not specify /usr/include as the location for teem library and headers include files." >&5
-echo "$as_me: error: Please do not specify /usr/include as the location for teem library and headers include files." >&2;}
-   { (exit 1); exit 1; }; }
+  if test "$pkg_rtrt" = "yes" && test "$pkg_BioPSE" != "yes" && test "$pkg_teem" != "yes" && test "$pkg_MatlabInterface" != "yes" && test "$pkg_uintah" != "yes"; then
+     _sci_optional=optional
   fi
-  # make sure it exists
-  if test -d $i; then
-    if test -z "$_sci_includes"; then
-      _sci_includes=-I$i
-    else
-      _sci_includes="$_sci_includes -I$i"
-    fi
-  fi
-done
 
-if test "optional" = "specific"; then
-  # If 'specific' then only one lib is allowed:
-  ### Determine if there is only one item in $_sci_lib m (I don't know of a better way to do this.)
-  __sci_pass=false
-  __sci_first_time=true
+  # Determine if teem is using png.  Assume teem is either in the 3rd Party
+  # or where the user has specified (as we are going to use nm to look at its
+  # symbols and are not trying to link against it (at this point.))
 
-  # Must have the "" for the SGI sh.
-  for value in "" $_sci_lib m; do
-    if test "$value" = "/usr/lib"; then
-       echo ""
-       { { echo "$as_me:$LINENO: error: Please do not specify /usr/lib as the location for libs teem." >&5
-echo "$as_me: error: Please do not specify /usr/lib as the location for libs teem." >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    if test "$value" = ""; then
-      continue
-    fi
-    if test $__sci_first_time = "true"; then
-      __sci_first_time=false
-      __sci_pass=true
-    else
-      __sci_pass=false
-    fi
-  done
-  if test $__sci_pass != "true"; then
-       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for teem library and headers only one library path may be specified (you had: $_sci_lib m).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: For specific SCI-TRY-LINK test for teem library and headers only one library path may be specified (you had: $_sci_lib m).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-  # and only one include path:
-  ### Determine if there is only one item in $_sci_inc
-  __sci_pass=false
-  __sci_first_time=true
-  for value in ""$_sci_inc; do
-    if test "$value" = ""; then
-      continue
-    fi
-    if test $__sci_first_time = "true"; then
-      __sci_first_time=false
-      __sci_pass=true
-    else
-      __sci_pass=false
-    fi
-  done
-  if test $__sci_pass != "true"; then
-       { { echo "$as_me:$LINENO: error: For specific SCI-TRY-LINK test for teem library and headers only one include path may be specified (you had: $_sci_inc).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: For specific SCI-TRY-LINK test for teem library and headers only one include path may be specified (you had: $_sci_inc).  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-fi
-
-
-for i in teem; do
-  if test -z "$_sci_libs"; then
-    _sci_libs=-l$i
-  else
-    _sci_libs="$_sci_libs -l$i"
-  fi
-done
-
-_sci_lib_path=
-
-for i in $_sci_lib m; do
-  # make sure it exists
-  if test -d $i; then
-    if test -z "$_sci_lib_path"; then
-      _sci_lib_path="$LDRUN_PREFIX$i -L$i"
-    else
-      _sci_lib_path="$_sci_lib_path $LDRUN_PREFIX$i -L$i"
-    fi
-  fi
-done
-
-CFLAGS="$_sci_includes $CFLAGS"
-CXXFLAGS="$_sci_includes $CXXFLAGS"
-LDFLAGS="$_sci_lib_path $LDFLAGS"
-LIBS="$_sci_libs  $LIBS"
-
-# Build up a list of the #include <file> lines for use in compilation:
-__sci_pound_includes=
-for i in ""teem/nrrd.h; do
-    # Have to have the "" for the SGI sh.
-    if test "$i" = ""; then
-      continue
-    fi
-    __sci_pound_includes="$__sci_pound_includes
-#include <$i>"
-done
-
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$__sci_pound_includes
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-
-eval LIB_DIR_TEEM='"$_sci_lib m"'
-
-if test "$_sci_lib m" = "$SCI_THIRDPARTY_LIB_DIR"; then
-  eval TEEM_LIB_DIR_FLAG=''
-else
-  eval TEEM_LIB_DIR_FLAG='"$_sci_lib_path"'
-fi
-
-#eval TEEM_LIB_FLAG='"$LIBS"'
-eval TEEM_LIB_FLAG='"$_sci_libs"'
-eval HAVE_TEEM="yes"
-
-if test "$_sci_includes" = "$INC_SCI_THIRDPARTY_H"; then
-  eval INC_TEEM_H=''
-else
-  eval INC_TEEM_H='"$_sci_includes"'
-fi
-
-eval HAVE_TEEM_H="yes"
-echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-eval LIB_DIR_TEEM=''
-eval TEEM_LIB_DIR_FLAG=''
-eval TEEM_LIB_FLAG=''
-eval HAVE_TEEM="no"
-eval INC_TEEM_H=''
-eval HAVE_TEEM_H="no"
-echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-if test "optional" != "optional"; then
-
-## SCI_MSG_ERROR
-if test -z "$debugging"; then
-  { echo "$as_me:$LINENO: WARNING:
-    Adding '--enable-verbosity' to configure line
-    _may_ give more information about what is breaking.
-    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
-    Digging through the config.log file is your best option
-    for determining what went wrong.  Search for the specific lib/file
-    that configured failed to find.  There should be a compile line
-    and source code near that check.  If you cut the source code into
-    a test.cc and then use the compile line to compile it, the true
-    error most likely will show up.
-  " >&5
-echo "$as_me: WARNING:
-    Adding '--enable-verbosity' to configure line
-    _may_ give more information about what is breaking.
-    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
-    Digging through the config.log file is your best option
-    for determining what went wrong.  Search for the specific lib/file
-    that configured failed to find.  There should be a compile line
-    and source code near that check.  If you cut the source code into
-    a test.cc and then use the compile line to compile it, the true
-    error most likely will show up.
-  " >&2;}
-fi
-
-{ { echo "$as_me:$LINENO: error: Test for required TEEM failed.
-    To see the failed compile information, look in config.log,
-    search for TEEM. Please install the relevant libraries
-     or specify the correct paths and try to configure again." >&5
-echo "$as_me: error: Test for required TEEM failed.
-    To see the failed compile information, look in config.log,
-    search for TEEM. Please install the relevant libraries
-     or specify the correct paths and try to configure again." >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-
-if test "optional" = "specific"; then
-#echo specific
-  # Make sure the exact includes were found
-  for i in ""teem/nrrd.h; do
-#echo looking for $_sci_inc/$i
-    if test ! -e $_sci_inc/$i; then
-     { { echo "$as_me:$LINENO: error: Specificly requested teem library and headers include file '$_sci_inc/$i' was not found" >&5
-echo "$as_me: error: Specificly requested teem library and headers include file '$_sci_inc/$i' was not found" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-  done
-  # Make sure the exact libraries were found
-  for i in ""teem; do
-#echo looking for $_sci_lib m/$i
-    if test ! -e $_sci_lib m/lib$i.so && test ! -e $_sci_lib m/lib$i.a; then
-     { { echo "$as_me:$LINENO: error: Specificly requested teem library and headers library file '$_sci_lib m/$i' was not found" >&5
-echo "$as_me: error: Specificly requested teem library and headers library file '$_sci_lib m/$i' was not found" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-  done
-fi
-
-
-#restore variables
-CFLAGS=$_sci_savecflags
-CXXFLAGS=$_sci_savecxxflags
-LDFLAGS=$_sci_saveldflags
-LIBS=$_sci_savelibs
-_sci_lib_path=''
-_sci_libs=''
-_sci_includes=''
-
-
-  else
-
-     # Determine if teem is using png.  Assume teem is either in the 3rd Party
-     # or where the user has specified (as we are going to use nm to look at its
-     # symbols and are not trying to link against it (at this point.))
-
-     result=`nm $_sci_lib/libteem.a | grep png`
-     if test -n "$result" && test "$HAVE_PNG" != "yes"; then
-        { echo "$as_me:$LINENO: WARNING: Teem was built with PNG support.  However the SCIRun configure" >&5
+  result=`nm $_sci_lib/libteem.a | grep png_write_info`
+  if test _sci_optional != "optional" && test -n "$result" && test "$HAVE_PNG" != "yes"; then
+     { echo "$as_me:$LINENO: WARNING: Teem was built with PNG support.  However the SCIRun configure" >&5
 echo "$as_me: WARNING: Teem was built with PNG support.  However the SCIRun configure" >&2;}
-        { echo "$as_me:$LINENO: WARNING: did not find PNG.  You need to determine where it is... as" >&5
+     { echo "$as_me:$LINENO: WARNING: did not find PNG.  You need to determine where it is... as" >&5
 echo "$as_me: WARNING: did not find PNG.  You need to determine where it is... as" >&2;}
-        { echo "$as_me:$LINENO: WARNING: Teem seems to have found it already.  You will most likely then need" >&5
+     { echo "$as_me:$LINENO: WARNING: Teem seems to have found it already.  You will most likely then need" >&5
 echo "$as_me: WARNING: Teem seems to have found it already.  You will most likely then need" >&2;}
-        { echo "$as_me:$LINENO: WARNING: to use --with-png=/dir/above/dir/having/libpng on your configure line." >&5
+     { echo "$as_me:$LINENO: WARNING: to use --with-png=/dir/above/dir/having/libpng on your configure line." >&5
 echo "$as_me: WARNING: to use --with-png=/dir/above/dir/having/libpng on your configure line." >&2;}
-        { { echo "$as_me:$LINENO: error: Please fix this problem and then configure again." >&5
+     { { echo "$as_me:$LINENO: error: Please fix this problem and then configure again." >&5
 echo "$as_me: error: Please fix this problem and then configure again." >&2;}
    { (exit 1); exit 1; }; }
-     fi
+  fi
 
 
 ##
@@ -28621,8 +28324,8 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking for teem library and headers (required)" >&5
-echo $ECHO_N "checking for teem library and headers (required)... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for teem library and headers ($_sci_optional)" >&5
+echo $ECHO_N "checking for teem library and headers ($_sci_optional)... $ECHO_C" >&6
 _sci_savelibs=$LIBS
 _sci_saveldflags=$LDFLAGS
 _sci_savecflags=$CFLAGS
@@ -28630,9 +28333,9 @@ _sci_savecxxflags=$CXXFLAGS
 
 _sci_includes=
 
-if test "required" != "optional" -a "required" != "required" -a "required" != "specific"; then
-     { { echo "$as_me:$LINENO: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had required.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
-echo "$as_me: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had required.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
+if test "$_sci_optional" != "optional" -a "$_sci_optional" != "required" -a "$_sci_optional" != "specific"; then
+     { { echo "$as_me:$LINENO: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had $_sci_optional.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&5
+echo "$as_me: error: Last parameter of SCI-TRY-LINK for teem library and headers must be: optional or required or specific.  (You had $_sci_optional.)  This is an internal SCIRun configure error and should be reported to scirun-develop@sci.utah.edu." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -28655,7 +28358,7 @@ echo "$as_me: error: Please do not specify /usr/include as the location for teem
   fi
 done
 
-if test "required" = "specific"; then
+if test "$_sci_optional" = "specific"; then
   # If 'specific' then only one lib is allowed:
   ### Determine if there is only one item in $_sci_lib (I don't know of a better way to do this.)
   __sci_pass=false
@@ -28808,7 +28511,7 @@ eval INC_TEEM_H=''
 eval HAVE_TEEM_H="no"
 echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
-if test "required" != "optional"; then
+if test "$_sci_optional" != "optional"; then
 
 ## SCI_MSG_ERROR
 if test -z "$debugging"; then
@@ -28851,7 +28554,7 @@ fi
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
-if test "required" = "specific"; then
+if test "$_sci_optional" = "specific"; then
 #echo specific
   # Make sure the exact includes were found
   for i in ""teem/nrrd.h; do
@@ -28884,7 +28587,6 @@ _sci_libs=''
 _sci_includes=''
 
 
-  fi
 
   if test "$HAVE_TEEM" = "yes"; then
      DEF_TEEM="#define HAVE_TEEM 1"
@@ -31485,7 +31187,7 @@ fi # end sci_required_qt
 
 ##  --  search for ruby  ----------------------------------------------------
 if test "$sci_required_ruby" = "yes"; then
-  _sci_optional=required;
+  _sci_optional=required
 
   if test "$with_ruby" = "yes"; then
     # --with-ruby has been specified without a parameter.
