Must check crypto before ssl because ssl needs the crypto lib

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18962,198 +18962,6 @@ fi
 
 
 
-##  --  search for ssl ---------------------------------
-
-if test "$sci_check_ssl" = "yes"; then
-  if test "$with_ssl"; then
-    _sci_lib="$with_ssl/lib"
-  else
-    _sci_lib="$sci_thirdparty_libs"
-  fi
-
-
-## arguments mean:
-## arg 1 : variable base name i.e. MATH
-## arg 2 : checking message
-## arg 3 : includes that arg 6 needs to compile
-## arg 4 : include paths -I
-## arg 5 : list of libs to link against -l
-## arg 6 : lib paths -L
-## arg 7 : extra link flags
-## arg 8 : body of code to compile. can be empty
-## arg 9 : optional or not-optional required argument
-##
-## after execution of macro, the following will be defined:
-##      Variable            Value
-##      --------            -----
-##      LIB_DIR_SSL        => lib path
-##      SSL_LIB_DIR_FLAG   => all the -L's
-##      SSL_LIB_FLAG       => all the -l's
-##      HAVE_SSL           => yes or no
-##      INC_SSL_H          => all the -I's
-##      HAVE_SSL_H         => yes or no
-
-
-
-echo "$as_me:$LINENO: checking for ssl library" >&5
-echo $ECHO_N "checking for ssl library... $ECHO_C" >&6
-_sci_savelibs=$LIBS
-_sci_saveldflags=$LDFLAGS
-_sci_savecflags=$CFLAGS
-_sci_savecxxflags=$CXXFLAGS
-
-_sci_includes=
-
-
-for i in ssl; do
-  if test -z "$_sci_libs"; then
-    _sci_libs=-l$i
-  else
-    _sci_libs="$_sci_libs -l$i"
-  fi
-done
-
-_sci_lib_path=
-
-for i in $_sci_lib; do
-  # make sure it exists
-  if test -d $i; then
-    if test -z "$_sci_lib_path"; then
-      _sci_lib_path="$LDRUN_PREFIX$i -L$i"
-    else
-      _sci_lib_path="$_sci_lib_path $LDRUN_PREFIX$i -L$i"
-    fi
-  fi
-done
-
-CFLAGS="$_sci_includes $CFLAGS"
-CXXFLAGS="$_sci_includes $CXXFLAGS"
-LDFLAGS="$_sci_lib_path $LDFLAGS"
-LIBS="$_sci_libs  $LIBS"
-
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-
-eval LIB_DIR_SSL='"$_sci_lib"'
-eval SSL_LIB_DIR_FLAG='"$_sci_lib_path"'
-eval SSL_LIB_FLAG='"$_sci_libs"'
-eval HAVE_SSL="yes"
-eval INC_SSL_H='"$_sci_includes"'
-eval HAVE_SSL_H="yes"
-echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-
-eval LIB_DIR_SSL=''
-eval SSL_LIB_DIR_FLAG=''
-eval SSL_LIB_FLAG=''
-eval HAVE_SSL="no"
-eval INC_SSL_H=''
-eval HAVE_SSL_H="no"
-echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-if test "optional" =  "not-optional"; then
-
-## SCI_MSG_ERROR
-if test -z "$debugging"; then
-  { echo "$as_me:$LINENO: WARNING:
-    Adding '--enable-verbosity' to configure line
-    _may_ give more information about what is breaking.
-    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
-    Digging through the config.log file is your best option
-    for determining what went wrong.  Search for the specific lib/file
-    that configured failed to find.  There should be a compile line
-    and source code near that check.  If you cut the source code into
-    a test.cc and then use the compile line to compile it, the true
-    error most likely will show up.
-  " >&5
-echo "$as_me: WARNING:
-    Adding '--enable-verbosity' to configure line
-    _may_ give more information about what is breaking.
-    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
-    Digging through the config.log file is your best option
-    for determining what went wrong.  Search for the specific lib/file
-    that configured failed to find.  There should be a compile line
-    and source code near that check.  If you cut the source code into
-    a test.cc and then use the compile line to compile it, the true
-    error most likely will show up.
-  " >&2;}
-fi
-
-{ { echo "$as_me:$LINENO: error: Test for required SSL failed.
-    To see the failed compile information, look in config.log,
-    search for SSL. Please install the relevant libraries
-     or specify the correct paths and try to configure again." >&5
-echo "$as_me: error: Test for required SSL failed.
-    To see the failed compile information, look in config.log,
-    search for SSL. Please install the relevant libraries
-     or specify the correct paths and try to configure again." >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-
-#restore variables
-CFLAGS=$_sci_savecflags
-CXXFLAGS=$_sci_savecxxflags
-LDFLAGS=$_sci_saveldflags
-LIBS=$_sci_savelibs
-_sci_lib_path=''
-_sci_libs=''
-_sci_includes=''
-
-
-
-  if test "$HAVE_SSL" = "yes"; then
-    DEF_SSL="#define HAVE_SSL 1"
-  fi
-
-  if test "$with_ssl" && test ! "$DEF_SSL"; then
-    echo
-    { { echo "$as_me:$LINENO: error: One or more of the SSL components is missing." >&5
-echo "$as_me: error: One or more of the SSL components is missing." >&2;}
-   { (exit 1); exit 1; }; }
-    echo
-  fi
-fi # end sci_check_ssl
-
-
-
-
-
 ##  --  search for crypto --------------------------------
 
 if test "$sci_check_crypto" = "yes"; then
@@ -19341,6 +19149,198 @@ echo "$as_me: error: One or more of the CRYPTO components is missing." >&2;}
     echo
   fi
 fi # end sci_check_crypto
+
+
+
+
+
+##  --  search for ssl ---------------------------------
+
+if test "$sci_check_ssl" = "yes"; then
+  if test "$with_ssl"; then
+    _sci_lib="$with_ssl/lib"
+  else
+    _sci_lib="$sci_thirdparty_libs"
+  fi
+
+
+## arguments mean:
+## arg 1 : variable base name i.e. MATH
+## arg 2 : checking message
+## arg 3 : includes that arg 6 needs to compile
+## arg 4 : include paths -I
+## arg 5 : list of libs to link against -l
+## arg 6 : lib paths -L
+## arg 7 : extra link flags
+## arg 8 : body of code to compile. can be empty
+## arg 9 : optional or not-optional required argument
+##
+## after execution of macro, the following will be defined:
+##      Variable            Value
+##      --------            -----
+##      LIB_DIR_SSL        => lib path
+##      SSL_LIB_DIR_FLAG   => all the -L's
+##      SSL_LIB_FLAG       => all the -l's
+##      HAVE_SSL           => yes or no
+##      INC_SSL_H          => all the -I's
+##      HAVE_SSL_H         => yes or no
+
+
+
+echo "$as_me:$LINENO: checking for ssl library" >&5
+echo $ECHO_N "checking for ssl library... $ECHO_C" >&6
+_sci_savelibs=$LIBS
+_sci_saveldflags=$LDFLAGS
+_sci_savecflags=$CFLAGS
+_sci_savecxxflags=$CXXFLAGS
+
+_sci_includes=
+
+
+for i in ssl crypto; do
+  if test -z "$_sci_libs"; then
+    _sci_libs=-l$i
+  else
+    _sci_libs="$_sci_libs -l$i"
+  fi
+done
+
+_sci_lib_path=
+
+for i in $_sci_lib; do
+  # make sure it exists
+  if test -d $i; then
+    if test -z "$_sci_lib_path"; then
+      _sci_lib_path="$LDRUN_PREFIX$i -L$i"
+    else
+      _sci_lib_path="$_sci_lib_path $LDRUN_PREFIX$i -L$i"
+    fi
+  fi
+done
+
+CFLAGS="$_sci_includes $CFLAGS"
+CXXFLAGS="$_sci_includes $CXXFLAGS"
+LDFLAGS="$_sci_lib_path $LDFLAGS"
+LIBS="$_sci_libs  $LIBS"
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+eval LIB_DIR_SSL='"$_sci_lib"'
+eval SSL_LIB_DIR_FLAG='"$_sci_lib_path"'
+eval SSL_LIB_FLAG='"$_sci_libs"'
+eval HAVE_SSL="yes"
+eval INC_SSL_H='"$_sci_includes"'
+eval HAVE_SSL_H="yes"
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+eval LIB_DIR_SSL=''
+eval SSL_LIB_DIR_FLAG=''
+eval SSL_LIB_FLAG=''
+eval HAVE_SSL="no"
+eval INC_SSL_H=''
+eval HAVE_SSL_H="no"
+echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+if test "optional" =  "not-optional"; then
+
+## SCI_MSG_ERROR
+if test -z "$debugging"; then
+  { echo "$as_me:$LINENO: WARNING:
+    Adding '--enable-verbosity' to configure line
+    _may_ give more information about what is breaking.
+    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
+    Digging through the config.log file is your best option
+    for determining what went wrong.  Search for the specific lib/file
+    that configured failed to find.  There should be a compile line
+    and source code near that check.  If you cut the source code into
+    a test.cc and then use the compile line to compile it, the true
+    error most likely will show up.
+  " >&5
+echo "$as_me: WARNING:
+    Adding '--enable-verbosity' to configure line
+    _may_ give more information about what is breaking.
+    IF YOU KNOW WHAT YOU ARE DOING, TRY THIS:
+    Digging through the config.log file is your best option
+    for determining what went wrong.  Search for the specific lib/file
+    that configured failed to find.  There should be a compile line
+    and source code near that check.  If you cut the source code into
+    a test.cc and then use the compile line to compile it, the true
+    error most likely will show up.
+  " >&2;}
+fi
+
+{ { echo "$as_me:$LINENO: error: Test for required SSL failed.
+    To see the failed compile information, look in config.log,
+    search for SSL. Please install the relevant libraries
+     or specify the correct paths and try to configure again." >&5
+echo "$as_me: error: Test for required SSL failed.
+    To see the failed compile information, look in config.log,
+    search for SSL. Please install the relevant libraries
+     or specify the correct paths and try to configure again." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+#restore variables
+CFLAGS=$_sci_savecflags
+CXXFLAGS=$_sci_savecxxflags
+LDFLAGS=$_sci_saveldflags
+LIBS=$_sci_savelibs
+_sci_lib_path=''
+_sci_libs=''
+_sci_includes=''
+
+
+
+  if test "$HAVE_SSL" = "yes"; then
+    DEF_SSL="#define HAVE_SSL 1"
+  fi
+
+  if test "$with_ssl" && test ! "$DEF_SSL"; then
+    echo
+    { { echo "$as_me:$LINENO: error: One or more of the SSL components is missing." >&5
+echo "$as_me: error: One or more of the SSL components is missing." >&2;}
+   { (exit 1); exit 1; }; }
+    echo
+  fi
+fi # end sci_check_ssl
 
 
 
@@ -21637,12 +21637,12 @@ s,@DEF_HDF5@,$DEF_HDF5,;t t
 s,@PERFEX_LIB_FLAG@,$PERFEX_LIB_FLAG,;t t
 s,@PERFEX_LIB_DIR_FLAG@,$PERFEX_LIB_DIR_FLAG,;t t
 s,@DEF_PERFEX@,$DEF_PERFEX,;t t
-s,@SSL_LIB_FLAG@,$SSL_LIB_FLAG,;t t
-s,@SSL_LIB_DIR_FLAG@,$SSL_LIB_DIR_FLAG,;t t
-s,@DEF_SSL@,$DEF_SSL,;t t
 s,@CRYPTO_LIB_FLAG@,$CRYPTO_LIB_FLAG,;t t
 s,@CRYPTO_LIB_DIR_FLAG@,$CRYPTO_LIB_DIR_FLAG,;t t
 s,@DEF_CRYPTO@,$DEF_CRYPTO,;t t
+s,@SSL_LIB_FLAG@,$SSL_LIB_FLAG,;t t
+s,@SSL_LIB_DIR_FLAG@,$SSL_LIB_DIR_FLAG,;t t
+s,@DEF_SSL@,$DEF_SSL,;t t
 s,@GLOBUS_LIB_FLAG@,$GLOBUS_LIB_FLAG,;t t
 s,@GLOBUS_LIB_DIR_FLAG@,$GLOBUS_LIB_DIR_FLAG,;t t
 s,@INC_GLOBUS_H@,$INC_GLOBUS_H,;t t
