sync configure with in, using v2.13 autoconf on rapture, which seems to fix our platform issues...

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3195,7 +3195,7 @@ echo "configure:3151: checking for $MAKE version 3.78.1" >&5
     fi
   
 
-for ac_prog in gawk mawk nawk awk
+for ac_prog in mawk gawk nawk awk
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -3483,49 +3483,49 @@ cross_compiling=$ac_cv_prog_cxx_cross
 
 
 ##  ----------  See if this is a 64 bit machine --------------------------
-echo $ac_n "checking size of void *""... $ac_c" 1>&6
-echo "configure:3488: checking size of void *" >&5
-if eval "test \"`echo '$''{'ac_cv_sizeof_void_p'+set}'`\" = set"; then
+echo $ac_n "checking size of void*""... $ac_c" 1>&6
+echo "configure:3488: checking size of void*" >&5
+if eval "test \"`echo '$''{'ac_cv_sizeof_voidp'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   if test "$cross_compiling" = yes; then
-  ac_cv_sizeof_void_p=0
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
 #line 3496 "configure"
 #include "confdefs.h"
 #ifdef __cplusplus
-extern "C" void exit(int) throw ();
+extern "C" void exit(int);
 #endif
 #include <stdio.h>
 main()
 {
   FILE *f=fopen("conftestval", "w");
   if (!f) exit(1);
-  fprintf(f, "%d\n", sizeof(void *));
+  fprintf(f, "%d\n", sizeof(void*));
   exit(0);
 }
 EOF
 if { (eval echo configure:3510: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
-  ac_cv_sizeof_void_p=`cat conftestval`
+  ac_cv_sizeof_voidp=`cat conftestval`
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -fr conftest*
-  ac_cv_sizeof_void_p=0
+  ac_cv_sizeof_voidp=0
 fi
 rm -fr conftest*
 fi
 
 fi
-echo "$ac_t""$ac_cv_sizeof_void_p" 1>&6
+echo "$ac_t""$ac_cv_sizeof_voidp" 1>&6
 cat >> confdefs.h <<EOF
-#define SIZEOF_VOID_P $ac_cv_sizeof_void_p
+#define SIZEOF_VOIDP $ac_cv_sizeof_voidp
 EOF
 
 
-case $ac_cv_sizeof_void_p in
+case $ac_cv_sizeof_voidp in
  8)
   NBITS=64
   ;;
@@ -5239,7 +5239,7 @@ for i in /usr/lib /usr/X11R6/lib; do
   if test ! -d "$i"; then 
     continue
   fi
-  
+
   
     ##  SCI_CHECK_LIB
     _SCI_FOUND_='echo -n ""'
@@ -8569,7 +8569,7 @@ for i in $with_vdt $thirdparty $SCI_LAB_TP_DEFAULT; do
   # Testing the link also need by vdt to link is:
   VDT_LIB_PATH="-L$i/src/vdt/G3D/lib/$ad -L$i/src/vdt/Ckit/lib/$ad -L$i/src/vdt/LOBS/lib/$ad -L$i/src/vdt/PiRaT/lib/$ad -L$i/src/vdt/Meschach/$ad -L$i/src/vdt/lp_solve_2.2/$ad -L$i/src/vdt/Elixir/lib/$ad -L$i/src/vdt/VDT/lib/$ad $X_LIBRARY"
 
-  VDT_NEEDED_LIBRARIES='-lesi -lelixir -llpk -lpirat -llobs3d -llobs2d -llobs1d -lg3d -lckit -lmeschach -lX11 -lXext -lXaw -lXt'
+  VDT_NEEDED_LIBRARIES='-lesi -lelixir -llpk -lpirat -llobs3d -llobs2d -llobs1d -lg3d -lckit -lmeschach -lX11 -lXext -lXaw -lXt -lXmu -lm'
 
   
     ##  SCI_CHECK_LIB
