Fix uni-petsc check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32453,15 +32453,33 @@ esac
 # Again required for the following uni-petsc checks, that attempt to support
 # the MatrixSolver module.
 
-if test "$with_mpiuni"; then
-  _sci_lib="$with_mpiuni/lib"
-  _sci_inc="$with_mpiuni/include"
+_sci_lib=
+_sci_inc=
+
+if test "$with_mpiuni" = "yes"; then
+  echo
+  { { echo "$as_me:$LINENO: error: You must specify a directory with the --with-mpiuni=dir." >&5
+echo "$as_me: error: You must specify a directory with the --with-mpiuni=dir." >&2;}
+   { (exit 1); exit 1; }; }
+  echo
 elif test "$with_unipetsc"; then
   _sci_lib="$with_unipetsc/lib/$PETSC_SUB/$PETSC_ARCH"
-  _sci_inc="$with_unipetsc/src/sys/src/mpiuni $with_unipetsc/bmake/$PETSC_ARCH"
-else
-  _sci_lib="$sci_thirdparty_libs"
-  _sci_inc="$sci_thirdparty_includes"
+  if test ! -d "$_sci_lib" || test ! -d "$with_unipetsc/include/mpiuni" ||
+     test ! -d "$with_unipetsc/bmake/$PETSC_ARCH" ; then
+    echo
+    { echo "$as_me:$LINENO: WARNING: Specified unipetsc directory is invalid.  One of the following dirs does not exist:" >&5
+echo "$as_me: WARNING: Specified unipetsc directory is invalid.  One of the following dirs does not exist:" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $_sci_lib" >&5
+echo "$as_me: WARNING: $_sci_lib" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $with_unipetsc/include/mpiuni" >&5
+echo "$as_me: WARNING: $with_unipetsc/include/mpiuni" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $with_unipetsc/bmake/$PETSC_ARCH" >&5
+echo "$as_me: WARNING: $with_unipetsc/bmake/$PETSC_ARCH" >&2;}
+    { { echo "$as_me:$LINENO: error: Please fix this problem and reconfigure." >&5
+echo "$as_me: error: Please fix this problem and reconfigure." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  _sci_inc="$with_unipetsc/include/mpiuni $with_unipetsc/bmake/$PETSC_ARCH"
 fi
 
 
@@ -33420,7 +33438,7 @@ fi
 
 
 
-#  --  search for mpi-uni  --------------------------------------------
+#  --  search for PETSc  --------------------------------------------
 if test -z "$PETSC_ARCH"; then
    { { echo "$as_me:$LINENO: error: PETSC_ARCH environment var is not set.  Please set." >&5
 echo "$as_me: error: PETSC_ARCH environment var is not set.  Please set." >&2;}
@@ -33429,13 +33447,12 @@ fi
 
 # Make sure we have either mpi or mpi-uni, blas, and lapack
 # It seems that under AIX and OSF, the libs that cover blas also cover lapack
-if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") &&
-    test "$HAVE_BLAS" = "yes" &&
+if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") && test "$HAVE_BLAS" = "yes" &&
    (test "$PETSC_ARCH" = "rs6000_sp" || test "$PETSC_ARCH" = "dec" ||
     test "$HAVE_LAPACK" = "yes"); then
 
-  _sci_lib_dir=""
-  _sci_inc=""
+  _sci_lib_dir=
+  _sci_inc=
 
   if test "$with_petsc"; then
     _sci_lib_dir="$with_petsc/lib/$PETSC_SUB/$PETSC_ARCH"
@@ -33929,13 +33946,17 @@ echo "$as_me: error: One or more of the PETSc components is missing." >&2;}
   fi
 
   #  --  search for uni-petsc  --------------------------------------------
-  _sci_lib=""
-  _sci_inc=""
 
-  if test "$with_unipetsc"; then
-    _sci_lib="$with_unipetsc/lib/$PETSC_SUB/$PETSC_ARCH"
-    _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
-  fi
+  if test "$HAVE_PETSC" != "yes" ; then
+
+    # Only check for uni petsc if petsc not found.
+    _sci_lib=""
+    _sci_inc=""
+
+    if test "$with_unipetsc"; then
+      _sci_lib="$with_unipetsc/lib/$PETSC_SUB/$PETSC_ARCH"
+      _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
+    fi
 
 
 ##
@@ -33974,7 +33995,7 @@ echo "$as_me: error: One or more of the PETSc components is missing." >&2;}
 ## arg 2 : petsc-uni libraries and headers
 ## arg 3 : petsc.h
 ## arg 4 : $_sci_inc /usr/include/petsc
-## arg 5 : petsc petscvec petscmat petscdm petsccontrib petscsnes petscts petscsles petscfortran
+## arg 5 : petsc petscvec petscmat petscdm petscsnes petscts petscfortran
 ## arg 6 : $_sci_lib
 ## arg 7 : $LAPACK_LIB_DIR_FLAG $LAPACK_LIB_FLAG $BLAS_LIB_DIR_FLAG $BLAS_LIB_FLAG $M_LIB_FLAG $INC_MPI_UNI_H $MPI_UNI_LIB_DIR_FLAG $MPI_UNI_LIB_FLAG $F_LIB_FLAG
 ## arg 8 : <Can't expand it here as it may be multiple lines and cause sh problems.>
@@ -34055,10 +34076,10 @@ done
 
 ### Take care of arg 5 (the list of libs)
 
-if test -n "petsc petscvec petscmat petscdm petsccontrib petscsnes petscts petscsles petscfortran"; then
+if test -n "petsc petscvec petscmat petscdm petscsnes petscts petscfortran"; then
 
    found_framework=no
-   for lib in "" petsc petscvec petscmat petscdm petsccontrib petscsnes petscts petscsles petscfortran; do
+   for lib in "" petsc petscvec petscmat petscdm petscsnes petscts petscfortran; do
 
       if test -z "$lib"; then
          # SGI sh needs the "" in the for statement... so skip it here.
@@ -34374,7 +34395,7 @@ echo "$as_me: error: Specificly requested PETSC_UNI include file '$_sci_inc /usr
     fi
   done
   # Make sure the exact libraries were found
-  for i in "" petsc petscvec petscmat petscdm petsccontrib petscsnes petscts petscsles petscfortran; do
+  for i in "" petsc petscvec petscmat petscdm petscsnes petscts petscfortran; do
 #echo looking for $_sci_lib/$i
     if test -n "$i" && test ! -e $_sci_lib/lib$i.so && test ! -e $_sci_lib/lib$i.a; then
      { { echo "$as_me:$LINENO: error: Specificly requested PETSC_UNI library file '$_sci_lib/$i' was not found" >&5
@@ -34396,16 +34417,17 @@ _sci_includes=''
 
 
 
-  if test "$HAVE_PETSC_UNI" = "yes" ; then
-    DEF_PETSC_UNI="#define PETSC_UNI 1"
-  fi
+    if test "$HAVE_PETSC_UNI" = "yes" ; then
+      DEF_PETSC_UNI="#define PETSC_UNI 1"
+    fi
 
-  if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
-    echo
-    { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
+    if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
+      echo
+      { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
 echo "$as_me: error: One or more of the UNI-PETSC components is missing." >&2;}
    { (exit 1); exit 1; }; }
-    echo
+      echo
+    fi
   fi
 
 else
