Add Ptolemy package to SCIRun build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -340,7 +340,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CXX CPPFLAGS CXXFLAGS F77 FFLAGS CPP CXXCPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os DEF_CHROMIUM DEF_NO_DYNAMIC_CAST MATLAB_ENG DEF_COLLAB_VIS HAVE_COLLAB_VIS IS_OSX ac_ct_CC EXEEXT OBJEXT ac_ct_CXX ac_ct_F77 SO_OR_ARCHIVE_EXTENSION NOPRINTDIR PACKAGE_DIRS LOAD_PACKAGE EXENAME LARGESOS TIME_IMPL DEF_MALLOC ASSERTION_LEVEL THROW_LEVEL OGL_ERR_MACRO AS LD NEED_OSX_HACK DEF_NEED_OSX_HACK CC_DEPEND_MODE CC_DEPEND_REGEN CC_DEPEND_EXT F77_DEPEND_MODE F77_DEPEND_REGEN F77_DEPEND_EXT GMAKE MAKE AWK YACC LEX LEXLIB LEX_OUTPUT_ROOT LEX_LIB_FLAG ETAGS PERL FORTRAN_UNDERSCORE G77 SOFLAGS ASFLAGS LDRUN_PREFIX extra_cflags MAKE_PARALLELISM NEED_SONAME REPOSITORY_FLAGS TEMPLATE_TAG TEMPLATE_BOX EGREP NBITS SCI_THIRDPARTY_DIR INC_SCI_THIRDPARTY_H SCI_THIRDPARTY_LIB_DIR SCI_THIRDPARTY_LIB_DIR_FLAG M_LIB_FLAG M_LIB_DIR_FLAG X_LIB_FLAG X_LIB_DIR_FLAG THREAD_IMPL THREAD_LIB_FLAG DEF_THREAD SEMAPHORE_LIB_FLAG GL_LIB_FLAG GL_LIB_DIR_FLAG INC_GL_H DEF_OGL_EXT_HDRS COMPILE_AVR DEF_HAVE_AVR DL_LIB_FLAG DL_LIB_DIR_FLAG DEF_STAT64 DEF_IEEEFP DEF_HASHMAP LIB_DIR_TCL TCL_LIB_FLAG TCL_LIB_DIR_FLAG INC_TCL_H TK_LIB_FLAG TK_LIB_DIR_FLAG INC_TK_H LIB_DIR_ITCL ITCL_LIB_FLAG ITCL_LIB_DIR_FLAG INC_ITCL_H ITK_LIB_FLAG ITK_LIB_DIR_FLAG INC_ITK_H BLT_LIB_FLAG BLT_LIB_DIR_FLAG INC_BLT_H TCL_PREFIX TCL_VERSION TK_VERSION ITCL_WIDGETS XERCES_C_LIB_FLAG XERCES_C_LIB_DIR_FLAG INC_XERCESC_H SSTREAM_COMPAT EXC_LIB_FLAG EXC_LIB_DIR_FLAG DEF_EXC Z_LIB_FLAG Z_LIB_DIR_FLAG INC_Z_H DEF_Z JPEG_LIB_FLAG JPEG_LIB_DIR_FLAG TIFF_LIB_FLAG TIFF_LIB_DIR_FLAG PNG_LIB_FLAG PNG_LIB_DIR_FLAG INC_PNG_H DEF_PNG MPEGE_LIB_FLAG MPEGE_LIB_DIR_FLAG DEF_MPEG MAGICK_LIB_FLAG MAGICK_LIB_DIR_FLAG INC_MAGICK_H DEF_MAGICK SCISOCK_LIB_FLAG SCISOCK_LIB_DIR_FLAG INC_SCISOCK_H UNP_LIB_FLAG UNP_LIB_DIR_FLAG INC_UNP_H F_LIB_FLAG HAVE_CBLAS DEF_CBLAS HAVE_BLAS INC_BLAS_H BLAS_LIB_FLAG BLAS_LIB_DIR_FLAG DEF_BLAS HAVE_LAPACK DEF_LAPACK LAPACK_LIB_FLAG LAPACK_LIB_DIR_FLAG HAVE_LAPACKMP LAPACKMP_LIB_FLAG LAPACKMP_LIB_DIR_FLAG HAVE_MPI DEF_MPI INC_MPI_H MPI_LIB_FLAG MPI_LIB_DIR_FLAG DEF_MPI_UNI INC_MPI_UNI_H MPI_UNI_LIB_FLAG MPI_UNI_LIB_DIR_FLAG HAVE_PETSC PETSC_LIB_FLAG PETSC_LIB_DIR_FLAG DEF_PETSC INC_PETSC_H HAVE_PETSC_UNI PETSC_UNI_LIB_FLAG PETSC_UNI_LIB_DIR_FLAG DEF_PETSC_UNI INC_PETSC_UNI_H HAVE_INSIGHT DEF_INSIGHT INC_INSIGHT_H INSIGHT_LIB_FLAG INSIGHT_LIB_DIR_FLAG XALAN_PATH TAU_MAKEFILE BABEL_BIN HAVE_BABEL DEF_BABEL INC_SIDL_H SIDL_LIB_FLAG SIDL_LIB_DIR_FLAG NETSOLVE_LIB_FLAG NETSOLVE_LIB_DIR_FLAG INC_GLUT_H GLUT_LIB_FLAG GLUT_LIB_DIR_FLAG INC_GLUI_H GLUI_LIB_FLAG GLUI_LIB_DIR_FLAG DEF_OOGL INC_OOGL_H OOGL_LIB_FLAG OOGL_LIB_DIR_FLAG DEF_GLEW INC_GLEW_H GLEW_LIB_FLAG GLEW_LIB_DIR_FLAG FREETYPE_LIB_FLAG FREETYPE_LIB_DIR_FLAG DEF_FREETYPE INC_FREETYPE_H FTGL_LIB_FLAG FTGL_LIB_DIR_FLAG DEF_FTGL INC_FTGL_H DEF_AUDIO HAVE_AUDIO AUDIO_LIB_FLAG AUDIO_LIB_DIR_FLAG HAVE_TEEM DEF_TEEM INC_TEEM_H TEEM_LIB_FLAG TEEM_LIB_DIR_FLAG DEF_MDSPLUS INC_MDSPLUS_H MDSPLUS_LIB_FLAG MDSPLUS_LIB_DIR_FLAG DEF_HDF5 INC_HDF5_H HDF5_LIB_FLAG HDF5_LIB_DIR_FLAG DEF_PERFEX PERFEX_LIB_FLAG PERFEX_LIB_DIR_FLAG DEF_CRYPTO CRYPTO_LIB_FLAG CRYPTO_LIB_DIR_FLAG DEF_SSL SSL_LIB_FLAG SSL_LIB_DIR_FLAG HAVE_GLOBUS DEF_GLOBUS INC_GLOBUS_H GLOBUS_LIB_FLAG GLOBUS_LIB_DIR_FLAG QT_MOC_BIN HAVE_QT DEF_QT INC_QT_MT_H QT_MT_LIB_FLAG QT_MT_LIB_DIR_FLAG HAVE_RUBY DEF_RUBY INC_RUBY_H RUBY_LIB_FLAG RUBY_LIB_DIR_FLAG HAVE_VTK DEF_VTK INC_VTK_H VTK_LIB_FLAG VTK_LIB_DIR_FLAG DEF_VDT INC_VDT_H VDT_LIB_FLAG VDT_LIB_DIR_FLAG HAVE_HYPRE DEF_HYPRE INC_HYPRE_H HYPRE_LIB_FLAG HYPRE_LIB_DIR_FLAG HAVE_UUID UUID_LIB_FLAG BUILD_SCIRUN2 scirun_obj_dir scirun_src_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CXX CPPFLAGS CXXFLAGS F77 FFLAGS CPP CXXCPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os DEF_CHROMIUM DEF_NO_DYNAMIC_CAST MATLAB_ENG DEF_COLLAB_VIS HAVE_COLLAB_VIS IS_OSX ac_ct_CC EXEEXT OBJEXT ac_ct_CXX ac_ct_F77 SO_OR_ARCHIVE_EXTENSION NOPRINTDIR PACKAGE_DIRS LOAD_PACKAGE EXENAME LARGESOS TIME_IMPL DEF_MALLOC ASSERTION_LEVEL THROW_LEVEL OGL_ERR_MACRO AS LD NEED_OSX_HACK DEF_NEED_OSX_HACK CC_DEPEND_MODE CC_DEPEND_REGEN CC_DEPEND_EXT F77_DEPEND_MODE F77_DEPEND_REGEN F77_DEPEND_EXT GMAKE MAKE AWK YACC LEX LEXLIB LEX_OUTPUT_ROOT LEX_LIB_FLAG ETAGS PERL FORTRAN_UNDERSCORE G77 SOFLAGS ASFLAGS LDRUN_PREFIX extra_cflags MAKE_PARALLELISM NEED_SONAME REPOSITORY_FLAGS TEMPLATE_TAG TEMPLATE_BOX EGREP NBITS SCI_THIRDPARTY_DIR INC_SCI_THIRDPARTY_H SCI_THIRDPARTY_LIB_DIR SCI_THIRDPARTY_LIB_DIR_FLAG M_LIB_FLAG M_LIB_DIR_FLAG X_LIB_FLAG X_LIB_DIR_FLAG THREAD_IMPL THREAD_LIB_FLAG DEF_THREAD SEMAPHORE_LIB_FLAG GL_LIB_FLAG GL_LIB_DIR_FLAG INC_GL_H DEF_OGL_EXT_HDRS COMPILE_AVR DEF_HAVE_AVR DL_LIB_FLAG DL_LIB_DIR_FLAG DEF_STAT64 DEF_IEEEFP DEF_HASHMAP LIB_DIR_TCL TCL_LIB_FLAG TCL_LIB_DIR_FLAG INC_TCL_H TK_LIB_FLAG TK_LIB_DIR_FLAG INC_TK_H LIB_DIR_ITCL ITCL_LIB_FLAG ITCL_LIB_DIR_FLAG INC_ITCL_H ITK_LIB_FLAG ITK_LIB_DIR_FLAG INC_ITK_H BLT_LIB_FLAG BLT_LIB_DIR_FLAG INC_BLT_H TCL_PREFIX TCL_VERSION TK_VERSION ITCL_WIDGETS XERCES_C_LIB_FLAG XERCES_C_LIB_DIR_FLAG INC_XERCESC_H SSTREAM_COMPAT EXC_LIB_FLAG EXC_LIB_DIR_FLAG DEF_EXC Z_LIB_FLAG Z_LIB_DIR_FLAG INC_Z_H DEF_Z JPEG_LIB_FLAG JPEG_LIB_DIR_FLAG TIFF_LIB_FLAG TIFF_LIB_DIR_FLAG PNG_LIB_FLAG PNG_LIB_DIR_FLAG INC_PNG_H DEF_PNG MPEGE_LIB_FLAG MPEGE_LIB_DIR_FLAG DEF_MPEG MAGICK_LIB_FLAG MAGICK_LIB_DIR_FLAG INC_MAGICK_H DEF_MAGICK SCISOCK_LIB_FLAG SCISOCK_LIB_DIR_FLAG INC_SCISOCK_H UNP_LIB_FLAG UNP_LIB_DIR_FLAG INC_UNP_H F_LIB_FLAG HAVE_CBLAS DEF_CBLAS HAVE_BLAS INC_BLAS_H BLAS_LIB_FLAG BLAS_LIB_DIR_FLAG DEF_BLAS HAVE_LAPACK DEF_LAPACK LAPACK_LIB_FLAG LAPACK_LIB_DIR_FLAG HAVE_LAPACKMP LAPACKMP_LIB_FLAG LAPACKMP_LIB_DIR_FLAG HAVE_MPI DEF_MPI INC_MPI_H MPI_LIB_FLAG MPI_LIB_DIR_FLAG DEF_MPI_UNI INC_MPI_UNI_H MPI_UNI_LIB_FLAG MPI_UNI_LIB_DIR_FLAG HAVE_PETSC PETSC_LIB_FLAG PETSC_LIB_DIR_FLAG DEF_PETSC INC_PETSC_H HAVE_PETSC_UNI PETSC_UNI_LIB_FLAG PETSC_UNI_LIB_DIR_FLAG DEF_PETSC_UNI INC_PETSC_UNI_H HAVE_INSIGHT DEF_INSIGHT INC_INSIGHT_H INSIGHT_LIB_FLAG INSIGHT_LIB_DIR_FLAG HAVE_PTOLEMY JAVA_PATH PTOLEMY_PATH PTOLEMY_CLASSPATH XALAN_PATH TAU_MAKEFILE BABEL_BIN HAVE_BABEL DEF_BABEL INC_SIDL_H SIDL_LIB_FLAG SIDL_LIB_DIR_FLAG NETSOLVE_LIB_FLAG NETSOLVE_LIB_DIR_FLAG INC_GLUT_H GLUT_LIB_FLAG GLUT_LIB_DIR_FLAG INC_GLUI_H GLUI_LIB_FLAG GLUI_LIB_DIR_FLAG DEF_OOGL INC_OOGL_H OOGL_LIB_FLAG OOGL_LIB_DIR_FLAG DEF_GLEW INC_GLEW_H GLEW_LIB_FLAG GLEW_LIB_DIR_FLAG FREETYPE_LIB_FLAG FREETYPE_LIB_DIR_FLAG DEF_FREETYPE INC_FREETYPE_H FTGL_LIB_FLAG FTGL_LIB_DIR_FLAG DEF_FTGL INC_FTGL_H DEF_AUDIO HAVE_AUDIO AUDIO_LIB_FLAG AUDIO_LIB_DIR_FLAG HAVE_TEEM DEF_TEEM INC_TEEM_H TEEM_LIB_FLAG TEEM_LIB_DIR_FLAG DEF_MDSPLUS INC_MDSPLUS_H MDSPLUS_LIB_FLAG MDSPLUS_LIB_DIR_FLAG DEF_HDF5 INC_HDF5_H HDF5_LIB_FLAG HDF5_LIB_DIR_FLAG DEF_PERFEX PERFEX_LIB_FLAG PERFEX_LIB_DIR_FLAG DEF_CRYPTO CRYPTO_LIB_FLAG CRYPTO_LIB_DIR_FLAG DEF_SSL SSL_LIB_FLAG SSL_LIB_DIR_FLAG HAVE_GLOBUS DEF_GLOBUS INC_GLOBUS_H GLOBUS_LIB_FLAG GLOBUS_LIB_DIR_FLAG QT_MOC_BIN HAVE_QT DEF_QT INC_QT_MT_H QT_MT_LIB_FLAG QT_MT_LIB_DIR_FLAG HAVE_RUBY DEF_RUBY INC_RUBY_H RUBY_LIB_FLAG RUBY_LIB_DIR_FLAG HAVE_VTK DEF_VTK INC_VTK_H VTK_LIB_FLAG VTK_LIB_DIR_FLAG DEF_VDT INC_VDT_H VDT_LIB_FLAG VDT_LIB_DIR_FLAG HAVE_HYPRE DEF_HYPRE INC_HYPRE_H HYPRE_LIB_FLAG HYPRE_LIB_DIR_FLAG HAVE_UUID UUID_LIB_FLAG BUILD_SCIRUN2 scirun_obj_dir scirun_src_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -938,6 +938,10 @@ Optional Packages:
 --with-blas=DIR         Use the blas installation in DIR
 --with-lapack=DIR       Use the lapack installation in DIR
 --with-fortran=DIR      Use the fortran (eg: g2c) installation in DIR/lib
+--with-ptolemyII=DIR    Use the Ptolemy II (eg: ptII4.0.1) installation in
+                          DIR (Ptolemy package only)
+--with-java=DIR         Use the Java distribution in DIR (Ptolemy package
+                          only)
 --with-mpi=DIR          Use the mpi installation in DIR
 --with-mpiuni=DIR       Use the mpiuni installation in DIR
 --with-hypre=DIR        Use the hypre installation in DIR
@@ -1657,6 +1661,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
   sci_required_gzopen=no
   sci_required_hypre=no
   sci_required_insight=no
+  sci_required_java=no
   sci_required_jpeg=no
   sci_required_lapack=no
   sci_required_mdsplus=no
@@ -1665,6 +1670,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
   sci_required_oogl=no
   sci_required_perl=no
   sci_required_petsc=no
+  sci_required_ptolemyII=no
   sci_required_qt=no
   sci_required_ruby=no
   sci_required_ssl=no
@@ -1792,6 +1798,42 @@ fi;
   if test -n "$fortran" -a ! -e "$fortran"; then
     { { echo "$as_me:$LINENO: error: The file or directory parameter ($fortran) specified for --with-fortran does not exist!  Please verify that the path and file are correct." >&5
 echo "$as_me: error: The file or directory parameter ($fortran) specified for --with-fortran does not exist!  Please verify that the path and file are correct." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+# Check whether --with-ptolemyII or --without-ptolemyII was given.
+if test "${with_ptolemyII+set}" = set; then
+  withval="$with_ptolemyII"
+  with_ptolemyII="$withval"
+   sci_required_ptolemyII=yes
+else
+  with_ptolemyII=""
+fi;
+  sci_arg_with_list="$sci_arg_with_list --with-ptolemyII --without-ptolemyII"
+  if test -n "$ptolemyII" -a ! -e "$ptolemyII"; then
+    { { echo "$as_me:$LINENO: error: The file or directory parameter ($ptolemyII) specified for --with-ptolemyII does not exist!  Please verify that the path and file are correct." >&5
+echo "$as_me: error: The file or directory parameter ($ptolemyII) specified for --with-ptolemyII does not exist!  Please verify that the path and file are correct." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+# Check whether --with-java or --without-java was given.
+if test "${with_java+set}" = set; then
+  withval="$with_java"
+  with_java="$withval"
+   sci_required_java=yes
+else
+  with_java=""
+fi;
+  sci_arg_with_list="$sci_arg_with_list --with-java --without-java"
+  if test -n "$java" -a ! -e "$java"; then
+    { { echo "$as_me:$LINENO: error: The file or directory parameter ($java) specified for --with-java does not exist!  Please verify that the path and file are correct." >&5
+echo "$as_me: error: The file or directory parameter ($java) specified for --with-java does not exist!  Please verify that the path and file are correct." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -2612,6 +2654,10 @@ case SCIRun2 in
         ;;
     esac
   ;;
+  Ptolemy)
+    sci_required_ptolemyII=yes
+    sci_required_java=yes
+  ;;
   *)
     { echo "$as_me:$LINENO: WARNING: In aclocal.m4: No known dependencies for Package SCIRun2" >&5
 echo "$as_me: WARNING: In aclocal.m4: No known dependencies for Package SCIRun2" >&2;}
@@ -2787,6 +2833,10 @@ case $i in
         ;;
     esac
   ;;
+  Ptolemy)
+    sci_required_ptolemyII=yes
+    sci_required_java=yes
+  ;;
   *)
     { echo "$as_me:$LINENO: WARNING: In aclocal.m4: No known dependencies for Package $i" >&5
 echo "$as_me: WARNING: In aclocal.m4: No known dependencies for Package $i" >&2;}
@@ -2868,6 +2918,10 @@ case Teem in
      *)
         ;;
     esac
+  ;;
+  Ptolemy)
+    sci_required_ptolemyII=yes
+    sci_required_java=yes
   ;;
   *)
     { echo "$as_me:$LINENO: WARNING: In aclocal.m4: No known dependencies for Package Teem" >&5
@@ -2951,6 +3005,10 @@ case DataIO in
         ;;
     esac
   ;;
+  Ptolemy)
+    sci_required_ptolemyII=yes
+    sci_required_java=yes
+  ;;
   *)
     { echo "$as_me:$LINENO: WARNING: In aclocal.m4: No known dependencies for Package DataIO" >&5
 echo "$as_me: WARNING: In aclocal.m4: No known dependencies for Package DataIO" >&2;}
@@ -2960,6 +3018,92 @@ esac
 
       package="$package DataIO"
   fi
+fi
+
+if test "$pkg_Ptolemy" = "yes"; then
+  # check versions?
+  # check --with-ptolemyII
+  if test -z "$with_ptolemyII"; then
+    { echo "$as_me:$LINENO: WARNING: Ptolemy II is required by the Ptolemy package." >&5
+echo "$as_me: WARNING: Ptolemy II is required by the Ptolemy package." >&2;}
+    { { echo "$as_me:$LINENO: error: Use the --with-ptolemyII=DIR option to set the installation directory." >&5
+echo "$as_me: error: Use the --with-ptolemyII=DIR option to set the installation directory." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+eval pkg_Ptolemy=yes
+
+case Ptolemy in
+  BioPSE)
+  ;;
+  Teem)
+    sci_required_teem=yes
+  ;;
+  VDT)
+    sci_required_vdt=yes
+  ;;
+  MatlabInterface)
+  ;;
+  Uintah)
+    sci_required_fortran=yes
+    sci_required_mpi=yes
+    sci_required_blas=yes
+    sci_required_lapack=yes
+    sci_required_perl=yes
+    sci_required_tools=yes
+  ;;
+  Fusion)
+  ;;
+  PCS)
+  ;;
+  DataIO)
+    sci_required_mdsplus=yes
+    sci_required_hdf5=yes
+  ;;
+  SCIRun2)
+    sci_required_babel=yes
+    sci_required_uuid=yes
+    sci_required_ruby=yes
+  ;;
+  Remote)
+    sci_required_jpeg=yes
+    sci_required_tiff=yes
+  ;;
+  NetSolve)
+    sci_required_netsolve=yes
+  ;;
+  rtrt)
+    sci_required_glut=yes
+    sci_required_glui=yes
+    sci_required_oogl=yes
+    sci_required_audio=yes
+    sci_required_teem=yes
+  ;;
+  Insight)
+    sci_required_insight=yes
+    sci_required_xalan=yes
+  ;;
+  Volume)
+    case $host in
+     *-darwin*)
+	sci_required_glew=yes
+	;;
+     *)
+        ;;
+    esac
+  ;;
+  Ptolemy)
+    sci_required_ptolemyII=yes
+    sci_required_java=yes
+  ;;
+  *)
+    { echo "$as_me:$LINENO: WARNING: In aclocal.m4: No known dependencies for Package Ptolemy" >&5
+echo "$as_me: WARNING: In aclocal.m4: No known dependencies for Package Ptolemy" >&2;}
+  ;;
+esac
+
+
 fi
 
 for i in $package; do
@@ -4470,7 +4614,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4473:" \
+echo "$as_me:4617:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -38148,6 +38292,82 @@ fi
 
 sci_defs_files="$sci_defs_files include/sci_defs/insight_testdefs.h"
 
+##  --  search for Ptolemy II ---------------------------------------------------
+if test "$sci_required_ptolemyII" = "yes"; then
+
+  echo "$as_me:$LINENO: checking for Java." >&5
+echo $ECHO_N "checking for Java.... $ECHO_C" >&6
+
+  # check for Java
+  if test -z "$with_java"; then
+
+    { echo "$as_me:$LINENO: WARNING: Java is required by the Ptolemy package." >&5
+echo "$as_me: WARNING: Java is required by the Ptolemy package." >&2;}
+    echo "$as_me:$LINENO: checking for environment variable JAVA_HOME or JAVAHOME" >&5
+echo $ECHO_N "checking for environment variable JAVA_HOME or JAVAHOME... $ECHO_C" >&6
+
+    if test -z "$JAVA_HOME"; then
+      if test -z "$JAVAHOME"; then # Ptolemy build uses JAVAHOME
+
+	{ echo "$as_me:$LINENO: WARNING: Package Ptolemy requires Java." >&5
+echo "$as_me: WARNING: Package Ptolemy requires Java." >&2;}
+	{ { echo "$as_me:$LINENO: error: Use the --with-java=DIR option or set the environment variable JAVA_HOME to the directory that contains your Java distribution." >&5
+echo "$as_me: error: Use the --with-java=DIR option or set the environment variable JAVA_HOME to the directory that contains your Java distribution." >&2;}
+   { (exit 1); exit 1; }; }
+
+      else # JAVAHOME set in environment
+	jdir="$JAVAHOME"
+      fi
+    else # JAVA_HOME set in environment
+      jdir="$JAVA_HOME"
+    fi
+  else # --with-java
+    jdir="$with_java"
+  fi
+
+  if test -d "$jdir"; then
+    echo "$as_me:$LINENO: result: $jdir" >&5
+echo "${ECHO_T}$jdir" >&6
+
+    JAVA_PATH="$jdir"
+  else
+
+    { { echo "$as_me:$LINENO: error: Java installation directory is missing." >&5
+echo "$as_me: error: Java installation directory is missing." >&2;}
+   { (exit 1); exit 1; }; }
+
+  fi
+
+  echo "$as_me:$LINENO: checking for Ptolemy II." >&5
+echo $ECHO_N "checking for Ptolemy II.... $ECHO_C" >&6
+
+
+  # search here
+  if test "$with_ptolemyII"; then
+    pdir="$with_ptolemyII"
+  fi
+
+  if test -d "$pdir"; then
+    echo "$as_me:$LINENO: result: $pdir" >&5
+echo "${ECHO_T}$pdir" >&6
+
+    PTOLEMY_PATH="$pdir"
+    PTOLEMY_CLASSPATH="$PTOLEMY_PATH:/lib/diva.jar:/lib/java_cup.jar:/lib/sootclasses.jar:/lib/jasminclasses.jar:/lib/ptCal.jar:/lib/ptjacl.jar:/lib/jython.jar:/lib/mapss.jar:/lib/saxon7.jar:/ptolemy/ptolemy.jar:/ptolemy/ptsupport.jar:/ptolemy/vergil/vergil.jar:$JAVA_PATH/jre:/lib/rt.jar"
+    HAVE_PTOLEMY="yes"
+  else
+    { { echo "$as_me:$LINENO: error: Ptolemy II directory is missing." >&5
+echo "$as_me: error: Ptolemy II directory is missing." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+fi
+
+
+
+
+
+sci_defs_files="$sci_defs_files include/sci_defs/ptolemy_testdefs.h"
+
 ##  --  search for xalan  ---------------------------------------------------
 if test "$sci_required_xalan" ; then
   echo "$as_me:$LINENO: checking for xalan-j." >&5
@@ -50735,6 +50955,10 @@ s,@DEF_INSIGHT@,$DEF_INSIGHT,;t t
 s,@INC_INSIGHT_H@,$INC_INSIGHT_H,;t t
 s,@INSIGHT_LIB_FLAG@,$INSIGHT_LIB_FLAG,;t t
 s,@INSIGHT_LIB_DIR_FLAG@,$INSIGHT_LIB_DIR_FLAG,;t t
+s,@HAVE_PTOLEMY@,$HAVE_PTOLEMY,;t t
+s,@JAVA_PATH@,$JAVA_PATH,;t t
+s,@PTOLEMY_PATH@,$PTOLEMY_PATH,;t t
+s,@PTOLEMY_CLASSPATH@,$PTOLEMY_CLASSPATH,;t t
 s,@XALAN_PATH@,$XALAN_PATH,;t t
 s,@TAU_MAKEFILE@,$TAU_MAKEFILE,;t t
 s,@BABEL_BIN@,$BABEL_BIN,;t t
