Fixed so that --with-mpi (without a dir) works.  (Sync with branch.)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31983,12 +31983,15 @@ echo "$as_me: checking for required MPI components......" >&6;}
         # CXX="mp$CXX"
         # ;;
      *)
+        _sci_optional=optional
         if test "$with_mpi"; then
-           _sci_lib="$with_mpi/lib"
-           _sci_inc="$with_mpi/include"
-        else
-           _sci_lib="$sci_thirdparty_libs"
-           _sci_inc="$sci_thirdparty_includes"
+           if test "$with_mpi" = "yes"; then
+              _sci_optional=required
+           else
+              _sci_optional=specific
+              _sci_lib="$with_mpi/lib"
+              _sci_inc="$with_mpi/include"
+           fi
         fi
         # /usr/include/mpi is the standard location of mpi on some linux dists.
 
@@ -32464,8 +32467,8 @@ _sci_includes=''
 
 
         if test "$HAVE_MPI" != "yes"; then
-        # Try without pmpi (and with pthreads) (for the newer version
-	# of lam mpi.
+          # Try without pmpi (and with pthreads) (for the newer version
+          # of lam mpi.
 
 ##
 ## SCI_TRY_LINK (MPI):  mpi library and header-2
@@ -32938,8 +32941,7 @@ _sci_includes=''
 
 
 
-
-        if test "$HAVE_MPI" != "yes"; then
+          if test "$HAVE_MPI" != "yes"; then
 
 ##
 ## SCI_TRY_LINK (MPI):  mpi library and header-3
@@ -33412,7 +33414,7 @@ _sci_includes=''
 
 
 
-           if test "$HAVE_MPI" != "yes"; then
+             if test "$HAVE_MPI" != "yes"; then
 
 ##
 ## SCI_TRY_LINK (MPI):  mpich library and header
@@ -33885,17 +33887,27 @@ _sci_includes=''
 
 
 
-              if test "$HAVE_MPI" = "yes"; then
-  	        HAVE_MPICH="yes"
-#  	        LIB_DIR_MPI="$LIB_DIR_MPICH"
-#                MPI_LIB_FLAG="$MPICH_LIB_FLAG"
-#                MPI_LIB_DIR_FLAG="$MPICH_LIB_DIR_FLAG"
-              fi
-           fi
-        fi
+                if test "$HAVE_MPI" = "yes"; then
+                  HAVE_MPICH="yes"
+                fi
+             fi
+          fi
         fi
 
         if test "$HAVE_MPI" = "yes"; then
+
+           if test "$_sci_optional" = "specific"; then
+              # verify that it was found in the location requested.
+              if test ! -e $with_mpi/lib/libmpi.so &&
+                 test ! -e $with_mpi/lib/libmpi.a &&
+                 test ! -e $with_mpi/lib/libmpi.dylib; then
+                   echo
+                   { { echo "$as_me:$LINENO: error: Found libmpi but not in requested directory: $with_mpi/lib" >&5
+echo "$as_me: error: Found libmpi but not in requested directory: $with_mpi/lib" >&2;}
+   { (exit 1); exit 1; }; }
+              fi
+           fi
+
            if test "$HAVE_MPICH" = "yes"; then
              DEF_MPI="#define HAVE_MPICH 1"
            else
