Fixed typo. Fixed PNG lib specification.  Made GLEW required.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10509,8 +10509,8 @@ if test -z "$thirdparty"; then
     if test -e $_sci_tp_path; then
       sci_thirdparty_dir="$_sci_tp_path"
     else
-      { { echo "$as_me:$LINENO: error: Thidparty installation does not exist in $_sci_tmp_tp_path or in $_sci_tp_path. Please specify the installation like this --with-thirdparty=DIR" >&5
-echo "$as_me: error: Thidparty installation does not exist in $_sci_tmp_tp_path or in $_sci_tp_path. Please specify the installation like this --with-thirdparty=DIR" >&2;}
+      { { echo "$as_me:$LINENO: error: Thirdparty installation does not exist in $_sci_tmp_tp_path or in $_sci_tp_path. Please specify the installation like this --with-thirdparty=DIR" >&5
+echo "$as_me: error: Thirdparty installation does not exist in $_sci_tmp_tp_path or in $_sci_tp_path. Please specify the installation like this --with-thirdparty=DIR" >&2;}
    { (exit 1); exit 1; }; }
     fi
   fi
@@ -25456,7 +25456,8 @@ if test "$with_png" = "yes"; then
 else
   if test "$with_png"; then
     # If --with-png has a parameter, then use it
-    _sci_lib="$with_png/lib"
+    #   The BASE_LIB_PATH below will add /lib or /lib{64,32} to the sci_lib
+    _sci_lib="$with_png"
     _sci_inc="$with_png/include"
 
 ##
@@ -53817,7 +53818,7 @@ fi # end sci_required_oogl
 
 
 ##  --  search for glew  -----------------------------------------------
-_sci_optional=optional
+_sci_optional=required
 _sci_lib="$sci_thirdparty_lib"
 _sci_inc="$sci_thirdparty_include"
 
