Update --with-tabprops configure check.  Note, use of HDF5 now requries the C++ hdf5 library.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -745,10 +745,6 @@ DEF_ZOLTAN
 INC_ZOLTAN_H
 ZOLTAN_LIB_FLAG
 ZOLTAN_LIB_DIR_FLAG
-DEF_TABPROPS
-INC_TABPROPS_H
-TABPROPS_LIB_FLAG
-TABPROPS_LIB_DIR_FLAG
 PATH_TO_VC
 PATH_TO_PSDK
 PATH_TO_MSYS_BIN
@@ -881,6 +877,10 @@ DEF_HDF5
 INC_HDF5_H
 HDF5_LIB_FLAG
 HDF5_LIB_DIR_FLAG
+DEF_TABPROPS
+INC_TABPROPS_H
+TABPROPS_LIB_FLAG
+TABPROPS_LIB_DIR_FLAG
 HAVE_HYPRE
 DEF_HYPRE
 INC_HYPRE_H
@@ -7299,49 +7299,6 @@ echo "${ECHO_T}yes" >&6; }
   INC_ZOLTAN_H="-I$with_zoltan/include"
   ZOLTAN_LIB_DIR_FLAG="-L$with_zoltan/lib"
   ZOLTAN_LIB_FLAG="-lzoltan"
-
-fi
-
-
-
-
-
-## -----------------------------------------------
-
-##  --  search for TabProps ------------------------
-
-if test "$with_tabprops"; then
-  if test "$with_tabprops" = "yes"; then
-    { { echo "$as_me:$LINENO: error: --with-tabprops=DIR requires a DIRectory be provided. " >&5
-echo "$as_me: error: --with-tabprops=DIR requires a DIRectory be provided. " >&2;}
-   { (exit 1); exit 1; }; }
-  else
-    { echo "$as_me:$LINENO: checking for TabProps files (For now we are just verifying the existence of lib and .h files)" >&5
-echo $ECHO_N "checking for TabProps files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
-    if test ! -d $with_tabprops; then
-      { { echo "$as_me:$LINENO: error: '$with_tabprops' directory does not exist. " >&5
-echo "$as_me: error: '$with_tabprops' directory does not exist. " >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    if test ! -f $with_tabprops/lib/libtabprops.a; then
-      { { echo "$as_me:$LINENO: error: '$with_tabprops/lib/libtabprops.a' does not exist. " >&5
-echo "$as_me: error: '$with_tabprops/lib/libtabprops.a' does not exist. " >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    for file in BSpline.h LU.h StateTable.h; do
-      if test ! -f $with_tabprops/include/$file; then
-        { { echo "$as_me:$LINENO: error: '$with_tabprops/include/$file' does not exist. " >&5
-echo "$as_me: error: '$with_tabprops/include/$file' does not exist. " >&2;}
-   { (exit 1); exit 1; }; }
-      fi
-    done
-  fi
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-  DEF_TABPROPS="#define HAVE_TABPROPS 1"
-  INC_TABPROPS_H="-I$with_tabprops/include"
-  TABPROPS_LIB_DIR_FLAG="-L$with_tabprops/lib"
-  TABPROPS_LIB_FLAG="-ltabprops"
 
 fi
 
@@ -44359,6 +44316,11 @@ fi
 sci_defs_files="$sci_defs_files include/sci_defs/teem_testdefs.h"
 
 ##  --  search for hdf5  -------------------------------------------------
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 # The sci_required_hdf5 could have been set to yes when using the
 # with_hdf5 agument or from a package in the aclocal.m4 it.
@@ -44410,9 +44372,9 @@ if test "$sci_required_hdf5" = "yes"; then
 ##
 ## arg 1 : HDF5
 ## arg 2 : hdf5 library and headers
-## arg 3 : hdf5.h
+## arg 3 : hdf5.h H5Cpp.h
 ## arg 4 : $_sci_inc
-## arg 5 : hdf5
+## arg 5 : hdf5 hdf5_cpp
 ## arg 6 : $_sci_lib
 ## arg 7 :
 ## arg 8 : <Can't expand it here as it may be multiple lines and cause sh problems.>
@@ -44495,10 +44457,10 @@ done
 
 ### Take care of arg 5 (the list of libs)
 
-if test -n "hdf5"; then
+if test -n "hdf5 hdf5_cpp"; then
 
    found_framework=no
-   for lib in hdf5; do
+   for lib in hdf5 hdf5_cpp; do
 
       if test "$found_framework" = "one"; then
          found_framework=two
@@ -44648,7 +44610,7 @@ LIBS="$_sci_libs  $LIBS"
 __extern_c="no"
 __sci_pound_includes=""
 
-for inc in "" hdf5.h; do
+for inc in "" hdf5.h H5Cpp.h; do
     if test "$inc" = "extern_C"; then
        __sci_pound_includes="extern \"C\" {"
        __extern_c=yes
@@ -44697,7 +44659,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
+	 test -z "$ac_cxx_werror_flag" ||
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
@@ -44818,7 +44780,7 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 if test "$_sci_optional" = "specific"; then
   #echo specific
   # Make sure the exact includes were found
-  for i in "" hdf5.h; do
+  for i in "" hdf5.h H5Cpp.h; do
     #echo looking for $_sci_inc/$i
     if test ! -e $_sci_inc/$i; then
      { { echo "$as_me:$LINENO: error: Specifically requested HDF5 include file '$_sci_inc/$i' was not found" >&5
@@ -44827,7 +44789,7 @@ echo "$as_me: error: Specifically requested HDF5 include file '$_sci_inc/$i' was
     fi
   done
   # Make sure the exact libraries were found
-  for i in "" hdf5; do
+  for i in "" hdf5 hdf5_cpp; do
     if test -z "$i"; then
        continue
     fi
@@ -44872,6 +44834,55 @@ fi #end sci_required_hdf5
 		# Place this var in the configVars.mk.in
 	# Place this var in the configVars.mk.in
 sci_defs_files="$sci_defs_files include/sci_defs/hdf5_testdefs.h"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+##  --  search for TabProps ------------------------
+
+if test "$HAVE_HDF5" != "yes"; then
+  { { echo "$as_me:$LINENO: error: --with-tabprops=DIR requires HDF5. " >&5
+echo "$as_me: error: --with-tabprops=DIR requires HDF5. " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "$with_tabprops"; then
+  if test "$with_tabprops" = "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-tabprops=DIR requires a DIRectory be provided. " >&5
+echo "$as_me: error: --with-tabprops=DIR requires a DIRectory be provided. " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    { echo "$as_me:$LINENO: checking for TabProps files (For now we are just verifying the existence of lib and .h files)" >&5
+echo $ECHO_N "checking for TabProps files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
+    if test ! -d $with_tabprops; then
+      { { echo "$as_me:$LINENO: error: '$with_tabprops' directory does not exist. " >&5
+echo "$as_me: error: '$with_tabprops' directory does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    for file in include/tabprops/BSpline.h include/tabprops/LU.h include/tabprops/StateTable.h lib/tabprops/libtabprops.a; do
+      if test ! -f $with_tabprops/$file; then
+        { { echo "$as_me:$LINENO: error: '$with_tabprops/$file' does not exist. " >&5
+echo "$as_me: error: '$with_tabprops/$file' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+    done
+  fi
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  DEF_TABPROPS="#define HAVE_TABPROPS 1"
+  INC_TABPROPS_H="-I$with_tabprops/include"
+  TABPROPS_LIB_DIR_FLAG="-L$with_tabprops/lib/tabprops"
+  TABPROPS_LIB_FLAG="-ltabprops"
+
+fi
+
+
+
+
+
+## -----------------------------------------------
 
 ##  --  search for hypre stuff  ------------------------------------------
 
@@ -46274,10 +46285,6 @@ DEF_ZOLTAN!$DEF_ZOLTAN$ac_delim
 INC_ZOLTAN_H!$INC_ZOLTAN_H$ac_delim
 ZOLTAN_LIB_FLAG!$ZOLTAN_LIB_FLAG$ac_delim
 ZOLTAN_LIB_DIR_FLAG!$ZOLTAN_LIB_DIR_FLAG$ac_delim
-DEF_TABPROPS!$DEF_TABPROPS$ac_delim
-INC_TABPROPS_H!$INC_TABPROPS_H$ac_delim
-TABPROPS_LIB_FLAG!$TABPROPS_LIB_FLAG$ac_delim
-TABPROPS_LIB_DIR_FLAG!$TABPROPS_LIB_DIR_FLAG$ac_delim
 PATH_TO_VC!$PATH_TO_VC$ac_delim
 PATH_TO_PSDK!$PATH_TO_PSDK$ac_delim
 PATH_TO_MSYS_BIN!$PATH_TO_MSYS_BIN$ac_delim
@@ -46367,6 +46374,10 @@ HAVE_CBLAS!$HAVE_CBLAS$ac_delim
 INC_BLAS_H!$INC_BLAS_H$ac_delim
 BLAS_LIB_FLAG!$BLAS_LIB_FLAG$ac_delim
 BLAS_LIB_DIR_FLAG!$BLAS_LIB_DIR_FLAG$ac_delim
+DEF_BLAS!$DEF_BLAS$ac_delim
+DEF_CBLAS!$DEF_CBLAS$ac_delim
+HAVE_LAPACK!$HAVE_LAPACK$ac_delim
+DEF_LAPACK!$DEF_LAPACK$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -46408,10 +46419,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-DEF_BLAS!$DEF_BLAS$ac_delim
-DEF_CBLAS!$DEF_CBLAS$ac_delim
-HAVE_LAPACK!$HAVE_LAPACK$ac_delim
-DEF_LAPACK!$DEF_LAPACK$ac_delim
 LAPACK_LIB_FLAG!$LAPACK_LIB_FLAG$ac_delim
 LAPACK_LIB_DIR_FLAG!$LAPACK_LIB_DIR_FLAG$ac_delim
 HAVE_LAPACKMP!$HAVE_LAPACKMP$ac_delim
@@ -46451,6 +46458,10 @@ DEF_HDF5!$DEF_HDF5$ac_delim
 INC_HDF5_H!$INC_HDF5_H$ac_delim
 HDF5_LIB_FLAG!$HDF5_LIB_FLAG$ac_delim
 HDF5_LIB_DIR_FLAG!$HDF5_LIB_DIR_FLAG$ac_delim
+DEF_TABPROPS!$DEF_TABPROPS$ac_delim
+INC_TABPROPS_H!$INC_TABPROPS_H$ac_delim
+TABPROPS_LIB_FLAG!$TABPROPS_LIB_FLAG$ac_delim
+TABPROPS_LIB_DIR_FLAG!$TABPROPS_LIB_DIR_FLAG$ac_delim
 HAVE_HYPRE!$HAVE_HYPRE$ac_delim
 DEF_HYPRE!$DEF_HYPRE$ac_delim
 INC_HYPRE_H!$INC_HYPRE_H$ac_delim
