Look for Freetype2 in Thirdparty

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3510,6 +3510,18 @@ esac
 
 fi
 
+
+if test "$pkg_Insight" = "yes"; then
+  if test -z "$sci_required_insight"; then
+    { echo "$as_me:$LINENO: WARNING: Insight is required by the Insight package." >&5
+echo "$as_me: WARNING: Insight is required by the Insight package." >&2;}
+    { echo "$as_me:$LINENO: WARNING: Use the --with-insight=DIR option if Insight is not located in Thirdparty." >&5
+echo "$as_me: WARNING: Use the --with-insight=DIR option if Insight is not located in Thirdparty." >&2;}
+    sci_required_insight=yes
+  fi
+
+fi
+
 # Make sure the Package directories exist.
 #   Do an 'ls' of all files in the Packages directory and then grep for the
 #   package in this list.  (We used to just do a "test -d $package", but on
@@ -6784,7 +6796,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6787:" \
+echo "$as_me:6799:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -54354,10 +54366,16 @@ if test -e $freetype_bin/freetype-config; then
 echo "${ECHO_T}Using $freetype_bin/freetype-config to set freetype variables." >&6
 
     includes=`$freetype_bin/freetype-config --cflags`
+elif test -e $sci_thirdparty_dir/bin/freetype-config; then
+    echo "$as_me:$LINENO: result: Using $sci_thirdparty_dir/bin/freetype-config to set freetype variables." >&5
+echo "${ECHO_T}Using $sci_thirdparty_dir/bin/freetype-config to set freetype variables." >&6
+    found_freetype_config="yes"
+    includes=`$sci_thirdparty_dir/bin/freetype-config --cflags`
+    _sci_lib="$sci_thirdparty_lib"
 else
     echo "$as_me:$LINENO: result: No 'freetype-config' file found in $freetype_bin." >&5
 echo "${ECHO_T}No 'freetype-config' file found in $freetype_bin." >&6
-    # try the 3P (for windows...)
+    # try the 3P for windows
     _sci_lib="$sci_thirdparty_lib"
     _sci_inc="$sci_thirdparty_include"
     includes=""
