Merge of trunk with /branches/md_dev     (svn merge -r50954:51034)

diff --git a/md_dev/src/Makefile.in b/md_dev/src/Makefile.in
--- a/md_dev/src/Makefile.in
+++ b/md_dev/src/Makefile.in
@@ -118,7 +118,12 @@ TCL_ETAGS_FILES := $(wildcard $(TCL_FILES))
 ETAGS := @ETAGS@
 CTAGS := ctags
 
-all:: prereqs packmaker $(ALLTARGETS) uintah
+################################################################################
+# 'uintah' target is defined in StandAlone/sub.mk
+#
+all:: prereqs packmaker $(ALLTARGETS) uintah verify_zlib
+#
+################################################################################
 
 prereqs : $(MAKEFILEDIRSTAG) $(CREATETCLINDEX) $(LIBDIR) $(SUBMAKEFILES) $(ALLGEN) $(VCDIR) $(VCDEPS)
 	@if test ! -f prereqs; then \
@@ -249,18 +254,51 @@ $(VCSOLUTION): $(ALLVCPROJECTS)
 	@echo -e "Microsoft Visual Studio Solution File, Format Version 8.00$(foreach project,$^,\nProject(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"$(basename $(notdir $(project)))\", \"$(project)\", \"{$($(project)_ID)}\"\n\tProjectSection(ProjectDependencies) = postProject$(foreach dep,$($(project)_PROJ_DEPS),\n\t\t{$($(dep)_ID)} = {$($(dep)_ID)}PPPPP)\n\tEndProjectSection\nEndProject)\nGlobal\n\tGlobalSection(SolutionConfiguration) = preSolution\n\t\t$(CONF_NAME) = $(CONF_NAME)\n\tEndGlobalSection\n\tGlobalSection(ProjectConfiguration) = postSolution$(foreach project,$^,\n\t\t{$($(project)_ID)}.$(CONF_NAME).ActiveCfg = $(CONF_NAME)|Win32\n\t\t{$($(project)_ID)}.$(CONF_NAME).Build.0 = $(CONF_NAME)|Win32PPPPP)\n\tEndGlobalSection\n\tGlobalSection(ExtensibilityGlobals) = postSolution\n\tEndGlobalSection\n\tGlobalSection(ExtensibilityAddIns) = postSolution\n\tEndGlobalSection\nEndGlobal" | sed 's,PPPPP ,,g' | sed 's,PPPPP,,g' > $@
 
 #########################################################################################################
+# Targets for zlib verification
+verify_zlib : sus
+ifneq ($(IS_OSX),yes)
+	@num_libs=`ldd lib/*.so StandAlone/sus | grep libz[\.] | cut -f3 -d" " | sort -u | wc | awk '{print $$1}'`; \
+         if test "$$num_libs" -ne 1; then                                                                       \
+            echo "";                                                                                            \
+            echo "It appears that more than one version of libz was linked into Uintah...";                     \
+            echo "This will cause the use of compression for UDAs to fail:";                                    \
+            echo "";                                                                                            \
+            ldd lib/*.so StandAlone/sus | grep libz[\.] | cut -f3 -d" " | sort -u;                              \
+            echo "";                                                                                            \
+            echo "Exiting make... Goodbye.";                                                                    \
+            echo "";                                                                                            \
+            exit 1;                                                                                             \
+         fi
+else
+	@num_libs=`otool -L lib/*.dylib StandAlone/sus | grep libz[\.] | cut -f1 -d" " | sort -u | wc | awk '{print $$1}'`; \
+         if test "$$num_libs" -ne 1; then                                                                       \
+            echo "";                                                                                            \
+            echo "It appears that more than one version of libz was linked into Uintah...";                     \
+            echo "This will cause the use of compression for UDAs to fail:";                                    \
+            echo "";                                                                                            \
+            otool -L lib/*.dylib StandAlone/sus | grep libz[\.] | cut -f1 -d" " | sort -u;                      \
+            echo "";                                                                                            \
+            echo "Exiting make... Goodbye.";                                                                    \
+            echo "";                                                                                            \
+            exit 1;                                                                                             \
+         fi
+endif
+
+#########################################################################################################
 # Targets for regression testing...
 
 gold_standards :
-	@mkdir -p $(OBJTOP_ABS)/TestData;                    \
-         cd $(OBJTOP_ABS)/TestData;                          \
-	 components=`$(SRCTOP_ABS)/R_Tester/helpers/selectComponents.sh $(SRCTOP_ABS)/R_Tester`; \
-	 if test "$$?" -eq 0; then                            \
-            export PYTHONPATH="$(SRCTOP_ABS)/R_Tester/toplevel:$(SRCTOP_ABS)/R_Tester"; \
-            $(SRCTOP_ABS)/R_Tester/toplevel/generateGoldStandards.py \
-	                                           -d $(IS_DEBUG) -b $(OBJTOP_ABS) -s $(SRCTOP_ABS) $$components \
-	                                           -m $(SCI_MALLOC_ON) -j $(MAKE_PARALLELISM) -v; \
-         fi
+	@mkdir -p $(OBJTOP_ABS)/TestData;                                                                        \
+         echo -n "Started at: "; date;                                                                           \
+         cd $(OBJTOP_ABS)/TestData;                                                                              \
+         components=`$(SRCTOP_ABS)/R_Tester/helpers/selectComponents.sh $(SRCTOP_ABS)/R_Tester`;                 \
+         if test "$$?" -eq 0; then                                                                               \
+            export PYTHONPATH="$(SRCTOP_ABS)/R_Tester/toplevel:$(SRCTOP_ABS)/R_Tester";                          \
+            $(SRCTOP_ABS)/R_Tester/toplevel/generateGoldStandards.py                                             \
+                                                   -d $(IS_DEBUG) -b $(OBJTOP_ABS) -s $(SRCTOP_ABS) $$components \
+                                                   -m $(SCI_MALLOC_ON) -j $(MAKE_PARALLELISM) -v;                \
+         fi;                                                                                                     \
+         echo -n "Ended at: "; date
 
 #__________________________________
 #  to execute the local regression tester
