Parallel copy script that runs on multiple nodes.
The user must be using either interactive nodes or the batch scheduling system.
The user is limited to 50 processors to transfer data.  Three methods to transfer
data are supported cp, tar and rsync.  Rsync is strongly encouraged since it has error checking

Usage: pcp <number of nodes> <method (cp/rsync/tar)> <transfer entire uda (y/n) > < remove remote directory (y/n) > < local dir to be copied> <remote dir>"

diff --git a/src/scripts/pcp b/src/scripts/pcp
--- a/src/scripts/pcp
+++ b/src/scripts/pcp
@@ -1,70 +1,85 @@
-#! /bin/bash
+#! /bin/bash -norc
 #
 #______________________________________________________________________
 # Parallel copy (cp)
-# pcp <num Processors> <transfer entire uda (y/n)> < remove remote directory> < localDirectory>
-
+# This script copies an uda between file system in parallel.  It requires
+# that the user has interactive nodes or is using batch scheduling system.
 #______________________________________________________________________
-#echo $argv
-#
-#------------------
 # unalias commands
 unalias -a rm
 unalias -a cd
 
-#------------------
+#__________________________________
 # error checking
-if test "$#" -ne 5; then
+if test "$#" -ne 6; then
   echo ""
-  echo "Usage: pcp < number of Processes> <transfer entire uda (y/n) > < remove remote directory (y/n) > < local dir to be copied> <remote dir>"
-  echo ""
-  exit 1
-fi
-
-# Need /usr/bin/which as the shell which doesn't give us the full path...
-if test ! -x /usr/bin/which; then
-  echo ""
-  echo "Error:  Can't find /usr/bin/which...  Goodbye."
+  echo "Usage: pcp <number of nodes> <method (rsync/tar)> <transfer entire uda (y/n) > < remove remote directory (y/n) > < local dir to be copied> <remote dir>"
   echo ""
   exit 1
 fi
 
-pcpfulldir=`readlink -f $0`
-pcpdir=`dirname $pcpfulldir`
+# is this node under PBS control?
+printenv PBS_NUM_PPN > /dev/null 2>&1
+if test $? != 0 ; then
+  echo ""
+  echo "ERROR: you must run this script on interactive nodes or through the batch scheduling system."
+  echo ""
+  exit 1  
+fi
 
-nproc=$1
-transferWholeUda=$2
-rmDir=$3
-localDir=$4
-uda=`basename $localDir`
-REMOTEDIR=$5
+#__________________________________
+# local variables are all lowercase
+# upper case:  enviromental vars that are passed to the makefile
+pcpfulldir=`readlink -f $0`     
+PCPDIR=`dirname $pcpfulldir`    # path to driver script
+pcpTmpDir="$HOME/.pcp"          # directory to keep temporary files
+
+
+# parse the arguments
+numNodes=$1                     # number of nodes
+METHOD=$2                       # cp, tar or rsync
+transferWholeUda=$3
+rmDir=$4
+LOCALDIR=$5                     # local directory path
+uda=`basename $LOCALDIR`        # name of the uda
+REMOTEDIR=$6                    # path to the remote directory
+let numPPM=$PBS_NUM_PPN-1       # number of processors per node, keep one node free or you will lock up the machine 
 
 OS=`uname`
 if test "$OS" == "Darwin"; then
-  # Darwin and Linux are similar enought that this works...
-  OS="Linux"
+  OS="Linux"   # Darwin and Linux are similar
 fi
 
-if test `echo $localDir | cut -c1` != "/"; then
+if test $METHOD != "cp" -a $METHOD != "rsync" -a $METHOD != "tar"; then
+  echo ""
+  echo "ERROR:  the method option is not valid ($METHOD)"
+  echo "        valid options are  (cp/rsync/tar)"
+  echo ""
+  exit 1
+fi
+
+if test `echo $LOCALDIR | cut -c1` != "/"; then
   # Not absolute path... fix it.
-  localDir=`pwd`/$4
+  LOCALDIR=`pwd`/$5
 fi
 
+/bin/rm -rf $pcpTmpDir
+mkdir $pcpTmpDir     
 
-export PCP_FILES=/tmp/pcp_files_`basename $localDir`_`whoami`
+export PCP_FILES=$pcpTmpDir/pcp_files_$uda
 
 echo "_____________________________________"
 echo "Inputs:"
-echo "	# processes:           $nproc"
+echo "	# nodes:               $numNodes"
+echo "	# procs per node:      $numPPM"
+echo "	method:                $METHOD"
 echo "	transfer whole uda:    $transferWholeUda"
-echo "	localDir:              $localDir"
+echo "	LOCALDIR:              $LOCALDIR"
 echo "	remoteDir:             $REMOTEDIR"
 echo "	remove the remote directory?: " $rmDir
-echo "	PCP_FILES:            $PCP_FILES"
-echo "	pcpdir:               $pcpdir"
 echo "_____________________________________"
 echo ""
-#------------------
+#__________________________________
 # Bulletproofing
 echo "Bullet proof tests:"
 
@@ -105,14 +120,16 @@ validateTransferredFilesDir()
   fi
 }
 
-export STAMP_DIR=$localDir/.transferred_files
+#__________________________________
+
+export STAMP_DIR=$LOCALDIR/.transferred_files
 validateTransferredFilesDir
 
 if test ! -d "$STAMP_DIR"; then
   # Didn't have permissions to make the directory... so place it in tmp
   echo ""
   echo "  WARNING: Was not able to create $STAMP_DIR directory (bad permissions?)."
-  export STAMP_DIR=/tmp/.transferred_files_`basename $localDir`_`whoami`
+  export STAMP_DIR=/tmp/.transferred_files_`basename $LOCALDIR`_`whoami`
   echo "           Placing it in $STAMP_DIR instead."
   echo ""
   validateTransferredFilesDir
@@ -124,18 +141,18 @@ if test ! -d "$STAMP_DIR"; then
   echo ""
 fi
 
-if test "$localDir" == "."; then
+if test "$LOCALDIR" == "."; then
   echo ""
   echo "  ERROR: You can't set the local dir to '.'"
   echo ""
   exit 1
 fi
 
-echo -n "  Testing: does the local folder ($localDir) exist... "
-if test ! -e $localDir; then
+echo -n "  Testing: does the local folder ($LOCALDIR) exist... "
+if test ! -e $LOCALDIR; then
   echo ""
   echo ""
-  echo "  ERROR: Local directory '$localDir' does not exist"
+  echo "  ERROR: Local directory '$LOCALDIR' does not exist"
   echo ""
   exit 1
 fi
@@ -153,51 +170,70 @@ if test ! -d "$REMOTEDIR"; then
 fi
 echo "yes."
 
-if test ! -e $pcpdir/pcp_driver_$OS; then
+if test ! -e $PCPDIR/pcp_driver_$OS; then
   echo ""
   echo ""
-  echo " ERROR: the driver file $pcpdir/pcp_driver_$OS does not exist..."
+  echo " ERROR: the driver file $PCPDIR/pcp_driver_$OS does not exist..."
   echo ""
   echo ""
 fi
+
+if test $numNodes -gt $PBS_NUM_NODES; then
+  echo ""
+  echo ""
+  echo " ERROR:  The number of nodes you've requested to copy data exceeds what the batch scheduler system has allocated to you"
+  echo ""
+  exit 1 
+fi
+
+let numProcs=$numNodes*$numPPM
+if test $numProcs -gt 50; then
+  echo ""
+  echo ""
+  echo " ERROR:  You cannot use more than 50 procs to copy data"
+  echo ""
+  exit 1 
+fi
+
 echo "_____________________________________"
 
-#--------------------------------------------------------------------------
+#______________________________________________________________________
 # Now do the work
-
-#--------------------------------------------------------------------------
 # record some info for posterity
 
-DATA_TRANSFER_RECORD=$localDir/data_transfer_record
+data_transfer_record=$LOCALDIR/data_transfer_record
 
-touch $DATA_TRANSFER_RECORD
+touch $data_transfer_record
 
-if test ! -f $DATA_TRANSFER_RECORD; then
+if test ! -f $data_transfer_record; then
   # Can't write to that directory... just place it in tmp for now.
-  DATA_TRANSFER_RECORD=/tmp/data_transfer_record_`whoami`
+  data_transfer_record=/tmp/data_transfer_record_`whoami`
 fi
 
-echo "--------------------------------" >> $DATA_TRANSFER_RECORD
-echo "Data transferred from: $HOSTNAME" >> $DATA_TRANSFER_RECORD
-echo "on `date`."                       >> $DATA_TRANSFER_RECORD
-echo "Data originally in $localDir"     >> $DATA_TRANSFER_RECORD
-echo "Copied to $REMOTEDIR"             >> $DATA_TRANSFER_RECORD
-echo ""                                 >> $DATA_TRANSFER_RECORD
+echo "--------------------------------" >> $data_transfer_record
+echo "Data transferred from: $HOSTNAME" >> $data_transfer_record
+echo "on `date`."                       >> $data_transfer_record
+echo "Data originally in $LOCALDIR"     >> $data_transfer_record
+echo "Copied to $REMOTEDIR"             >> $data_transfer_record
+echo "Number of nodes: $numNodes"       >> $data_transfer_record
+echo "Method of copying data: $METHOD"  >> $data_transfer_record
+echo ""                                 >> $data_transfer_record
 
 # remove the remote directory
 if test "$rmDir" == "y" -o "$rmDir" == "Y"; then
   echo "Now removing $REMOTEDIR/$uda if it exists..."
   /bin/rm -rf $REMOTEDIR/$uda; mkdir $REMOTEDIR/$uda
 else
-  cp $DATA_TRANSFER_RECORD $REMOTEDIR/$uda
+  cp $data_transfer_record $REMOTEDIR/$uda
 fi
 
 REMOTEDIR="$REMOTEDIR/$uda/"
-cd $localDir
+cd $LOCALDIR
 
-#-------------------------------
+#______________________________________________________________________
 # make a sorted list of potential files to copy
 # let the user edit that file with vi
+/bin/rm -f md5sum_org md5sum_copy md5sum_sorted /tmp/pcp.tmp > /dev/null 2>&1
 /bin/rm -f $PCP_FILES
 
 FIND=find
@@ -205,29 +241,106 @@ $FIND .             -maxdepth 1 -type f -exec basename {} \; | grep -v .transfer
 $FIND ./t*          -maxdepth 0 -type d -exec basename {} \; | sort -r                    >>$PCP_FILES
 $FIND ./checkpoints -maxdepth 1                                                           >>$PCP_FILES
 
-
 if test "$transferWholeUda" == "n" -o "$transferWholeUda" == "N"; then
   echo "Now starting an editor:  Remove the files you don't want transferred"
-
-  if test ! $?EDITOR || test "$EDITOR" == ""; then
-    echo
-    echo WARNING: \$EDITOR is not defined... defaulting to 'vi'
-    echo "And 'vi' sometimes doesn't work well..."
-    export EDITOR=vi
-  fi
+  vi $PCP_FILES
 fi
 
-$EDITOR $PCP_FILES
 chmod ug+rw $PCP_FILES
  
 echo
 echo -n "Starting at: "
 date
-echo 
-echo "/usr/bin/time -p make TAR=tar --file $pcpdir/pcp_driver_$OS -j $nproc"
+echo
 
-/usr/bin/time -p make TAR=tar --file $pcpdir/pcp_driver_$OS REMOTEDIR=$REMOTEDIR -j $nproc
+#__________________________________
+# chop up the PCP_files into smaller chunks
+# one chunk for each node
+totalLines=`wc -l $PCP_FILES| cut -f1 -d" "`
+let nLines=$totalLines/$numNodes 
+node=0
+startLine=1
+while [  $node -lt $numNodes ]; do
+  sed -n -e "$startLine,+$nLines p" $PCP_FILES > $PCP_FILES.$node
+  let node=node+1 
+  startLine=$((startLine+nLines))
+done
 
+# export all of the environmental variables.
+# these are read  back in 
+envVariables=$pcpTmpDir/envVars
+echo "export REMOTEDIR=$REMOTEDIR" >$envVariables
+echo "export PCP_FILES=$PCP_FILES" >>$envVariables
+echo "export STAMP_DIR=$STAMP_DIR" >>$envVariables
+echo "export LOCAL_DIR=$LOCALDIR"  >>$envVariables
+echo "export numPPM=$numPPM"       >>$envVariables
+echo "export OS=$OS"               >>$envVariables
+echo "export PCPDIR=$PCPDIR"       >>$envVariables
+echo "export METHOD=$METHOD"       >>$envVariables
+
+#__________________________________
+# distribute the work over the nodes, each node receives one copy of the command
+# the exit code of the make command is stored
+pbsdsh -u  bash -c 'source ~/.pcp/envVars; cd $LOCAL_DIR; make --file $PCPDIR/pcp_driver_$OS -j $numPPM ' 2> $pcpTmpDir/pcpRC.$uda
+
+
+
+# Check the make command exit code.
+grep -q 2 $pcpTmpDir/pcpRC.$uda
+
+if test $? -eq 0  ; then
+  echo ""
+  echo "ERROR:  something went wrong with the copy."
+  echo ""
+else
+  echo ""
+  echo "$uda has be copied to $REMOTEDIR"
+  echo "Blowing away the list of transferred files and the temporary directory"
+  rm -rf $STAMP_DIR
+  /bin/rm -rf $pcpTmpDir
+fi
+
+echo
+echo -n "Ending at: "
+date
+echo
+
+exit 0
+#______________________________________________________________________
+#  Generate a checksum of all the files in the original uda and verify that it is identical
+#  to the copied uda
+echo ""
+echo "Now running checksum test."
+echo -n "Starting at: "
+date
+pcp_tmp=/tmp/pcp.tmp
+/bin/rm -f md5sum_org.* md5sum_copy.* $pcp_tmp > /dev/null 2>&1
+
+# create files containing md5sums
+find $LOCALDIR -type f |xargs md5sum > $pcp_tmp
+sort -k 5 -t / $pcp_tmp > md5sum_org
+
+/bin/rm $pcp_tmp
+find $REMOTEDIR -type f|xargs md5sum > $pcp_tmp
+sort -k 5 -t / $pcp_tmp > md5sum_copy
+
+#cut out the file names since the paths will always be different
+cut -f 1 -d" " md5sum_org  > md5sum_org.clean
+cut -f 1 -d" " md5sum_copy > md5sum_copy.clean
+
+# only compare the 1st column that contains the md5sum
+diff -q  md5sum_org.clean md5sum_copy.clean
+
+if test $? != 0 ; then
+  echo ""
+  echo " ERROR:  the checksum of the original direcory != the copied directory"
+  echo " This indicates that the udas are are different!"
+  echo " To see the differences run:"
+  echo ""
+  echo " diff md5sum_org md5sum_copy"
+  echo " Now exiting"
+  exit 1
+fi
 echo
 echo -n "Ending at: "
 date
