Version 2.0
- All directories that are tarred are also compressed using either gzip or pigz (parallel gzip).
  With compression the timesteps directories are ~%35 smaller. 

- Added ability to extract compressed timesteps in parallel.

- new command line options:

      Options:
          -np:            [int]       Number of processores used.
          -allTimesteps:   [y/n]      operate on all directories in uda?  If "n" then a vi window will open allowing you to edit the timesteps
          -create         blank       create new archives
          -extract        blank       extract timestep archieves
          -uda            [dir name]  uda name
          -help:                      Display this option summary

diff --git a/src/scripts/udaTransferScripts/pTarUda b/src/scripts/udaTransferScripts/pTarUda
--- a/src/scripts/udaTransferScripts/pTarUda
+++ b/src/scripts/udaTransferScripts/pTarUda
@@ -1,11 +1,17 @@
-#! /bin/bash
+#!/bin/bash
 #
 #______________________________________________________________________
-#  This script tars, in parallel, each timestep in the uda and inside of the checkpoints 
+#  This script tars/untars, in parallel, each timestep in the uda and inside of the checkpoints 
 #  directory.
 #
 #  Usage:
-#   pTarUda < number of Processors> <tar all timesteps in the uda (y/n) >  < uda> 
+#   pTarUda 
+#            -np:            [int]       Number of processores used.
+#            -allTimesteps:   [y/n]       Tar all timesteps in uda?  If "n" then a vi window will open allowing you to edit the timesteps
+#            -create         blank       create new archives
+#            -extract        blank       extract timestep archieves
+#            -uda            [dir name]  uda name
+#            -help:                      Display this option summary
 #
 #
 #  It does not delete the original timestep directories. 
@@ -19,51 +25,112 @@
 unalias -a rm
 unalias -a cd
 
-#------------------
-# error checking
-if test "$#" -ne 3; then
-  echo ""
-  echo "Usage: pTarUda < number of Processors> <tar all timesteps in the uda (y/n) >  < uda> "
-  echo ""
-  exit 1
+#______________________________________________________________________
+# Parse input
+show_help=0
+if test $# -ne 7; then
+  echo "Wrong number of arguments ($#)."
+  show_help=1
 fi
 
+# command line arguments
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+  -np|--np)
+      shift
+      nproc="$1"
+      ;;
+  -allTimesteps|--allTimesteps)
+      shift
+      allTimesteps=${1^^}     # upper case trick
+    #  if test "$allTimesteps" != "Y" || "$allTimesteps" != "N" ; then
+    #    show_help=1
+    #  fi 
+      ;;
+  -uda|--uda)
+      shift
+      uda="$1"
+      ;;
+  -create|--create)
+      createExtract="create"
+      ;;
+  -extract|--extract)
+      createExtract="extract"
+      ;;    
+  -help|--help|-h)
+      show_help=1
+      ;;
+   *)
+      echo "$1: Unknown option, -help for help"
+      exit 1
+      ;;
+   esac
+   shift
+done
 
-# Need /usr/bin/which as the shell which doesn't give us the full path...
-if test ! -x /usr/bin/which; then
-  echo ""
-  echo "Error:  Can't find /usr/bin/which...  Goodbye."
-  echo ""
-  exit 1
+# usage string - exit
+if [ $show_help -ne 0 ]; then
+  cat <<EOF
+      It does not delete the original timestep directories. 
+
+      Options:
+          -np:            [int]       Number of processores used.
+          -allTimesteps:   [y/n]      operate on all directories in uda?  If "n" then a vi window will open allowing you to edit the timesteps
+          -create         blank       create new archives
+          -extract        blank       extract timestep archieves
+          -uda            [dir name]  uda name
+          -help:                      Display this option summary
+EOF
+  exit 0
 fi
+#__________________________________
 
-#pTarfulldir=`/usr/bin/which $0`
 pTarfulldir=`readlink -f $0`
 pTardir=`dirname $pTarfulldir`
 
-nproc=$1
-tarWholeUda=$2
-localDir=$3
-
-if test `echo $localDir | cut -c1` != "/"; then
+if test `echo $uda | cut -c1` != "/"; then
   # Not absolute path... fix it.
-  localDir=`pwd`/$localDir
+  uda=`pwd`/$uda
 fi
 
+#__________________________________
+#  Form the TAR command
+which pigz >& /dev/null                      # is the parallel version of gzip installed?
+rc=$?
 
-export PTAR_FILES=/tmp/ptar_files_`basename $localDir`_`whoami`
+if test $createExtract == "create"; then
+  if test "$rc" = "0"; then
+    TAR="tar  --use-compress-program 'pigz' -cBf"
+  else
+    TAR="tar --use-compress-program 'gzip' -cBf"
+  fi
+fi
 
+which unpigz >& /dev/null                      # is the parallel version of gunzip installed?
+rc=$?
+if test $createExtract == "extract"; then
+  if test "$rc" = "0"; then
+    TAR="tar  --use-compress-program 'unpigz' -xf"
+  else
+    TAR="tar --use-compress-program 'gunzip' -xf"
+  fi
+fi
+
+export TAR createExtract
+
+export PTAR_FILES=/tmp/ptar_files_`basename $uda`_`whoami`
 
 echo "_____________________________________"
 echo "Inputs:"
-echo "	login:                 $LOGIN"
 echo "	# processors:          $nproc"
-echo "	tar whole uda:         $tarWholeUda"
-echo "	localDir:              $localDir"
+echo "	allDirectories:        $allTimesteps"
+echo "	uda:                   $uda"
 echo "	PTAR_FILES:            $PTAR_FILES"
 echo "	pTardir:               $pTardir"
+echo "	tar command:           $TAR"
 echo "_____________________________________"
 echo ""
+
 #______________________________________________________________________
 # Bulletproofing
 echo "Bullet proof tests:"
@@ -96,14 +163,14 @@ validateTarredFilesDir()
   fi
 }
 
-export STAMP_DIR=$localDir/.tarred_files
+export STAMP_DIR=$uda/.tarred_files
 validateTarredFilesDir
 
 if test ! -d "$STAMP_DIR"; then
   # Didn't have permissions to make the directory... so place it in tmp
   echo ""
   echo "  WARNING: Was not able to create $STAMP_DIR directory (bad permissions?)."
-  export STAMP_DIR=/tmp/.tarred_files_`basename $localDir`_`whoami`
+  export STAMP_DIR=/tmp/.tarred_files_`basename $uda`_`whoami`
   echo "           Placing it in $STAMP_DIR instead."
   echo ""
   validateTarredFilesDir
@@ -115,18 +182,18 @@ if test ! -d "$STAMP_DIR"; then
   echo ""
 fi
 
-if test "$localDir" == "."; then
+if test "$uda" == "."; then
   echo ""
   echo "  ERROR: You can't set the local dir to '.'"
   echo ""
   exit 1
 fi
 
-echo -n "  Testing: does the local folder ($localDir) exist... "
-if test ! -e $localDir; then
+echo -n "  Testing: does the local folder ($uda) exist... "
+if test ! -e $uda; then
   echo ""
   echo ""
-  echo "  ERROR: Local directory '$localDir' does not exist"
+  echo "  ERROR: Local directory '$uda' does not exist"
   echo ""
   exit 1
 fi
@@ -144,7 +211,7 @@ echo "_____________________________________"
 #______________________________________________________________________
 # record some info for posterity
 
-PTAR_RECORD=$localDir/ptar_record
+PTAR_RECORD=$uda/ptar_record
 
 touch $PTAR_RECORD
 
@@ -155,10 +222,10 @@ fi
 
 echo "--------------------------------" >> $PTAR_RECORD
 echo "Started on `date`."               >> $PTAR_RECORD
-echo "Uda:  $localDir"                  >> $PTAR_RECORD
+echo "Uda:  $uda"                  >> $PTAR_RECORD
 echo ""                                 >> $PTAR_RECORD
 
-cd $localDir
+cd $uda
 
 #-------------------------------
 # make a sorted list of potential files to tar
@@ -166,16 +233,25 @@ cd $localDir
 /bin/rm -f $PTAR_FILES
 
 FIND=find
-$FIND .                -maxdepth 1 -type d  -exec basename {} \; | grep -v "\.\|t[0-9]\|checkpoints\|.tarred_files" >$PTAR_FILES
-$FIND ./t*             -maxdepth 0 -type d  -exec basename {} \; >>$PTAR_FILES
-$FIND ./checkpoints    -maxdepth 1 -type d  >>$PTAR_FILES
+
+if test $createExtract == "create"; then
+  $FIND .                -maxdepth 1 -type d  -exec basename {} \; | grep -v "\.\|t[0-9]\|checkpoints\|.tarred_files" >$PTAR_FILES
+  $FIND ./t*             -maxdepth 0 -type d  -exec basename {} \; >>$PTAR_FILES
+  $FIND ./checkpoints    -maxdepth 1 -type d  >>$PTAR_FILES
+fi
+if test $createExtract == "extract"; then
+  $FIND .                -maxdepth 1 -name "*.gz" -exec basename {} \; | grep -v "\.\|t[0-9]\|checkpoints\|.tarred_files" >$PTAR_FILES
+  $FIND ./t*             -maxdepth 0 -name "*.gz" -exec basename {} \; >>$PTAR_FILES
+  $FIND ./checkpoints    -maxdepth 1 -name "*.gz" >>$PTAR_FILES
+fi
+
 
 #remove "./checkpoints" from PTAR_FILES
 sed -i /".\/checkpoints$"/d $PTAR_FILES
 
 #more $PTAR_FILES
 
-if test "$tarWholeUda" == "n" -o "$tarWholeUda" == "N"; then
+if test "$allTimesteps" == "N"; then
   echo "Now starting an editor:  Remove the files you don't want transferred"
 
   if test ! $?EDITOR || test "$EDITOR" == ""; then
@@ -194,9 +270,11 @@ echo -n "Starting at: " | tee -a $PTAR_RECORD
 date | tee -a $PTAR_RECORD
 echo | tee -a $PTAR_RECORD
 
-/usr/bin/time -p $MAKE TAR=tar -s -f $pTardir/pTarUda_driver_$OS -j $nproc | tee -a $PTAR_RECORD
+/usr/bin/time -p $MAKE  -s -f $pTardir/pTarUda_driver_$OS -j $nproc | tee -a $PTAR_RECORD
 
 echo | tee -a $PTAR_RECORD
 echo -n "Ending at: " | tee -a $PTAR_RECORD
 date |tee -a $PTAR_RECORD
 echo
+
+exit 0
