This fixes the problem Todd was seeing with very large domains.
M    Core/Grid/Grid.cc

- Fix the problem with precision.  Before, for large numbers, adding epsilon 
    did not change the number (due to not enough precision).  See in-code
    comments explaining this fix.

- Alphabetize the #includes.

M    R_Tester/toplevel/startLocalTest

- Clean up (add white space) some of the error messages.
- Add the ability to point at a 'gold standard' TestData directory that is
    in a different location then the current directory.  To use this feature,
    set the TEST_DATA environment variable with an absolute path to the
    gold standard directory of choice.

M    R_Tester/toplevel/generateGoldStandards.py

- Clean up output message.

M    R_Tester/helpers/selectComponents.sh

- Print out a list of possible test components to make it easier for the user
    to set the TEST_COMPONENTS environment variable.

diff --git a/R_Tester/toplevel/startLocalTest b/R_Tester/toplevel/startLocalTest
--- a/R_Tester/toplevel/startLocalTest
+++ b/R_Tester/toplevel/startLocalTest
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /bin/bash
 
 #______________________________________________________________________
 #  startLocalTest:
@@ -35,7 +35,9 @@ IS_DEBUG_BUILD="$3"     # Will be 'yes', or 'no'
 SCI_MALLOC_ENABLED="$4" # Will be 'yes', or 'no'
 
 if [ ! -d "${BUILD_DIR}" ]; then
+  echo ""
   echo "ERROR: The build directory $BUILD_DIR does not exist.  Now exiting"
+  echo ""
   exit -1
 fi
 
@@ -43,6 +45,14 @@ cd "${BUILD_DIR}"
 
 if ! test ${TEST_DATA:+1}; then
   TEST_DATA="${BUILD_DIR}/TestData"
+else
+  if [ "${TEST_DATA:0:1}" != "/" ]; then
+    echo ""
+    echo "ERROR: Environment variable TEST_DATA must be an absolute path!"
+    echo "       (Ie: It must start with a '/'.)"
+    echo ""
+    exit -1
+  fi
 fi
 
 echo "Note: Using GoldStandards in:"
@@ -74,19 +84,24 @@ if [ ! -d inputs ]; then
   ln -s ${SRCTOP}/StandAlone/inputs inputs
 fi
 
-if [ -d goldStandard ]; then
+if [ -d goldStandard -o -L goldStandard ]; then
   rm -f goldStandard
 fi
 ln -s "${TEST_DATA}" goldStandard
 
 #__________________________________
 # bulletproofing
-if [ ! -d "$TEST_DATA" ]; then
+if ! test -d "$TEST_DATA"; then
+  echo ""
   echo "__________________________________"
+  echo ""
   echo "ERROR: gold standards directory doesn't exist: $TEST_DATA."
+  echo ""
   echo "Run the command:"
   echo "    make gold_standards"
-  echo " to generate them.  Now exiting"
+  echo "to generate them, or set the environment variable TEST_DATA to point to a valid Gold Standard directory."
+  echo ""
+  echo "Goodbye."
   echo "__________________________________"
   exit -1;
 fi
