added:
  -dbg_only
  -opt_only
   
options to the RT.

diff --git a/Packages/Uintah/R_Tester/helpers/runTests b/Packages/Uintah/R_Tester/helpers/runTests
--- a/Packages/Uintah/R_Tester/helpers/runTests
+++ b/Packages/Uintah/R_Tester/helpers/runTests
@@ -1,8 +1,10 @@
 #!/bin/sh
 
-# should have PATH, OS, PARALLELISM, TMPDIR, BUILD_DIR, VERBOSE,
+# should have the environmental variables:
+# PATH, OS, PARALLELISM, TMPDIR, BUILD_DIR, VERBOSE,
 # BUILDROOT, TEST_DATA, OPT_CONFIGURE,HTMLLOG,WEBLOG, DBG_CONFIGURE,
-# OPT_CONFIGURE, SEND_MAIL_TO, REPLY_TO  all set
+# OPT_CONFIGURE, SEND_MAIL_TO, REPLY_TO  DO_OPT DO_DBG all set
+
 PATH="$BUILDROOT"/src/Packages/Uintah/R_Tester/helpers:"$PATH":/usr/sbin
 export PATH OS MAKE_PARALLELISM PARALLELISM TMPDIR BUILD_DIR BUILDROOT TEST_DATA
 
@@ -28,7 +30,7 @@ rm -f "$BUILDROOT"/dbg/log "$BUILDROOT"/opt/log "$BUILDROOT"/dbg/summary_log "$B
 
 #__________________________________
 # if weekly tests, do not do dbg
-if [ "$WEEKLY" != "1" ]; then
+if [ "$WEEKLY" != "1" -a "$DO_DBG" == "1" ]; then
   WKLY_STRING=" "
   echo "" >> "$HTMLLOG"
   echo "/--------------------------\\" >> "$HTMLLOG"
@@ -55,37 +57,38 @@ fi
 
 #__________________________________
 # optimized
-echo "" >> "$HTMLLOG"
-echo "/--------------------------\\" >> "$HTMLLOG"
-echo "|  OPTIMIZED TEST SUMMARY   |" >> "$HTMLLOG"
-echo "\\--------------------------/" >> "$HTMLLOG"
-   
-# compile and run   
-if [ $VERBOSE = "yes" ]; then
-  build_and_run "opt" "$OPT_CONFIGURE"
-else
-  build_and_run "opt" "$OPT_CONFIGURE" > "$BUILDROOT"/opt/log 2>&1
+if [ "$DO_OPT" == "1" ]; then
+  echo "" >> "$HTMLLOG"
+  echo "/--------------------------\\" >> "$HTMLLOG"
+  echo "|  OPTIMIZED TEST SUMMARY   |" >> "$HTMLLOG"
+  echo "\\--------------------------/" >> "$HTMLLOG"
+
+  # compile and run   
+  if [ $VERBOSE = "yes" ]; then
+    build_and_run "opt" "$OPT_CONFIGURE"
+  else
+    build_and_run "opt" "$OPT_CONFIGURE" > "$BUILDROOT"/opt/log 2>&1
+  fi
+
+  retval=$?
+  if [ $retval != 0 ]; then
+    failed=1
+    opt_failed=1
+    opt_passFail="failed"
+  fi
+  echo "Optimized tests $opt_passFail!" >> "$HTMLLOG"
+
+
+  if [ $failed = "0" ]; then
+    echo "All tests passed!" >> "$BUILDROOT"/log
+    echo "All tests passed!" >> "$HTMLLOG"
+  fi
 fi
-
-retval=$?
-if [ $retval != 0 ]; then
-  failed=1
-  opt_failed=1
-  opt_passFail="failed"
-fi
-echo "Optimized tests $opt_passFail!" >> "$HTMLLOG"
-
-
-if [ $failed = "0" ]; then
-  echo "All tests passed!" >> "$BUILDROOT"/log
-  echo "All tests passed!" >> "$HTMLLOG"
-fi
-
 #__________________________________
 # Build the log that will be sent out in the email
 echo "" >> "$BUILDROOT"/log
 
-if [ "$WEEKLY" != "1" ]; then
+if [ "$WEEKLY" != "1" -a "$DO_DBG" == "1"]; then
   echo "/--------------------------\\" >> "$BUILDROOT"/log
   echo "| DEBUG TESTS - $dbg_passFail     |" >> "$BUILDROOT"/log
   echo "\\--------------------------/" >> "$BUILDROOT"/log
@@ -96,12 +99,14 @@ if [ "$WEEKLY" != "1" ]; then
   echo "" >> "$BUILDROOT"/log
 fi
 
-echo "/--------------------------\\" >> "$BUILDROOT"/log
-echo "| OPTIMIZED TESTS - $opt_passFail |" >> "$BUILDROOT"/log
-echo "\\--------------------------/" >> "$BUILDROOT"/log
-echo "" >> "$BUILDROOT"/log
+if [ "$DO_OPT" == "1" ]; then
+  echo "/--------------------------\\" >> "$BUILDROOT"/log
+  echo "| OPTIMIZED TESTS - $opt_passFail |" >> "$BUILDROOT"/log
+  echo "\\--------------------------/" >> "$BUILDROOT"/log
+  echo "" >> "$BUILDROOT"/log
 
-cat "$BUILDROOT"/opt/log >> "$BUILDROOT"/log
+  cat "$BUILDROOT"/opt/log >> "$BUILDROOT"/log
+fi
 
 echo "</pre></body></html>" >> "$HTMLLOG"
 echo "" >> "$BUILDROOT"/log
