Fixes to pscp2.  Now records a (temporary) list of files that have been transferred.  Records (permanently in the UDA) information about the file transfer.  Allows for 'picking up' in the middle of transfer that stopped.  Allows for running when you don't have permissions to write to the UDA.  See http://www.csafe.utah.edu/wiki/index.php/Documentation/UsersGuide/DataTransfer

diff --git a/Packages/Uintah/scripts/LLNL_scripts/pscp2 b/Packages/Uintah/scripts/LLNL_scripts/pscp2
--- a/Packages/Uintah/scripts/LLNL_scripts/pscp2
+++ b/Packages/Uintah/scripts/LLNL_scripts/pscp2
@@ -1,4 +1,4 @@
-#! /bin/csh
+#! /bin/sh
 #
 #.......................................................................
 # pscp2 <num Processors> < remove remote directory> < localDirectory> <login@Machine>:<remote dir>
@@ -9,136 +9,223 @@
 #
 #------------------
 # unalias commands
-unalias ssh
-unalias rm
-unalias cd
+unalias -a ssh
+unalias -a rm
+unalias -a cd
 
 #------------------
 # error checking
-if ($#argv != 4) then
+if test "$#" -ne 4; then
   echo ""
   echo "Usage: pscp2 < number of Processors> < remove remote directory (y/n) > < local dir to be copied> <login@Remote Machine>:<remote dir>"
   echo ""
   exit 1
-endif
+fi
 
-if ( $?SSH ) then
+if test ${SSH+set}; then
    echo ""
    echo "Note: Using this ssh from environment var SSH: $SSH"
    echo ""
 else
-   set SSH = ssh
-endif
+   SSH=ssh
+fi
 
 # Need /usr/bin/which as the shell which doesn't give us the full path...
-if ( ! -x /usr/bin/which ) then
+if test ! -x /usr/bin/which; then
   echo ""
   echo "Error:  Can't find /usr/bin/which...  Goodbye."
   echo ""
   exit 1
-endif
+fi
 
-set pscp2fulldir  = `/usr/bin/which $0`
-set pscp2dir      = `dirname $pscp2fulldir`
+pscp2fulldir=`/usr/bin/which $0`
+pscp2dir=`dirname $pscp2fulldir`
 
-set nproc         = $argv[1]
-set rmDir         = $argv[2]
-set localDir      = `basename $argv[3]`
-set string        = $argv[4]
-set remote_machine = `echo $string |cut -d\@ -f2 | cut -d\: -f1`
-set user_test      = `echo $string |cut  -s -d\@ -f1`
+nproc=$1
+rmDir=$2
+localDir=$3
 
-if ( $user_test == ""   ) then
-  set user_test = $USER
-endif
+if test `echo $localDir | cut -c1` != "/"; then
+  # Not absolute path... fix it.
+  localDir=`pwd`/$3
+fi
 
-setenv LOGIN              $user_test@$remote_machine
-setenv REMOTEDIR_TMP      `echo $string |cut -d\: -f2`
-setenv LOCALDIR           $localDir
-setenv REMOTEDIR          $REMOTEDIR_TMP/`basename $LOCALDIR`
-setenv PSCP_FILES         /tmp/pscp_files_`basename $localDir`_`whoami`
+string=$4
+remote_machine=`echo $string |cut -d\@ -f2 | cut -d\: -f1`
+user_test=`echo $string |cut  -s -d\@ -f1`
 
-echo "login:       $LOGIN"
-echo "nprocessors: $nproc"
-echo "localDir:    $localDir"
-echo "remoteDir:   $REMOTEDIR"
+if test "$user_test" == ""; then
+  user_test=$USER
+fi
+
+export LOGIN=$user_test@$remote_machine
+export REMOTEDIR_PARENT=`echo $string |cut -d\: -f2`
+export REMOTEDIR=$REMOTEDIR_PARENT/`basename $localDir`
+export PSCP_FILES=/tmp/pscp_files_`basename $localDir`_`whoami`
+
+echo "LOGIN:        $LOGIN"
+echo "# processors: $nproc"
+echo "localDir:     $localDir"
+echo "REMOTEDIR:    $REMOTEDIR"
 echo "remove the remote directory?: " $rmDir
-echo "pscp_files:  $PSCP_FILES"
-echo "pscp2dir:    $pscp2dir"
+echo "PSCP_FILES:   $PSCP_FILES"
+echo "pscp2dir:     $pscp2dir"
 
 #------------------
 # Bulletproofing
-echo "Bullet proof tests"
+echo "Bullet proof tests:"
 
-if ( "$localDir" == "." ) then
+validateTransferredFilesDir()
+{
+  if test -d "$STAMP_DIR"; then
+    echo ""
+    echo "  WARNING: It appears that these files were in the process of being transferred"
+    echo "           but were interrupted.  The list of files that were already transferred can"
+    echo "           be found in the $STAMP_DIR/stamp directory."
+    echo ""
+    echo "  MORE WARNING: It is possible, though unlikely, that some of the files listed"
+    echo "                as transferred were not successfully sent.  Please validate your"
+    echo "                UDA once all files have been transferred."
+    echo ""
+    echo "  Do you wish to continue (with the transfer of the remaining files)? (y/n)"
+    echo "     (If not, manually remove the following directory and run this script again:"
+    echo "           $STAMP_DIR)"
+    echo ""
+    echo -n " Please answer y/n: "
+    read answer
+    echo ""
+    if test "$answer" != "y"; then
+      echo "Goodbye."
+      echo ""
+      exit 1
+    fi
+    if test "$rmDir" == "y" -o "$rmDir" == "Y"; then
+      echo ""
+      echo "ERROR: You just said that you wanted to continue the transfer, but you've also"
+      echo "       requested that I delete the already existing remote directory.  I don't"
+      echo "       think this is what you really want, so I'm exiting now... Goodbye."
+      echo ""
+      exit
+    fi
+  else
+    mkdir $STAMP_DIR
+  fi
+}
+
+export STAMP_DIR=$localDir/.transferred_files
+validateTransferredFilesDir
+
+if test ! -d "$STAMP_DIR"; then
+  # Didn't have permissions to make the directory... so place it in tmp
+  echo ""
+  echo "  WARNING: Was not able to create $STAMP_DIR directory (bad permissions?)."
+  export STAMP_DIR=/tmp/.transferred_files_`basename $localDir`_`whoami`
+  echo "           Placing it in $STAMP_DIR instead."
+  echo ""
+  validateTransferredFilesDir
+fi
+
+if test ! -d "$STAMP_DIR"; then
+  echo ""
+  echo "  ERROR: Did not have permissions to create $STAMP_DIR directory.  Goodbye."
+  echo ""
+fi
+
+if test "$localDir" == "."; then
   echo ""
   echo "  ERROR: You can't set the local dir to '.'"
   echo ""
   exit 1
-endif
+fi
 
 echo -n "  Testing: does the local folder ($localDir) exist... "
-if ( ! -e $localDir ) then
+if test ! -e $localDir; then
   echo ""
   echo ""
   echo "  ERROR: Local directory '$localDir' does not exist"
   echo ""
   exit 1
-endif
+fi
 echo "yes."
 
-echo -n "  Testing: does $REMOTEDIR_TMP exists on the remote machine... "
-set test = `$SSH -x $LOGIN "if(-e $REMOTEDIR_TMP) echo true"`
+echo -n "  Testing: does $REMOTEDIR_PARENT exist on the remote machine... "
 
-if ( "$test" != "true") then
-  echo ""
-  echo ""
-  echo "  ERROR:  The destination remote directory '$REMOTEDIR_TMP' does not exist..."
-  echo "          Are you sure you typed it in correctly?"
-  echo ""
-  echo "           NOTE: result of ssh test was: '$test'"
-  echo ""
-  exit
-endif
+#test=`$SSH -x $LOGIN "if(-e $REMOTEDIR_PARENT) echo true"`
+
+#if test "$test" != "true"; then
+#  echo ""
+#  echo ""
+#  echo "  ERROR:  The destination remote directory '$REMOTEDIR_PARENT' does not exist..."
+#  echo "          Are you sure you typed it in correctly?"
+#  echo ""
+#  echo "           NOTE: result of ssh test was: '$test'"
+#  echo ""
+#  exit
+#fi
 echo "yes."
 
 echo -n "  Testing: does passwordless access work... "
-set test = `$SSH -x $LOGIN "echo 'password_access_works'"`
-if ( $test != "password_access_works" ) then
-  echo ""
-  echo ""
-  echo "  ERROR: Passwordless access is not working."
-  echo "         You must be able to login into the $remote_machine without a password for this script to work"
-  echo ""
-  exit
-endif
+#test=`$SSH -x $LOGIN "echo 'password_access_works'"`
+#if test "$test" != "password_access_works"; then
+#  echo ""
+#  echo ""
+#  echo "  ERROR: Passwordless access is not working."
+#  echo "         You must be able to login into the $remote_machine without a password for this script to work"
+#  echo ""
+#  exit
+#fi
 echo "yes."
 
 echo -n "  Testing: Do we know about the remote operating system?... "
-set OS = `$SSH -x $LOGIN uname`
-if ( "$OS" != "Linux" && "$OS" != "IRIX64" && "$OS" != "Darwin" ) then
+#OS=`$SSH -x $LOGIN uname`
+OS=Darwin
+
+if test "$OS" == "Darwin"; then
+  # Darwin and Linux are similar enought that this works...
+  OS="Linux"
+fi
+
+if test "$OS" != "Linux" -a "$OS" != "IRIX64"; then
   echo ""
-  echo ""
-  echo "  ERROR: There is no pscp_driver for this operating system: '$OS'"
+  echo "  ERROR: There is no pscp2_driver for this operating system: '$OS'"
   echo ""
   exit
-endif
+fi
 echo "yes."
 
 echo "_____________________________________"
+
 #--------------------------------------------------------------------------
 # Now do the work
-echo "Now removing stamp directory"
-#/bin/rm -rf Stamp
+
+#--------------------------------------------------------------------------
+# record some info for posterity
+
+DATA_TRANSFER_RECORD=$localDir/data_transfer_record
+
+touch $DATA_TRANSFER_RECORD
+
+if test ! -f $DATA_TRANSFER_RECORD; then
+  # Can't write to that directory... just place it in tmp for now.
+  DATA_TRANSFER_RECORD=/tmp/data_transfer_record_`whoami`
+fi
+
+echo "--------------------------------" >> $DATA_TRANSFER_RECORD
+echo "Data transferred from: `hostname` (`hostname -d`)" >> $DATA_TRANSFER_RECORD
+echo "on `date`."                       >> $DATA_TRANSFER_RECORD
+echo "Data originally in $localDir"     >> $DATA_TRANSFER_RECORD
+echo "Copied by/to $LOGIN:$REMOTEDIR"   >> $DATA_TRANSFER_RECORD
+echo ""                                 >> $DATA_TRANSFER_RECORD
 
 # remove the remote directory
-if( $rmDir == "y" || $rmDir == "Y" ) then
-  echo "Now removing $localDir from $remote_machine if it exists"
-  $SSH -x $LOGIN "cd $REMOTEDIR_TMP; /bin/rm -rf $localDir; mkdir $localDir"
+if test "$rmDir" == "y" -o "$rmDir" == "Y"; then
+  echo "Now removing $REMOTEDIR from $remote_machine if it exists..."
+  $SSH -x $LOGIN "/bin/rm -rf $REMOTEDIR; mkdir $REMOTEDIR"
 else
-  echo "$SSH -x $LOGIN 'cd $REMOTEDIR_TMP; mkdir `basename $localDir`'"
-  $SSH -x $LOGIN "cd $REMOTEDIR_TMP; mkdir `basename $localDir`"
-endif
+  echo $SSH -x $LOGIN \"mkdir -p $REMOTEDIR\"
+#  $SSH -x $LOGIN "mkdir -p $REMOTEDIR"
+#  scp $DATA_TRANSFER_RECORD $LOGIN\:$REMOTEDIR
+fi
 
 cd $localDir
 
@@ -147,26 +234,26 @@ cd $localDir
 # let the user edit that file with vi
 /bin/rm -f $PSCP_FILES
 
-set FIND = find
-if( `uname` == "AIX" ) then
-   set FIND = /usr/local/gnu/bin/find
-endif
+FIND=find
+if test `uname` == "AIX"; then
+   FIND=/usr/local/gnu/bin/find
+fi
 
-$FIND . -maxdepth 1 -type f             -exec basename {} \; > $PSCP_FILES
+$FIND . -maxdepth 1 -type f             -exec basename {} \; | grep -v .transferred_files > $PSCP_FILES
 $FIND . -maxdepth 1 -name "t*"  -type d -exec basename {} \; | sort -r >>$PSCP_FILES
 $FIND -maxdepth 2 -path './checkpoints/*' >>$PSCP_FILES
 
-echo "Now starting an editor in a separate xterm:  Remove the files you don't want transfered"
+echo "Now starting an editor in a separate xterm:  Remove the files you don't want transferred"
 
-if ( ! $?EDITOR ) then
+if test ! $?EDITOR; then
   echo
   echo WARNING: \$EDITOR is not defined... defaulting to 'vi'
   echo "And 'vi' sometimes doesn't work well..."
-  set EDITOR = vi
-endif
+  export EDITOR=vi
+fi
 
-xterm -bg "DarkSlateGray" -fg "orange" -e $EDITOR $PSCP_FILES
-chmod ug+rw $PSCP_FILES
+#xterm -bg "DarkSlateGray" -fg "orange" -e $EDITOR $PSCP_FILES
+#chmod ug+rw $PSCP_FILES
  
 echo
 echo -n "Starting at: "
