Changed it so that it will continue with regression testing if it fails to compile everything but it compiles sus.  Also, let it compile twice before it decides that it failed to compile (sometimes the compiler dies but if you compile again it works).

diff --git a/src/Packages/Uintah/Test/helpers/build_and_run b/src/Packages/Uintah/Test/helpers/build_and_run
--- a/src/Packages/Uintah/Test/helpers/build_and_run
+++ b/src/Packages/Uintah/Test/helpers/build_and_run
@@ -49,18 +49,35 @@ while [ ! -x "${BUILDROOT}/${mode}/build/Packages/Uintah/StandAlone/sus" ]; do
     nice gmake -k -j$MAKE_PARALLELISM >> ../make.log 2>&1
     retval=$?
     if [ $retval != "0" ]; then
-	echo "*** Make failed with code $retval"
-	echo ""
-	echo "Showing make errors:"
-	# show the compile errors (just the stuff it can't compile)
-	nice gmake -k -j$MAKE_PARALLELISM
-	echo ""
+	# try it again -- it may not go all the way the first time
+	echo "Failed first compile, try again"
+	nice gmake -k -j$MAKE_PARALLELISM >> ../make.log 2>&1
+	retval=$?
+    fi
+    if [ $retval != "0" ]; then
+	nice gmake -k -j$MAKE_PARALLELISM > ../remake.log 2>&1
+	
+	if  [ -x "${BUILDROOT}/${mode}/build/Packages/Uintah/StandAlone/sus" ];
+	    echo "*** Make failed, but sus was compiled successfully"
+	    echo "A log of build errors can be found in"
+	    echo "${BUILDROOT}/${mode}/remake.log"
+	    echo "A full log of trying to compile everything twice can be found in"
+	    echo "${BUILDROOT}/${mode}/make.log"
+	    echo ""
+	else
+	    echo "*** Make failed with code $retval"
+	    echo ""
+	    echo "Showing make errors:"
+	    # show the compile errors (just the stuff it can't compile)
+	    cat ../remake.log
+	    echo ""
 
-	# failed make, set a lock for this build
-	if [ ! -d "${BUILD_DIR}/make-${mode}.lock" ]; then
-	    ln -s "$BUILDROOT" "${BUILD_DIR}/make-${mode}.lock"
+	    # failed make, set a lock for this build
+	    if [ ! -d "${BUILD_DIR}/make-${mode}.lock" ]; then
+		ln -s "$BUILDROOT" "${BUILD_DIR}/make-${mode}.lock"
+	    fi
+	    exit 1
 	fi
-	exit 1
     fi
 done
 
