Check to make sure that the malloc_stats file was created.

diff --git a/src/Packages/Uintah/Test/helpers/mem_leak_check b/src/Packages/Uintah/Test/helpers/mem_leak_check
--- a/src/Packages/Uintah/Test/helpers/mem_leak_check
+++ b/src/Packages/Uintah/Test/helpers/mem_leak_check
@@ -5,6 +5,11 @@ MALLOC_STATS=$2
 TMPDIR=$3
 ERRORS_TO=$4
 
+if [ ! -f $MALLOC_STATS ]; then
+    echo "No malloc_stats output found.  Can't do memory leak test."
+    exit 5
+fi
+
 grep 'src' $MALLOC_STATS > $TMPDIR/scinew_malloc_stats
 retval=$?
 
