Set the permisions of the gold standard directory to allow csafe write access

diff --git a/src/Packages/Uintah/Test/helpers/replace_gold_standard b/src/Packages/Uintah/Test/helpers/replace_gold_standard
--- a/src/Packages/Uintah/Test/helpers/replace_gold_standard
+++ b/src/Packages/Uintah/Test/helpers/replace_gold_standard
@@ -43,6 +43,19 @@ if [ $yesno == "y" -o $yesno == "yes" ]; then
     echo "failed"
     exit 1
   fi
+  echo "/bin/chgrp -Rh csafe $replacement_dir/$testname"
+  /bin/chgrp -Rh csafe "$replacement_dir/$testname"
+  if [ $? != "0" ]; then
+    echo "failed"
+    exit 1
+  fi
+  echo "/bin/chmod -R g+ws $replacement_dir/$testname"
+  /bin/chmod -R g+ws "$replacement_dir/$testname"
+  if [ $? != "0" ]; then
+    echo "failed"
+    exit 1
+  fi
+
   echo
   echo "Gold Standard successfully replaced!"
 else
