user can now just replace the checkpoints directory

diff --git a/src/Packages/Uintah/Test/helpers/replace_gold_standard b/src/Packages/Uintah/Test/helpers/replace_gold_standard
--- a/src/Packages/Uintah/Test/helpers/replace_gold_standard
+++ b/src/Packages/Uintah/Test/helpers/replace_gold_standard
@@ -15,6 +15,7 @@ do_uda="false"
 do_mem="false"
 do_perf="false"
 do_input="false"
+do_checkpoint="false"
 
 # prompt for and replace udas
 if [ $# -ne 3 -a $# -ne 4 ]; then
@@ -68,6 +69,48 @@ else
     fi
   else
     echo "udas not replaced"
+  fi
+fi
+#__________________________________
+# replace only the checkpoints
+if [ ! -d $replacement_dir/$testname/*.uda/checkpoints -o "$force" = "-m" ]; then
+  echo "No checkpoints to replace, or not replacing them"
+else
+
+  if [ "$force" = "-f" -a "$do_uda" = "false" ]; then
+    yesno="yes"
+  else
+    echo "Replace the checkpoints? (Enter 'yes' or 'y' to continue.) "
+    read yesno
+  fi
+  
+  # remove the udas, and copy the new ones
+  if [ $yesno = "y" -o $yesno = "yes" ]; then
+    do_checkpoint="true"
+    failcode="0"
+    echo -n "Replacing $testname udas ... "
+    rm -rf $gold_standard_dir/$testname/*.uda/checkpoints
+    if [ $? != "0" ]; then
+      failcode="1"
+      echo "$testname checkpoint replacement failed - could not remove old checkpoint directory"
+    fi
+
+    # if it has a --dereference option, then use it
+    cp -r --dereference $replacement_dir/$testname/*.uda/checkpoints $gold_standard_dir/$testname/*.uda/. > /dev/null 2>&1
+
+    # sometimes it doesn't work with --dereference...
+    if [ $? != "0" ]; then
+      cp -r $replacement_dir/$testname/*.uda/checkpoints $gold_standard_dir/$testname/*.uda/.
+      if [ $? != "0" ]; then
+        failcode="1"
+	echo "$testname checkpoint replacement failed - could not copy the new checkpoint"
+      fi
+    fi
+    if [ "$failcode" = "0" ]; then
+      echo "checkpoint successfully replaced"
+    fi
+  else
+    echo "checkpoint not replaced"
   fi
 fi
 #__________________________________
@@ -143,7 +186,7 @@ fi
 
 #__________________________________
 # LOG FILE
-if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_input" = "true" ]; then
+if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_input" = "true" -o "$do_checkpoint" = "true" ]; then
   # make a log
   if [ ! -f $logfile ]; then
     echo "Replacement log for $gold_standard_dir/$testname" >> $logfile
@@ -153,6 +196,9 @@ if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_inp
   echo -n "`date`: user $user " >> $logfile
   if [ "$do_uda" = "true" ]; then
     echo -n "replaced uda" >> $logfile
+  fi
+  if [ "$do_checkpoint" = "true" ]; then
+    echo -n "replaced checkpoints" >> $logfile
   fi
   if [ "$do_mem" = "true" ]; then
     if [ "$do_uda" = "true" ]; then
