Complete mirror of the Uintah trunk as of 39317, with files passed through a filter to adjust includes and rename UTextureBuilder's parent correctly.
This version leaves Dataflow in its place in Uintah, and there are CMake/SCIRun hooks to look in the right place instead of in SCIRun/Packages/Uintah/Dataflow, and as such leaves us responsible to create the tclIndex.

diff --git a/trunk/src/scripts/LLNL_scripts/pscp2 b/trunk/src/scripts/LLNL_scripts/pscp2
--- a/trunk/src/scripts/LLNL_scripts/pscp2
+++ b/trunk/src/scripts/LLNL_scripts/pscp2
@@ -1,4 +1,4 @@
-#!/bin/csh
+#! /bin/csh
 #
 #.......................................................................
 # pscp2 <num Processors> < remove remote directory> < localDirectory> <login@Machine>:<remote dir>
@@ -20,6 +20,7 @@ if ($#argv != 4) then
   exit(0)
 endif
 
+set pscp2dir      = `dirname $0`
 set nproc         = $argv[1]
 set rmDir         = $argv[2]
 set localDir      = $argv[3]
@@ -34,39 +35,65 @@ endif
 setenv LOGIN              $user_test@$remote_machine
 setenv REMOTEDIR_TMP      `echo $string |cut -d\: -f2`
 setenv LOCALDIR           $localDir
-setenv REMOTEDIR          $REMOTEDIR_TMP/$LOCALDIR
-setenv PSCP_FILES         /tmp/pscp_files_$localDir
+setenv REMOTEDIR          $REMOTEDIR_TMP/`basename $LOCALDIR`
+setenv PSCP_FILES         /tmp/pscp_files_`basename $localDir`_`whoami`
 
 echo "login:       $LOGIN"
 echo "nprocessors: $nproc"
 echo "localDir:    $localDir"
 echo "remoteDir:   $REMOTEDIR"
-echo "removing the remote directory: " $rmDir
+echo "remove the remote directory?: " $rmDir
+echo "pscp_files:  $PSCP_FILES"
+echo "pscp2dir:    $pscp2dir"
 
 #------------------
 # Bulletproofing
 echo "Bullet proof tests"
 
+if ( "$localDir" == "." ) then
+  echo ""
+  echo "  ERROR: You can't set the local dir to '.'"
+  echo ""
+  exit 1
+endif
+
 echo "  Test: does the local folder ($localDir) exist"
 if ( ! -e $localDir ) then
-  echo " ERROR: local directory $localDir doesn't exist"
-  exit(1)
+  echo ""
+  echo "  ERROR: Local directory $localDir doesn't exist"
+  echo ""
+  exit 1
 endif
 
-echo "  Test: passwordless access."
+echo "  Test: does $REMOTEDIR_TMP exists on the remote machine"
+set test = `ssh -x $LOGIN "if(-e $REMOTEDIR_TMP) echo true"`
+if ( $test != "true") then
+  echo ""
+  echo "  ERROR:  The destination remote directory '$REMOTEDIR_TMP' does not exist..."
+  echo "          Are you sure you typed it in correctly?"
+  echo ""
+  exit
+endif
+
+echo "  Test: passwordless access..."
 set test = `ssh -x $LOGIN "echo 'password_access_works'"`
 if ( $test != "password_access_works" ) then
-  echo " ERROR:  passwordless access is not working."
+  echo ""
+  echo "  ERROR: Passwordless access is not working."
   echo "         You must be able to login into the $remote_machine without a password for this script to work"
-  exit(1)
+  echo ""
+  exit
 endif
 
-echo "  Test: Do we know about the remote operating system"
+echo "  Test: Do we know about the remote operating system?"
 set OS = `ssh -x $LOGIN uname`
 if ( $OS != "Linux" && $OS != "IRIX64" ) then
-  echo " ERROR: there is no pscp_driver for this operating system: $OS"
-  exit(1)
+  echo ""
+  echo "  ERROR: There is no pscp_driver for this operating system: $OS"
+  echo ""
+  exit
 endif
+
 echo "_____________________________________"
 #--------------------------------------------------------------------------
 # Now do the work
@@ -78,7 +105,8 @@ if( $rmDir == "y" || $rmDir == "Y" ) then
   echo "Now removing $localDir from $remote_machine if it exists"
   ssh -x $LOGIN "cd $REMOTEDIR_TMP; /bin/rm -rf $localDir; mkdir $localDir"
 else
-  ssh -x $LOGIN "cd $REMOTEDIR_TMP; mkdir $localDir"
+  echo "ssh -x $LOGIN 'cd $REMOTEDIR_TMP; mkdir `basename $localDir`'"
+  ssh -x $LOGIN "cd $REMOTEDIR_TMP; mkdir `basename $localDir`"
 endif
 
 cd $localDir
@@ -88,15 +116,25 @@ cd $localDir
 # let the user edit that file with vi
 /bin/rm -f $PSCP_FILES
 
-find . -maxdepth 1 -type f             -exec basename {} \; > $PSCP_FILES
-find . -maxdepth 1 -name "t*"  -type d -exec basename {} \; | sort -r >>$PSCP_FILES
-find . -maxdepth 1 -name "checkpoints" -exec basename {} \; >> $PSCP_FILES
+set FIND = find
+if( `uname` == "AIX" ) then
+   set FIND = /usr/local/gnu/bin/find
+endif
 
-echo "Now starting vi in a separate xterm:  Remove the files you don't want transfered"
-xterm -bg "DarkSlateGray" -fg "orange" -e "vi $PSCP_FILES"
+$FIND . -maxdepth 1 -type f             -exec basename {} \; > $PSCP_FILES
+$FIND . -maxdepth 1 -name "t*"  -type d -exec basename {} \; | sort -r >>$PSCP_FILES
+$FIND -path './checkpoints/*' -maxdepth 2 >>$PSCP_FILES
+
+echo "Now starting an editor in a separate xterm:  Remove the files you don't want transfered"
+
+if ( ! $?EDITOR ) then
+  echo
+  echo WARNING: \$EDITOR is not defined... defaulting to 'vi'
+  echo "And 'vi' sometimes doesn't work well..."
+  set EDITOR = vi
+endif
+
+xterm -bg "DarkSlateGray" -fg "orange" -e $EDITOR $PSCP_FILES
 chmod ug+rw $PSCP_FILES
  
-/usr/bin/time -p gmake TAR=tar -f /usr/gapps/uintah/scripts/pscp2_driver_$OS -j $nproc
-
-cd ..
-exit(1)
+/usr/bin/time -p gmake TAR=tar -f $pscp2dir/pscp2_driver_$OS -j $nproc
diff --git a/trunk/src/scripts/LLNL_scripts/pscp_pull b/trunk/src/scripts/LLNL_scripts/pscp_pull
--- a/trunk/src/scripts/LLNL_scripts/pscp_pull
+++ b/trunk/src/scripts/LLNL_scripts/pscp_pull
@@ -1,13 +1,16 @@
-#!/bin/csh
+#! /bin/csh
 #
 #.......................................................................
 # pscp
+#
 # pscp <num Processors>  <login@Machine>:<remote dir> < localDirectory>
 # You must be able to ssh onto the remote machine without a password
-# or it won't work.
+# or it won't work... On some systems (Redstorm) you may need to use 
+# a different 'ssh'... You may set the SSH environment variable to this
+# ssh (eg: setenv SSH rssh) to use the specified SSH.
+# 
 #.......................................................................
-#echo $argv
-#
+
 #------------------
 # unalias commands
 unalias ssh
@@ -16,64 +19,158 @@ unalias cd
 
 #------------------
 # error checking
-if ($#argv != 3) then
-  echo " pscp < number of Processors>  <login@Remote Machine>:<remote dir> < local dir>"
-  exit(0)
+if ($#argv != 3 && $#argv != 4 && $#argv != 5 ) then
+  echo ""
+  echo "Error: Wrong number of args..."
+  echo ""
+  echo "Usage: pscp [-v] [-verify] <# of Processors> <login@Remote Machine>:<remote dir> <local dir>"
+  echo ""
+  echo "             -v - optional verbose flag"
+  echo ""
+  echo "             -verify  verify data that has already been received"
+  echo ""
+  echo "       [Note, you can setenv SSH to use a specific 'ssh' if necessary."
+  echo ""
+  exit 0
+endif
+
+set beVerbose = false
+if ($argv[1] == "-v") then
+  set beVerbose = true
+  shift
+endif
+
+set verifyData = false
+if ($argv[1] == "-verify") then
+  set verifyData = true
+  shift
 endif
 
 set nproc         = $argv[1]
+set mac_and_dir   = $argv[2]
 set localDir      = $argv[3]
-set string        = $argv[2]
-set remote_machine = `echo $string |cut -d\@ -f2 | cut -d\: -f1`
-set user_test      = `echo $string |cut  -s -d\@ -f1`
 
-if ( $user_test == ""   ) then
+set remote_machine = `echo $mac_and_dir |cut -d\@ -f2 | cut -d\: -f1`
+set user_test      = `echo $mac_and_dir |cut  -s -d\@ -f1`
+
+if ( $user_test == "" ) then
   set user_test = $USER
 endif
 
 setenv LOGIN              $user_test@$remote_machine
-setenv REMOTEDIR_TMP      `echo $string |cut -d\: -f2`
+setenv REMOTEDIR_TMP      `echo $mac_and_dir |cut -d\: -f2`
 setenv LOCALDIR           $localDir
 setenv REMOTEDIR          $REMOTEDIR_TMP
 
-echo "login:       $LOGIN"
-echo "nprocessors: $nproc"
-echo "localDir:    $localDir"
-echo "remoteDir:   $REMOTEDIR"
+if( $beVerbose == "true" ) then
+  echo ""
+  echo "Basic settings:"
+  echo ""
+  echo "login:       $LOGIN"
+  echo "nprocessors: $nproc"
+  echo "localDir:    $localDir"
+  echo "remoteDir:   $REMOTEDIR"
+  echo ""
+  if( $verifyData == "true") then
+    echo "Data will be verified"
+  endif
+endif
 
 #------------------
 # Bulletproofing
-echo "Bullet proof tests"
 
-echo "  Test: does the local folder ($localDir) exist"
+echo ""
+echo "Running Bulletproofing tests..."
+echo ""
+
+if( $beVerbose == "true" ) then
+  echo "Verify pscp_pull_driver exists..."
+endif
+
+set PSCP_PULL_DRIVER = `dirname $0`/pscp_pull_driver
+if( ! -e $PSCP_PULL_DRIVER ) then
+  echo ""
+  echo "ERROR: pscp_pull_driver ('$PSCP_PULL_DRIVER') not found... Goodbye."
+  echo ""
+  exit 1
+endif
+
+if( $beVerbose == "true" && $verifyData == "true") then
+  set DATAVERIFY_PULL_DRIVER = `dirname $0`/dataVerify_pull_driver
+  if( ! -e $PSCP_PULL_DRIVER ) then
+    echo ""
+    echo "ERROR: dataVerify_pull_driver ('$DATAVERIFY_PULL_DRIVER') not found... Goodbye."
+    echo ""
+    exit 1
+  endif
+endif
+
+
+
+if( $beVerbose == "true" ) then
+  echo "Verify local directory..."
+endif
+
 if ( ! -e $localDir ) then
-  echo " ERROR: local directory $localDir doesn't exist"
-  exit(1)
+  echo ""
+  echo "ERROR: Local directory '$localDir' does not exist."
+  echo "       Please create it... Goodbye."
+  echo ""
+  exit 1
 endif
 
-echo "  Test: passwordless access."
-set test = `ssh -x $LOGIN "echo 'password_access_works'"`
+if( $beVerbose == "true" ) then
+  echo "Verify password'less access..."
+endif
+
+if( ! $?SSH ) then
+  setenv SSH ssh
+endif
+
+if( $beVerbose == "true" ) then
+  echo "Using SSH of $SSH"
+endif
+
+set test = `$SSH -x $LOGIN "echo 'password_access_works'"`
+
 if ( $test != "password_access_works" ) then
-  echo " ERROR:  passwordless access is not working."
-  echo "         You must be able to login into the $remote_machine without a password for this script to work"
-  exit(1)
+  echo ""
+  echo "ERROR:  Password-less access is not working. You must be able to login"
+  echo "        into '$remote_machine' without a password for this script to work..."
+  echo "        Goodbye."
+  echo ""
+  exit 1
 endif
 
-echo "  Test: Do we know about the remote operating system"
-set OS = `ssh -x $LOGIN uname`
-if ( $OS != "Linux" && $OS != "IRIX64" ) then
-  echo " ERROR: there is no pscp_driver for this operating system: $OS"
-  exit(1)
+if( $beVerbose == "true" ) then
+  echo "Verify remote directory..."
 endif
-echo "_____________________________________"
+
+set REMOTE_DIR_VALID = `$SSH $LOGIN "if ( -d $REMOTEDIR ) echo yes"`
+
+if ( $REMOTE_DIR_VALID != "yes" ) then
+  echo ""
+  echo "ERROR: Remote directory '$REMOTEDIR' does not appear to exist."
+  echo "       Please verify that you have the correct path.  Goodbye."
+  echo ""
+  echo "       (If it does, it is possible that the problem is you don't run csh"
+  echo "        on the remote machine... if this is the case, contact Dav.)"
+  echo ""
+  exit 1
+endif
+
 #------------------
 # Now do the work
-echo "Now removing stamp directory"
-/bin/rm -rf Stamp
-mkdir $localDir
-cd $localDir
 
-/usr/bin/time -p gmake -f /usr/gapps/uintah/scripts/pscp_pull_driver -j $nproc
+echo ""
+echo "Fetch the data..."
+echo ""
 
-cd ..
-exit(1)
+if( $verifyData == "true") then
+  /usr/bin/time -p gmake -f $DATAVERIFY_PULL_DRIVER -j $nproc
+else
+  /usr/bin/time -p gmake -f $PSCP_PULL_DRIVER -j $nproc
+endif
+echo ""
+echo "Done..."
+echo ""
