Avoid problems caused by case-insensitive file systems when checking for existence of packages in src/Packages/ directory.

diff --git a/v1_24_0/src/configure b/v1_24_0/src/configure
--- a/v1_24_0/src/configure
+++ b/v1_24_0/src/configure
@@ -2962,9 +2962,19 @@ esac
   fi
 fi
 
+# Make sure the Package directories exist.
+#   Do an 'ls' of all files in the Packages directory and then grep for the
+#   package in this list.  (We used to just do a "test -d $package", but on
+#   a case-insensitive Mac file system, this fails.)
+
+packages_list=`ls $path_to_src/Packages`
 for i in $package; do
-   # Make sure the Package directories exist.
-   if test ! -d "$path_to_src/Packages/$i"; then
+   found_package=`echo $packages_list | grep $i`
+   if test -z "$found_package"; then
+      if test "$i" = "TEEM"; then
+         { echo "$as_me:$LINENO: WARNING: Try using 'Teem' instead of 'TEEM'" >&5
+echo "$as_me: WARNING: Try using 'Teem' instead of 'TEEM'" >&2;}
+      fi
       { { echo "$as_me:$LINENO: error: Package '$i' does not exist (in $path_to_src/Packages/)!" >&5
 echo "$as_me: error: Package '$i' does not exist (in $path_to_src/Packages/)!" >&2;}
    { (exit 1); exit 1; }; }
@@ -4470,7 +4480,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4473:" \
+echo "$as_me:4483:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
