Check for make fila

diff --git a/build_scripts/Wasatch3PStandalone/SpatialOps-build/doit b/build_scripts/Wasatch3PStandalone/SpatialOps-build/doit
--- a/build_scripts/Wasatch3PStandalone/SpatialOps-build/doit
+++ b/build_scripts/Wasatch3PStandalone/SpatialOps-build/doit
@@ -29,6 +29,14 @@ if test $? == 0; then
   echo ""
   make clean
   make -j4
+
+  if test $? != 0; then
+    echo ""
+    echo "SpatialOps make failed...  Goodbye."
+    echo ""
+    exit -1
+  fi
+
   make install
 
   echo ""
