build_and_run   - if the code didn't compile OR if "NOTESTS" has been choosen then exit script.   - eliminated 2 extra conditional statements.   - moved the loop over all componentTests to this script.
run
  - removed loop over all componentTests.  This script is only designed to run
    a single component tests.
  - added bulletproofing on required environmental variables.

diff --git a/src/R_Tester/helpers/build_and_run b/src/R_Tester/helpers/build_and_run
--- a/src/R_Tester/helpers/build_and_run
+++ b/src/R_Tester/helpers/build_and_run
@@ -6,7 +6,7 @@
 # $BUILD_DIR $BUILDROOT, $HTMLLOG, $NOTESTS, $PARALLELISM, $COMPILE, and $MAKE_PARALLELISM must be set
 
 mode=$1 # dbg or opt
-retval=0
+didCompile=0
 
 #__________________________________
 #  Create the build directory and compile the code.
@@ -19,7 +19,7 @@ if [ "$COMPILE" = "yes" ]; then
 
   # configure and compile the code
   build $mode
-  retval=$?
+  didCompile=$?
   
   #change the permissions
   echo "Changing permissions in `pwd`"
@@ -27,62 +27,90 @@ if [ "$COMPILE" = "yes" ]; then
   chmod -R g+rwX . 
 fi
 
+# exit if compile failed or there no tests to run
+if [ "$didCompile" != "0" -a "$NOTESTS" = "0" ]; then
+  exit $didCompile
+fi
+
+
 #__________________________________
 # If the code compiled successfully
 #    - generate the symbolic links
 #    - check for the goldStandards
-if [ "$retval" = "0" -a "$NOTESTS" = "0" ]; then
-  cd "${BUILDROOT}/${mode}"
+cd "${BUILDROOT}/${mode}"
 
-  if [ ! -d TestScripts ]; then
-    ln -s ../src/R_Tester TestScripts
-  fi
+if [ ! -d TestScripts ]; then
+  ln -s ../src/R_Tester TestScripts
+fi
 
-  if [ ! -f replace_all_GS ]; then
-    ln -s ../src/R_Tester/helpers/replace_all_GS replace_all_GS
-  fi
+if [ ! -f replace_all_GS ]; then
+  ln -s ../src/R_Tester/helpers/replace_all_GS replace_all_GS
+fi
 
-  if [ ! -d susdir ]; then
-    ln -s build/StandAlone susdir
-  fi
+if [ ! -d susdir ]; then
+  ln -s build/StandAlone susdir
+fi
 
-  if [ ! -d inputs ]; then
-    ln -s ../src/StandAlone/inputs inputs
-  fi
+if [ ! -d inputs ]; then
+  ln -s ../src/StandAlone/inputs inputs
+fi
 
-  if [ ! -d CheckPoints ]; then
-    ln -s /usr/local/home/csafe-tester/CheckPoints CheckPoints
-  fi
+if [ ! -d CheckPoints ]; then
+  ln -s /usr/local/home/csafe-tester/CheckPoints CheckPoints
+fi
 
-  # remove this in case it points to the wrong place
-  if [ -d goldStandard ]; then
-    rm -f goldStandard
-  fi
-  ln -s "${TEST_DATA}/${mode}" goldStandard
+# remove this in case it points to the wrong place
+if [ -d goldStandard ]; then
+  rm -f goldStandard
+fi
+ln -s "${TEST_DATA}/${mode}" goldStandard
 
-  summary_log="${BUILDROOT}/${mode}/summary_log"
-  rm -f $summary_log
-  
+summary_log="${BUILDROOT}/${mode}/summary_log"
+rm -f $summary_log
 
-  # checking for GoldStandards
-  if [ ! -d "$TEST_DATA" ]; then
-    echo "TEST_DATA directory doesn't exist: $TEST_DATA"
-    exit -1;
-  fi
 
-  if [ ! -d "${TEST_DATA}/${mode}" ]; then
-    mkdir "${TEST_DATA}/${mode}"
-  fi
+# checking for GoldStandards
+if [ ! -d "$TEST_DATA" ]; then
+  echo "TEST_DATA directory doesn't exist: $TEST_DATA"
+  exit -1;
+fi
+
+if [ ! -d "${TEST_DATA}/${mode}" ]; then
+  mkdir "${TEST_DATA}/${mode}"
 fi
 
 
 #__________________________________
-#  Run the component tests
-if [ "$retval" = "0" -a "$NOTESTS" = "0" ]; then
-  run $1
-  retval=$?
-#  chmod -R a+rX "$HTMLLOG"-"$mode"
-  exit $retval
+#  Run the all component tests
+
+cd TestScripts
+failed=0
+
+# find all the component tests which are python scripts
+componentTests=`file * | grep python | cut -d: -f1`
+
+#  main loop over components RT tests
+for componentTest in $componentTests; do
+  # if the file is an executable
+  if [ -f "$componentTest" -a -x "$componentTest" ]; then
+
+    #echo ""
+    #echo "Running test \"${componentTest}-${mode}\" at `date`"
+    run $mode $componentTest
+    retval=$?
+
+    if [ $retval = "1" ]; then
+      failed=1
+    fi
+  fi
+done
+
+echo ""
+echo "Finished $mode tests on `date`"
+if [ $failed = "0" ]; then
+  echo "All $mode tests passed!"
 else
-  exit $retval
+  echo "*** Some $mode tests failed."
 fi
+
+exit $failed
diff --git a/src/R_Tester/helpers/run b/src/R_Tester/helpers/run
--- a/src/R_Tester/helpers/run
+++ b/src/R_Tester/helpers/run
@@ -2,82 +2,69 @@
 #!/bin/sh#
 #______________________________________________________________________
 # run:  This shell script
-#         - Loop over all the components tests
+#         - runs a component's test
 #         - set locks if a component's tests fails.
-# $TEST_DATA, $BUILD_DIR $BUILDROOT, $mode, $HTMLLOG, $PARALLELISM, and $MAKE_PARALLELISM must be set
+# environmental Variables: $OS $BUILD_DIR, $BUILDROOT, $HTMLLOG, $PARALLELISM, $WEBLOG
 
 mode=$1
+componentTest=$2
 failed=0
+
+#__________________________________
+# bulletproof the inputs
+if [ "$BUILDROOT" = "" -o "$PARALLELISM" = "" -o "$OS" = "" ]; then
+  echo "ERROR:run  One of the environmental variables (BUILDROOT, PARALLELISM, OS) has not been set"
+  exit -1
+fi
+
+
+#__________________________________
+# create the do<component>tests  python script
+cd "${BUILDROOT}/${mode}"
+doTestScript="do${componentTest}tests"
+echo "#!/bin/tcsh" > "$doTestScript"
+echo "setenv PATH $PATH" >> "$doTestScript"
+echo "setenv OS $OS" >> "$doTestScript"
+echo "setenv SCI_DEBUG \"\"" >> "$doTestScript"
+
+echo "python TestScripts/$componentTest susdir inputs goldStandard $mode $PARALLELISM "'$1' >> "$doTestScript"
+
+/bin/chmod a+x "$doTestScript"
+
+#__________________________________
+# run the python script that contains all the
+# tests for that component
+rm -f "${BUILDROOT}/${mode}/${componentTest}-short.log"
+"$doTestScript" > "${componentTest}.log"  2>&1
+retval=$?
+
+cat "${componentTest}.log" >> "$summary_log"
+cat "${componentTest}.log" >> "$HTMLLOG"
 
 cd TestScripts
 
-# find all the component tests which are python scripts
-componentTests=`file * | grep python | cut -d: -f1`
-
 #__________________________________
-#  main loop over components RT tests
-for componentTest in $componentTests; do
-  # if the file is an executable
-  if [ -f "$componentTest" -a -x "$componentTest" ]; then
+# Setting or removing component locks
+if [ $retval = "0" ]; then
+  echo "Passed: ${componentTest}-${mode} tests! "
 
-    #echo ""
-    #echo "Running test \"${componentTest}-${mode}\" at `date`"
-    #__________________________________
-    # create the do<component>tests  python script
-    cd "${BUILDROOT}/${mode}"
-    doTestScript="do${componentTest}tests"
-    echo "#!/bin/tcsh" > "$doTestScript"
-    echo "setenv PATH $PATH" >> "$doTestScript"
-    echo "setenv OS $OS" >> "$doTestScript"
-    echo "setenv SCI_DEBUG \"\"" >> "$doTestScript"
-
-    echo "python TestScripts/$componentTest susdir inputs goldStandard $mode $PARALLELISM "'$1' >> "$doTestScript"
- 
-    /bin/chmod a+x "$doTestScript"
-    
-    #__________________________________
-    # run the python script that contains all the
-    # tests for that component
-    rm -f "${BUILDROOT}/${mode}/${componentTest}-short.log"
-    "$doTestScript" > "${componentTest}.log"  2>&1
-    retval=$?
-    
-    cat "${componentTest}.log" >> "$summary_log"
-    cat "${componentTest}.log" >> "$HTMLLOG"
-    
-    cd TestScripts
-
-    #__________________________________
-    # Setting or removing component locks
-    if [ $retval = "0" ]; then
-      echo "Passed: ${componentTest}-${mode} tests! "
- 
-      # It was successful, so it can remove the lock
-      if [ -d "${BUILD_DIR}/${componentTest}-${mode}.lock" ]; then
-          rm "${BUILD_DIR}/${componentTest}-${mode}.lock"
-      fi
-    elif [ $retval = "3" ]; then
-      echo "Skipped: ${componentTest}-$mode tests"
-    else
-      echo "Failed: ${componentTest}-${mode} tests"
-      if [ ! -d "${BUILD_DIR}/${componentTest}-${mode}.lock" ]; then
-        ln -s "$BUILDROOT" "${BUILD_DIR}/${componentTest}-${mode}.lock" > /dev/null 2>&1
-      fi
-      if [ -f "${BUILDROOT}/${mode}/${componentTest}-short.log" ]; then
-        cat "${BUILDROOT}/${mode}/${componentTest}-short.log"
-      fi
-      failed=1
-    fi
+  # It was successful, so it can remove the lock
+  if [ -d "${BUILD_DIR}/${componentTest}-${mode}.lock" ]; then
+      rm "${BUILD_DIR}/${componentTest}-${mode}.lock"
   fi
-done
-
-
-echo ""
-echo "Finished $mode tests on `date`"
-if [ $failed = "0" ]; then
-  echo "All $mode tests passed!"
+elif [ $retval = "3" ]; then
+  echo "Skipped: ${componentTest}-$mode tests"
 else
-  echo "*** Some $mode tests failed."
+  echo "Failed: ${componentTest}-${mode} tests"
+  if [ ! -d "${BUILD_DIR}/${componentTest}-${mode}.lock" ]; then
+    ln -s "$BUILDROOT" "${BUILD_DIR}/${componentTest}-${mode}.lock" > /dev/null 2>&1
+  fi
+  if [ -f "${BUILDROOT}/${mode}/${componentTest}-short.log" ]; then
+    cat "${BUILDROOT}/${mode}/${componentTest}-short.log"
+  fi
+  failed=1
 fi
+
+
 
 exit $failed
