compare_dat_files.pl   - Comments   - Improved return codes   - Output format
compare_dats:
  - Fixed hole in error checking.  Both udas must have the same number of dat files
  - Improved return codes


compare_sus_runs:
  - Added summary to the bottom of the compare_sus_runs.log.txt file

Summary:
======================================
  dat file comparsions:       PASSED
  uda comparisons:            PASSED
  checkpoint comparisons:     PASSED
======================================




Former-commit-id: 045660cb9690b08be5fc50368b8113ee33687d5a

diff --git a/src/R_Tester/helpers/compare_dats b/src/R_Tester/helpers/compare_dats
--- a/src/R_Tester/helpers/compare_dats
+++ b/src/R_Tester/helpers/compare_dats
@@ -2,17 +2,18 @@
 
 #______________________________________________________________________
 #  This script performs bulletproofing checks and calls
-#  the perl script compare_dat_files which does the actual comparison.
+#  the perl script (compare_dat_files.pl) which does the dat file comparisons.
 # 
 #   exit return values:
 #     -1:   no dat files to compare
 #      0:   The dat files are withn allowable errors
-#      1:   - Error occured and dats cannot be compared
-#           - Comparison failed
+#      1:   Comparison failed
+#      2:   Missing dat files
 #______________________________________________________________________
 
+tmpFile='.tmpCompDat'
 test_uda=$1
-compare_uda=$2
+gs_uda=$2
 
 abs_tol=$3  # Absolute tolerance
 rel_tol=$4  # Relative tolerance
@@ -21,36 +22,46 @@ if [ ! -d "$test_uda" ]; then
   echo "$test_uda doesn't exist"
   exit 1
 fi  
-if [ ! -d "$compare_uda" ]; then
-  echo "$compare_uda doesn't exist"
+if [ ! -d "$gs_uda" ]; then
+  echo "$gs_uda doesn't exist"
   exit 1
 fi
 
 #__________________________________
-# do both uda have dat files?
+#  are dat file present?
+n_dats_uda=`find $test_uda -maxdepth 1 -type f -name '*.dat' | wc -l`
+n_dats_gs=`find $gs_uda -maxdepth 1 -type f -name '*.dat' | wc -l`
+sum=$((n_dats_uda + n_dats_gs))
 
-ls -1 $test_uda/*.dat >/dev/null 2>&1
-retval=$?
-
-echo
-
-if [ $retval != "0" ]; then
-  # $test_uda has no dat files
-  ls -1 $compare_uda/*.dat >/dev/null 2>&1
-  retval=$?
-  echo
-  if [ $retval != "0" ]; then
-    # $compare_uda has no dat files either
-    echo "No dat files to compare"
-    exit -1
-  else
-    # $compare_uda does have at least one dat file so
-    # there is no excuse for $test_uda for not having any.
-    echo "The new uda directory has no dat files, but the old one does"
-    exit 1
-  fi
+if [ $sum == 0 ]; then
+  echo "  No dat files to compare"
+  exit -1
 fi
 
+#__________________________________
+# do both udas have dat files?
+
+diff $test_uda $gs_uda | grep -E 'Only.*dat' > $tmpFile
+
+missing_dats=`wc --lines < $tmpFile`
+
+if [ ${missing_dats} != "0" ]; then
+  
+  dats=`cat $tmpFile | grep $test_uda | cut -f 2 -d :`
+  
+  if [ ! -z $dats ]; then
+    echo "   ERROR: Missing dat files ($dats) in the gold standard uda"
+    exit 2
+  fi
+  
+  dats=`cat $tmpFile | grep $gs_uda | cut -f 2 -d :`  
+  
+  if [ ! -z $dats  ]; then
+    echo "   ERROR: Missing dat files ($dats) in the gold standard uda"
+    exit 2 
+  fi
+fi
+/bin/rm $tmpFile
 
 #__________________________________
 # perform comparison
@@ -60,29 +71,9 @@ dats=`ls -1 *.dat`
 testdat=`ls -1 *.dat | head -n 1`
 cd $WD
 
-#echo "compare_dat_files.pl $abs_tol $rel_tol $test_uda/ $compare_uda/ $dats"
-
-compare_dat_files.pl $abs_tol $rel_tol $test_uda/ $compare_uda/ $dats
+compare_dat_files.pl $abs_tol $rel_tol $test_uda/ $gs_uda/ $dats
 
 retval=$?
-
-newcount="0"
-oldcount="0"
-
-#__________________________________
-if [ $retval = "0" ]; then
-  newcount=`grep -c '\0' $test_uda/$testdat`
-  oldcount=`grep -c '\0' $compare_uda/$testdat`
-
-  if [ $newcount != $oldcount ]; then
-      cat <<EOF
-There is a discrepancy in the line count of the dat files.
-There are $newcount lines in the new $testdat and
-          $oldcount lines in the old $testdat.
-This could simply be a result of a change to the timestep size.
-EOF
-  fi
-fi
 
 exit $retval
 
