compare_uda:   - added exit values to the usage
compare_sus_runs:
  - fixed faulty logic.  If the udas cannot be compared then abort.
  - added comments describing the exit codes.
  
compare_dats:
  - added comments describing the exit codes.
  - clean up, 2 space indentation, lower case variable names
  
The following optimized tests will fail since the comparison failures weren't allowed to slip through.

Failed: ARCHES-opt tests 
  :isotropic-turbulence-decay__NEW: 	  test failed comparison tests

Failed: ICE-opt tests 
  :CouettePoiseuille: 	  test failed comparison tests
  :CouettePoiseuille: 	 (restart) test failed comparison tests

Failed: Wasatch-opt tests 
  :scalability-test: 	  test failed comparison tests

diff --git a/src/R_Tester/helpers/compare_sus_runs b/src/R_Tester/helpers/compare_sus_runs
--- a/src/R_Tester/helpers/compare_sus_runs
+++ b/src/R_Tester/helpers/compare_sus_runs
@@ -6,6 +6,14 @@
 #   - dat files
 #   - uda directories
 #   - checkpoint comparisons
+#   
+#   exit return values:
+#    -1:  not dat comparison
+#     0:  comparison passed
+#     1:  udas compared but the comparison failed
+#     5:  udas cannot be compared
+#    10:  input files differ
+#
 #______________________________________________________________________
 
 compareUda_function()
@@ -69,6 +77,12 @@ compareUda_function()
   $sus_dir/compare_uda $compare_flags $test_uda_dir $gs_uda_dir
 
   uda_retval=$?
+  echo "return value $uda_retval"
+  if [ $uda_retval == "5" ]; then
+    echo 
+    echo "*** uda directories cannot be compared ***"
+    exit 5
+  fi
 
   if [ $uda_retval != "0" ]; then
     echo                                                         
@@ -95,22 +109,20 @@ compareUda_function()
       echo "*** checkpoint comparison tests failed ***"  
       failed="1"                                         
     fi
-
-    if [ $failed != "0" ]; then
-      if [ $inputs_differ = "1" ]; then
-        exit 5;
-      fi
-      exit $failed
-    fi
-
-    if [ $inputs_differ = "1" ]; then
-      exit 10;
-    fi
   else
     echo "       WARNING: The checkpoint directory was not present in either the goldstandard or the test"
     echo "                No comparison performed"
   fi
+  #______________________________________________________________________
+  #  all of the uda comparisons have been made
+  
+  if [ $failed != "0" ]; then
+    exit $failed
+  fi
 
+  if [ $inputs_differ = "1" ]; then
+    exit 10;
+  fi
   exit 0
 }
 
@@ -120,6 +132,13 @@ compareUda_function()
 #  This script is a wrapper around the compareUda_function().  
 #    If the gold standard does not exist then it's created.
 #    The user must be the owner of the gold standards directory to copy to that dir
+#
+#   exit return values:
+#    -2:    copied existing uda to gold standards
+#    -1:    
+#     0:    passed
+#     1:    Error creating the gold standards
+#     5:    The udas may not be compared
 #______________________________________________________________________
 
 test=$1                # name of regression test
@@ -193,7 +212,7 @@ if [ -d "$test_uda_dir" ]; then
     echo "Missing gold Standard uda directory: $gs_uda_dir"
     
     if [ "$is_owner" = "true" ]; then
-      echo "copying the exiting uda to the gold standards"
+      echo "copying the existing uda to the gold standards"
 
       # try to remove it in case it exists as a non-directory
       /bin/rm $gs_uda_dir 
