Fixed major flaws in how memory gold standards were created.
compare_sus_runs:
  - variable create_gs determines whether to copy the original uda and memory files to the GS or 
    the restart memory files to the GS.

highwater_percent.pl
  - Throw an error if the high water value isn't available in either the current RT or the GS.
 
mem_leak_check
  - Throw an error if the merged malloc_stat file has 0 bytes.
  - rearrange where the highwater memory plots are generated.

replace_gold_standard
  - spacing
  
runComponentTests
  - set the environmental variable COMMON_GROUP in the doTestScripts
  
runSusTests.py
  - Perform memory tests before comparing udas.  This allows the malloc_stats file to be copied to the GS
  - regression test fails if memory tests fails
  - use the variable create_gs (yes_inputfile, yes_retart, no) to control when a GS is generated and 
    what is copied.
  
  
*** Any test that performs a memory check and if the GS:malloc_stats or GS:restart_malloc_stats are missing will fail.

diff --git a/src/R_Tester/helpers/compare_sus_runs b/src/R_Tester/helpers/compare_sus_runs
--- a/src/R_Tester/helpers/compare_sus_runs
+++ b/src/R_Tester/helpers/compare_sus_runs
@@ -78,28 +78,28 @@ compareUda_function()
 
   uda_retval=$?
   echo "compare_uda return value $uda_retval"
-  
+
   if [ $uda_retval == "5" ]; then
     echo
     echo "*** compare_uda aborted comparison. uda directories cannot be compared ***"
     exit 5
   fi
-  
+
   if [ $uda_retval != "0" ]; then
 
     if [ $uda_retval == "2" ]; then
       echo
       echo "*** uda comparison tests failed:  tolerances exceeded ***"
     fi
-    
+
     echo
     echo "Computing the Lnorms between the two udas "
     echo "======================================"
     $sus_dir/tools/compute_Lnorm_udas $test_uda_dir $gs_uda_dir
-    
+
     failed="1"
   fi
-  
+
 
   echo
   echo "Comparing checkpoints"
@@ -116,19 +116,19 @@ compareUda_function()
       echo "*** compare_uda aborted comparison. uda directories cannot be compared ***"
       exit 5
     fi
-    
+
     if [ $chp_retval == "2" ]; then
       echo
       echo "*** uda comparison tests failed:  tolerances exceeded ***"
       failed="1"
     fi
-    
+
     if [ $chp_retval != "0" ]; then
       echo
       echo "*** checkpoint comparison tests failed ***"
       failed="1"
-    fi  
-    
+    fi
+
   else
     echo "       WARNING: The checkpoint directory was not present in either the goldstandard or the test"
     echo "                No comparison performed"
@@ -167,6 +167,7 @@ gs_component_dir=$3    # path to gold standard component
 sus_dir=$4             # path to sus
 abs_tol=$5             # Absolute tolerance
 rel_tol=$6             # Relative tolerance
+create_gs=$7           # bool should the gold_standard be created?
 
 #__________________________________
 # determine the paths of the 2 udas
@@ -227,39 +228,48 @@ if [ -d "$test_uda_dir" ]; then
   fi
 
   #__________________________________
-  # copy the gold standards if they don't exist if needed
-  if [ ! -d "$gs_uda_dir" ]; then
-    echo "Missing gold Standard uda directory: $gs_uda_dir"
+  # copy the gold standards if they don't exist
+  # be careful copying the restart data  
+  
+  if [[ "$is_owner" == "false" && "$create_gs" =~ yes.* ]]; then
+    echo "  Permissions failure:  Only the owner of the gold standards directory can copy an uda to it for the first time."
+    echo "  Now exiting"
+    exit 1
+  fi
 
-    if [ "$is_owner" = "true" ]; then
-      echo "copying the existing uda to the gold standards"
+  # copy original uda and files
+  if [ $create_gs == "yes-inputFile" ]; then
+    echo "  Missing gold Standard uda directory: $gs_uda_dir"
+    echo "  copying the orginal uda to the gold standards"
 
-      # try to remove it in case it exists as a non-directory
-      /bin/rm $gs_uda_dir
+    # try to remove it in case it exists as a non-directory
+    /bin/rm $gs_uda_dir >/dev/null 2>&1
 
-      # --dereference option: always follow symbolic links
-      cp -r --dereference $test_uda_dir $gs_uda_dir
+    # --dereference option: always follow symbolic links
+    cp -r --dereference $test_uda_dir $gs_uda_dir
 
-      if [ $? != "0" ]; then
-	  # try without --dereference -- not all cp's have this option
-	  cp -r $test_uda_dir $gs_uda_dir
-      fi
-
-      # copy text files to the goldStandard
-      cp $test_dir/sus.log.txt  $test_dir/timestamp $test_dir/restart_timestamp $gs_component_dir/$test >/dev/null 2>&1
-      cp $test_dir/malloc_stats $test_dir/restart_malloc_stats                  $gs_component_dir/$test >/dev/null 2>&1
-
-      chgrp -R $COMMON_GROUP "$gs_component_dir/$test"
-      chmod -R g+rwX "$gs_component_dir/$test"
-
-      exit -2
-    else
-      echo "  Permissions failure:  Only the owner of the gold standards dir can copy uda to it."
-      echo "  Now exiting"
-      exit 1
+    if [ $? != "0" ]; then
+	# try without --dereference -- not all cp's have this option
+	cp -r $test_uda_dir $gs_uda_dir
     fi
 
+    # copy text files to the goldStandard. For each uda it passes
+    # through this section twice
+    cp "$test_dir/sus.log.txt"           $gs_component_dir/$test/.
+    cp "$test_dir/timestamp"             $gs_component_dir/$test/.
+    cp "$test_dir/malloc_stats"          $gs_component_dir/$test/.
+
+    chgrp -R $COMMON_GROUP "$gs_component_dir/$test"
+    chmod -R g+rwX "$gs_component_dir/$test"
+
+  # copy restart files
+  elif [ $create_gs == "yes-restart" ]; then
+    echo "  copying the restart files to the gold standards: $gs_uda_dir"
+    cp "$test_dir/restart_timestamp"     $gs_component_dir/$test/.
+    cp "$test_dir/restart_malloc_stats"  $gs_component_dir/$test/.
+    
   else
+
     #______________________________________________________________________
     #  now run the comparison function
     echo "Testing $test"
diff --git a/src/R_Tester/helpers/mem_leak_check b/src/R_Tester/helpers/mem_leak_check
--- a/src/R_Tester/helpers/mem_leak_check
+++ b/src/R_Tester/helpers/mem_leak_check
@@ -7,8 +7,8 @@ COMPARE_ROOT=$4
 TMPDIR=$5
 HELPERPATH=$6
 
-COMPARISON_MALLOC_STATS="$COMPARE_ROOT/$TEST/$MALLOC_STATS"
-error=1
+GS="$COMPARE_ROOT/$TEST/"
+COMPARISON_MALLOC_STATS="$GS/$MALLOC_STATS"
 HERE=`pwd`
 
 #__________________________________
@@ -20,6 +20,46 @@ if [ $OS = "Darwin" ]; then
   STAT_CMD="stat -f %z"
 fi
 
+#______________________________________________________________________
+# This function merges the malloc_stats files.  There is a
+# separate file for each process id.
+function merge_malloc_stats_files()
+{  
+  here=`pwd`
+  malloc_dir=$1
+  cd $malloc_dir
+  
+  echo "__________________________________"
+  echo "merge_malloc_stats_files: ($malloc_dir)"
+  
+  # if malloc_stats exists then return
+  if [ -f $MALLOC_STATS ]; then
+    bytes=`$STAT_CMD $MALLOC_STATS 2>/dev/null`
+
+    if [ $bytes != "0" ]; then
+      echo "  $MALLOC_STATS exists nothing to merge."
+      return 0
+    fi
+  fi
+  
+  #__________________________________
+  cat $MALLOC_STATS.* > $MALLOC_STATS 
+  
+  bytes=`$STAT_CMD $MALLOC_STATS 2>/dev/null`
+  
+  if [ $bytes = "0" ]; then
+      echo "  ERROR, combining the malloc_stats files in the directory: $malloc_dir."
+      echo "  Not performing memory leak or memory highwater tests"
+      echo "  This occurs with the localRT on restarts, or if the gold standards haven't been created"
+      exit 5
+   fi
+   echo "  Successfully merged $malloc_dir/malloc_stats files.*."
+  cd $here
+  return 0
+}
+#______________________________________________________________________
+
+
 #__________________________________
 # bulletproofing
 if [ ! -f $MALLOC_STATS ] && [ ! -f $MALLOC_STATS.0 ]; then
@@ -29,40 +69,11 @@ if [ ! -f $MALLOC_STATS ] && [ ! -f $MALLOC_STATS.0 ]; then
   exit 5
 fi
 
-#__________________________________
-# The malloc stats data are stored in separate files for each process id. Merge them
-ls $MALLOC_STATS.* >/dev/null 2>&1
-retval=$?
+# merge the malloc_stat files in both the localRT and gold Standards directories
+# After running generating the localRT gold standards they need to be merged
+merge_malloc_stats_files $HERE 
 
-if [ $retval = "0" ]; then
-  cat $MALLOC_STATS.* > $MALLOC_STATS
-  echo "Merging malloc stats_files.* from the multiple processes."
-  if [ `$STAT_CMD $MALLOC_STATS` = "0" ]; then
-    echo "No malloc_stats information found.  Can't do memory leak test."
-    exit 5
-  fi
-fi
-
-#__________________________________
-#   If the gold standards merged malloc_stats file
-#   doesn't exist then merge the separate files
-GS="$COMPARE_ROOT/$TEST/"
-cd $GS
-if [ ! -f $MALLOC_STATS ] && [ -f $MALLOC_STATS.0 ]; then
-  cd $GS
-  ls $MALLOC_STATS.* >/dev/null 2>&1
-  retval=$?
-
-  if [ $retval = "0" ]; then
-    cat $MALLOC_STATS.* > $MALLOC_STATS
-    echo "Merging the gold standards malloc_stats.* files from the multiple processes."
-    if [ `$STAT_CMD $MALLOC_STATS` = "0" ]; then
-      echo "No gold standard malloc_stats information found.  Can't do memory leak test."
-      exit 5
-    fi
-  fi
-fi
-cd $HERE
+merge_malloc_stats_files $GS
 
 #__________________________________
 echo "Checking $TEST for scinew memory leaks"
@@ -79,10 +90,35 @@ fi
 
 echo "Memory leak test passed -- no scinew memory leaks found"
 
+#__________________________________
+#  run check the highwater memory usage
+echo "Performing highwater memory usage check"
+
 meminfo=`highwater_percent.pl $MALLOC_STATS $COMPARISON_MALLOC_STATS`
 percent=`echo $meminfo | cut -d " " -f 1`
 abs=`echo $meminfo | cut -d " " -f 2`
 testHighwater=`echo $meminfo | cut -d " " -f 3`
+
+
+#__________________________________
+if [ $percent -gt "10" -a $abs -gt "1000000" ]; then
+  echo "***Highwater memory usage test failed"
+  echo " -- memory usage increased by %$percent ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
+  exit 2
+
+elif [ $percent -gt "0" ]; then
+  echo " -- memory usage increased by %$percent ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
+  exit 0
+elif [ $percent -lt "0" ]; then
+  let percent_improvement=-$percent;
+  echo " -- memory usage improved by %$percent_improvement ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
+  exit 0
+else
+  echo "" > $TMPDIR/highwater_shortmessage.txt
+  echo "Highwater memory usage check passed!"
+  exit 0
+fi
+
 
 #__________________________________
 if [ $MAKEPLOTS -eq "1" ]; then
@@ -110,26 +146,4 @@ if [ $MAKEPLOTS -eq "1" ]; then
   gnuplot $HELPERPATH/plotMemUsage.gp
   
 fi
-#__________________________________
-echo "Performing highwater memory usage check"
-
-if [ $percent -gt "10" -a $abs -gt "1000000" ]; then
-  echo "***Highwater memory usage test failed"
-  echo " -- memory usage increased by %$percent ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
-  exit 2
-
-elif [ $percent -gt "0" ]; then
-  echo " -- memory usage increased by %$percent ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
-  exit 0
-elif [ $percent -lt "0" ]; then
-  let percent_improvement=-$percent;
-  echo " -- memory usage improved by %$percent_improvement ($abs bytes)" > $TMPDIR/highwater_shortmessage.txt
-  exit 0
-else
-  echo "" > $TMPDIR/highwater_shortmessage.txt
-  echo "Highwater memory usage check passed!"
-  exit 0
-
-fi
-
-exit $error
+exit 1
