compare_uda:   - changed cerr messages -> ostringstream and passing the stream into the abort_uncomparable();     abort_uncomparble(): slightly better reporting to the user why comparison aborted.
compare_sus_runs & runSusTests
  - reduce the amount of noise pumped out by local/nightly RT when the input files differ.
  - slightly better reporting to the user why a comparison failed.

diff --git a/src/R_Tester/helpers/compare_sus_runs b/src/R_Tester/helpers/compare_sus_runs
--- a/src/R_Tester/helpers/compare_sus_runs
+++ b/src/R_Tester/helpers/compare_sus_runs
@@ -6,7 +6,7 @@
 #   - dat files
 #   - uda directories
 #   - checkpoint comparisons
-#   
+#
 #   exit return values:
 #    -1:  not dat comparison
 #     0:  comparison passed
@@ -61,7 +61,7 @@ compareUda_function()
   compare_dats $test_uda_dir $gs_uda_dir $abs_tol $rel_tol
   compare_dats_retval=$?
   if [ $compare_dats_retval = "1" ]; then
-    echo 
+    echo
     echo "*** dat comparison tests failed ***"
     failed="1"
   elif [ $compare_dats_retval = "-1" ]; then
@@ -77,22 +77,29 @@ compareUda_function()
   $sus_dir/compare_uda $compare_flags $test_uda_dir $gs_uda_dir
 
   uda_retval=$?
-  echo "return value $uda_retval"
+  echo "compare_uda return value $uda_retval"
+  
   if [ $uda_retval == "5" ]; then
-    echo 
-    echo "*** uda directories cannot be compared ***"
+    echo
+    echo "*** compare_uda aborted comparison. uda directories cannot be compared ***"
     exit 5
   fi
-
+  
   if [ $uda_retval != "0" ]; then
-    echo                                                         
-    echo "*** uda comparison tests failed ***"                   
-    failed="1"                                                   
-    echo                                                         
-    echo "Computing the Lnorms between the two udas "            
-    echo "======================================"                
-    $sus_dir/tools/compute_Lnorm_udas $test_uda_dir $gs_uda_dir  
+
+    if [ $uda_retval == "2" ]; then
+      echo
+      echo "*** uda comparison tests failed:  tolerances exceeded ***"
+    fi
+    
+    echo
+    echo "Computing the Lnorms between the two udas "
+    echo "======================================"
+    $sus_dir/tools/compute_Lnorm_udas $test_uda_dir $gs_uda_dir
+    
+    failed="1"
   fi
+  
 
   echo
   echo "Comparing checkpoints"
@@ -104,18 +111,31 @@ compareUda_function()
     $sus_dir/compare_uda -skip_unknown_types $compare_flags $test_uda_dir/checkpoints $gs_uda_dir/checkpoints
     chp_retval=$?
 
-    if [ $chp_retval != "0" ]; then
-      echo 
-      echo "*** checkpoint comparison tests failed ***"  
-      failed="1"                                         
+    if [ $chp_retval == "5" ]; then
+      echo
+      echo "*** compare_uda aborted comparison. uda directories cannot be compared ***"
+      exit 5
     fi
+    
+    if [ $chp_retval == "2" ]; then
+      echo
+      echo "*** uda comparison tests failed:  tolerances exceeded ***"
+      failed="1"
+    fi
+    
+    if [ $chp_retval != "0" ]; then
+      echo
+      echo "*** checkpoint comparison tests failed ***"
+      failed="1"
+    fi  
+    
   else
     echo "       WARNING: The checkpoint directory was not present in either the goldstandard or the test"
     echo "                No comparison performed"
   fi
   #______________________________________________________________________
   #  all of the uda comparisons have been made
-  
+
   if [ $failed != "0" ]; then
     exit $failed
   fi
@@ -129,13 +149,13 @@ compareUda_function()
 
 #______________________________________________________________________
 #______________________________________________________________________
-#  This script is a wrapper around the compareUda_function().  
+#  This script is a wrapper around the compareUda_function().
 #    If the gold standard does not exist then it's created.
 #    The user must be the owner of the gold standards directory to copy to that dir
 #
 #   exit return values:
 #    -2:    copied existing uda to gold standards
-#    -1:    
+#    -1:
 #     0:    passed
 #     1:    Error creating the gold standards
 #     5:    The udas may not be compared
@@ -145,7 +165,7 @@ test=$1                # name of regression test
 test_dir=$2            # path to uda to be compared
 gs_component_dir=$3    # path to gold standard component
 sus_dir=$4             # path to sus
-abs_tol=$5             # Absolute tolerance 
+abs_tol=$5             # Absolute tolerance
 rel_tol=$6             # Relative tolerance
 
 #__________________________________
@@ -173,10 +193,10 @@ fi
 if [ -d "$test_uda_dir" ]; then
 
   #__________________________________
-  # Create the GS/<component> directory if needed 
+  # Create the GS/<component> directory if needed
   if [ ! -d "$gs_component_dir" ]; then
     echo "Missing $gs_component_dir directory"
-    
+
     if [ "$is_owner" = "true" ]; then
       echo "  Creating directory"
       compare_PARENT_DIR=`echo "$gs_component_dir" | sed 's|/[^/]*$||'`
@@ -189,12 +209,12 @@ if [ -d "$test_uda_dir" ]; then
       exit 1
     fi
   fi
-  
+
   #__________________________________
   # Create the GS/<component>/<test> directory if needed
   if [ ! -d "$gs_component_dir/$test" ]; then
     echo "Missing $gs_component_dir/$test directory"
-  
+
     if [ "$is_owner" = "true" ]; then
       echo "  Creating directory"
       cd $gs_component_dir
@@ -205,17 +225,17 @@ if [ -d "$test_uda_dir" ]; then
       exit 1
     fi
   fi
-  
+
   #__________________________________
   # copy the gold standards if they don't exist if needed
   if [ ! -d "$gs_uda_dir" ]; then
     echo "Missing gold Standard uda directory: $gs_uda_dir"
-    
+
     if [ "$is_owner" = "true" ]; then
       echo "copying the existing uda to the gold standards"
 
       # try to remove it in case it exists as a non-directory
-      /bin/rm $gs_uda_dir 
+      /bin/rm $gs_uda_dir
 
       # --dereference option: always follow symbolic links
       cp -r --dereference $test_uda_dir $gs_uda_dir
@@ -238,12 +258,11 @@ if [ -d "$test_uda_dir" ]; then
       echo "  Now exiting"
       exit 1
     fi
-    
-  else  
+
+  else
     #______________________________________________________________________
     #  now run the comparison function
     echo "Testing $test"
-    #compare_sus_runs_by_udas $test_uda_dir $gs_uda_dir $sus_dir $abs_tol $rel_tol
     compareUda_function $test_uda_dir $gs_uda_dir $sus_dir $abs_tol $rel_tol
     exit $?
   fi
