* Merge of trunk with /branches/komp_scheduler/src (svn merge -r57139:57190 https://gforge.sci.utah.edu/svn/uintah/trunk/src).
Former-commit-id: 394d1287326c0d5a5429fccf0cb950a05b835e20

diff --git a/src/R_Tester/helpers/mem_leak_check b/src/R_Tester/helpers/mem_leak_check
--- a/src/R_Tester/helpers/mem_leak_check
+++ b/src/R_Tester/helpers/mem_leak_check
@@ -58,7 +58,11 @@ function merge_malloc_stats_files()
 
 
 #__________________________________
-# bulletproofing
+# merge the malloc_stat files in both the local and gold Standards directories
+# After generating the localRT
+ 
+merge_malloc_stats_files $HERE
+
 if [ ! -f $MALLOC_STATS ] && [ ! -f $MALLOC_STATS.0 ]; then
   echo "The malloc_stats file(s) is missing.  Can't perform memory leak test."
   echo "Verify that you've configured with"
@@ -66,11 +70,14 @@ if [ ! -f $MALLOC_STATS ] && [ ! -f $MALLOC_STATS.0 ]; then
   exit 5
 fi
 
-# merge the malloc_stat files in both the localRT and gold Standards directories
-# After running generating the localRT gold standards they need to be merged
-merge_malloc_stats_files $HERE 
 
 merge_malloc_stats_files $GS
+
+if [ ! -f $COMPARISON_MALLOC_STATS ]; then
+  echo "The gold standard malloc_stats file(s) are missing for this test.  Now exiting."
+  exit 5
+fi
+
 cd $HERE
 
 #__________________________________
