Added gui interface to replace_gold_standard
Added a master replace_GS script so all the GS can be replaced via one
script in either opt or dbg.

diff --git a/src/R_Tester/helpers/replace_gold_standard b/src/R_Tester/helpers/replace_gold_standard
--- a/src/R_Tester/helpers/replace_gold_standard
+++ b/src/R_Tester/helpers/replace_gold_standard
@@ -8,55 +8,119 @@
 #
 # Usage:
 #
-#    replace_gold_standard new_gold_uda gold_standard_dir testname force comment
-#        new_gold_uda      : the new uda
-#        gold_standard_dir : location of the gold standard udas
-#        testname          :
+#    replace_gold_standard [Options] <new_gold_uda> <gold_standard_dir> <testname> <comment>
+#        new_gold_uda      : Required:  the new uda
+#        gold_standard_dir : Required:  location of the gold standard udas
+#        testname          : Required:  
 #        force             : -f | -m 
 #                            -f : it won't ask you yes/no questions
 #                            -m : it won't ask, but will only replace memory stats
-#       comment            : user specified -f then they must include a comment for the log file
+#       comment            : Required:  Comment for the log file
 #
-
-# echos are commented to not output so much
-
-gold_standard_dir="$1"
-replacement_dir="$2"
-testname="$3"
-force="$4"     # if set to -f then it won't ask you yes/no questions
-               # if set to -m then it won't ask, but will only replace memory stats
-comment="$5"   # if using -f or -m then the 5th argument is a comment for the log file
-
-interactive="true"
-if [ "$force" = "-f" -o "$force" = "-m" ]; then
-  interactive="false"
-fi
-if [ "$force" = "-f" ]; then
-  yesno="yes"
-fi
-
-
-# Info for a log file, to keep track of who replaced gold standards
-logfile="$gold_standard_dir/$testname/replace.log"
-user=`whoami`
+#__________________________________
+# Defaults
+do_all="false"
 do_uda="false"
 do_mem="false"
 do_perf="false"
 do_input="false"
 do_checkpoint="false"
 
-if [ "$interactive" = "false" -a "$comment" = "" ]; then
-  echo "You must add a comment to the log file"
-  echo "usage: $0 <gold_standard_dir> <replacement_dir> <testname> [-f] [log file comment]"
-  exit 1 
+#__________________________________
+# usage
+printUsage(){
+  echo "replace_gold_standard  [options] <new goldStandard uda> < gold Standard Dir> <test name>"
+  echo "  Required:"
+  echo "      new gold standard uda"
+  echo "      gold standard directory"
+  echo "      test name"
+  echo "  Options:"
+  echo "       -a | --all          replace the uda, memory stats, and performance stats"
+  echo "       -c | --checkpoints  replace just the checkpoint directory"
+  echo "       -h | --help"
+  echo "       -i | --inputFile    replace the input file"
+  echo "       -m | --memory       replace the memory stats file"
+  echo "       -p | --performance  replace the performance file"
+  echo "       -u | --uda          replace the uda"
+  exit
+}
+
+#______________________________________________________________________
+# Evaluate the command line options
+INPUTS=`getopt --options=a,c,h,i,m,p,u  --longoptions=all,checkpoint,help,inputFile,memory,performance,uda -- "$@"`
+if [ $? != 0 ] ; then 
+  echo "Invalid input option.  Now exiting..." >&2 ; 
+  exit 1 ; 
+fi  
+
+#__________________________________
+# If user didn't input an options or a comment
+if [ $# -le 3 ]; then
+  inputs=`dialog --stdout --separate-output --checklist "Select what you want to replace" 20 50 40 "uda" "" off, "checkpoints" "" off, "memory" "" off, "performance" "" off, "inputFile" "" off, "all" "" on`
+  
+  # add "--" to the input options
+  options=""
+  for opt in ${inputs[@]}
+    do
+      options=( ${options[@]} `echo $opt|sed s/^/\ --/` )
+    done
+  
+  #__________________________________                                                         
+  # input the comment message must say something                                                
+  logMessage=""                                                                               
+  while [ `echo $logMessage |wc -w` == 0 ];                                                
+    do                                                                                            
+      logMessage=`dialog --stdout --inputbox "Mandatory: Enter goldStandard log message:" 8 80` 
+      if [ $? != 0 ] ; then                                                                
+        echo "cancel selected"                                                                  
+        exit                                                                                    
+      fi                                                                                        
+  done  
+  # evaluate the user inputs
+  tmp=("${options[@]}" "$@" "${logMessage[@]}" "--" )
+  INPUTS=`getopt --options=a,c,h,i,m,p,u  --longoptions=all,checkpoints,help,inputFile,memory,performance,uda -- "${tmp[@]}"`                                                                                     
+fi
+echo "------------------------"
+echo ${INPUTS[@]}
+
+# Note the quotes around `$INPUTS': they are essential!
+eval set -- "$INPUTS"
+
+while true ; do
+  case "$1" in                                                    
+    -a|--all)         echo " replace all" ;         do_all="true";        shift ;;          
+    -c|--checkpoints) echo " replace Checkpoints" ; do_checkpoint="true"; shift ;;
+    -h|--help)        echo " replace help"        ; printHelp="true";     shift ;;
+    -i|--inputFile)   echo " replace input file" ;  do_input="true";      shift ;; 
+    -m|--memory)      echo " replace memory" ;      do_mem="true";        shift ;;
+    -p|--performance) echo " replace performance" ; do_perf="true" ;      shift ;;
+    -u|--uda)         echo " replace uda"         ; do_uda="true";        shift ;;                                                                                    
+    --) shift ; break ;;                                                  
+    *) echo "Internal error!" ; exit 1 ;;                                 
+  esac                                                                          
+done
+echo "Remaining arguments:"
+for arg do 
+  echo '--> '"\`$arg'" ;
+done
+
+if [ "printUsage" = "true" ]; then
+  printHelp
 fi
 
+shift $(($OPTIND - 1))
 
-# prompt for and replace udas
-if [ $# -ne 3 -a $# -ne 4 -a $# -ne 5 ]; then
-  echo "usage: $0 <gold_standard_dir> <replacement_dir> <testname> [-f] [log file comment]"
-  exit 1
-fi
+gold_standard_dir="$1"
+replacement_dir="$2"
+testname="$3"
+comment="$4"
+
+# Info for a log file, to keep track of who replaced gold standards
+logfile="$gold_standard_dir/$testname/replace.log"
+user=`whoami`
+
+#__________________________________
+# bulletproofing
 if [ ! -d $gold_standard_dir/$testname ]; then
   echo "$gold_standard_dir/$testname does not exist!"
   exit 1
@@ -64,22 +128,17 @@ fi
 
 #__________________________________
 # replace UDA
-if [ ! -d $replacement_dir/$testname/*.uda -o "$force" = "-m" ]; then
-  echo "No udas to replace, or not replacing them"
-else
-
-  if [ "$interactive" = "true" ]; then
-    echo "Replace the udas at $gold_standard_dir/$testname with $replacement_dir/$testname? (Enter 'yes' or 'y' to continue.) "
-    read yesno
-  fi
+if [ "$do_uda" = "true" ]; then
+  if [ ! -d $replacement_dir/$testname/*.uda ]; then
+    echo "No udas to replace, or not replacing them"
+  else
   
-  # remove the udas, sus.log.txt, and copy the new ones
-  if [ $yesno = "y" -o $yesno = "yes" ]; then
-    do_uda="true"
+    # remove the udas, sus.log.txt, and copy the new ones
     failcode="0"
     echo -n "Replacing $testname udas ... "
     rm -rf $gold_standard_dir/$testname/*.uda
     rm -rf $gold_standard_dir/$testname/sus.log.txt
+    
     if [ $? != "0" ]; then
       failcode="1"
       echo "$testname replacement failed - could not remove old udas"
@@ -88,39 +147,37 @@ else
     # if it has a --dereference option, then use it
     cp -r --dereference $replacement_dir/$testname/*.uda       $gold_standard_dir/$testname/. > /dev/null 2>&1
     cp -r --dereference $replacement_dir/$testname/sus.log.txt $gold_standard_dir/$testname/. > /dev/null 2>&1
+    
     # sometimes it doesn't work with --dereference...
     if [ $? != "0" ]; then
       cp -r $replacement_dir/$testname/*.uda       $gold_standard_dir/$testname/.
       cp -r $replacement_dir/$testname/sus.log.txt $gold_standard_dir/$testname/.
+      
       if [ $? != "0" ]; then
         failcode="1"
-	echo "$testname replacement failed - could not copy new udas"
+	 echo "$testname replacement failed - could not copy new udas"
       fi
     fi
+    
     if [ "$failcode" = "0" ]; then
       echo "udas successfully replaced"
     fi
-  else
-    echo "udas not replaced"
+    
   fi
 fi
 
 #__________________________________
 # replace only the checkpoints
-if [ ! -d $replacement_dir/$testname/*.uda/checkpoints -o "$force" = "-m" ]; then
-  echo "No checkpoints to replace, or not replacing them"
-else
-  
-  if [ "$do_uda" == "false" ]; then
-    echo "Replace the checkpoints? (Enter 'yes' or 'y' to continue.) "
-    read yesno
-  fi
-  
-  # remove the udas, and copy the new ones
-  if [ "$yesno" = "y" -o "$yesno" = "yes" ]; then
-    do_checkpoint="true"
+if [ "$do_checkpoint" = "true" ]; then
+
+  if [ ! -d $replacement_dir/$testname/*.uda/checkpoints ]; then
+    echo "No checkpoints to replace, or not replacing them"
+  else
+
+    # remove the checkpoints, and copy the new ones
     failcode="0"
-    echo -n "Replacing $testname udas ... "
+    echo -n "Replacing $testname checkpoints ... "
+    
     rm -rf $gold_standard_dir/$testname/*.uda/checkpoints
   
     if [ $? != "0" ]; then
@@ -134,93 +191,80 @@ else
     # sometimes it doesn't work with --dereference...
     if [ $? != "0" ]; then
       cp -r $replacement_dir/$testname/*.uda/checkpoints $gold_standard_dir/$testname/*.uda/.
+      
       if [ $? != "0" ]; then
         failcode="1"
 	echo "$testname checkpoint replacement failed - could not copy the new checkpoint"
       fi
     fi
+    
     if [ "$failcode" = "0" ]; then
       echo "checkpoint successfully replaced"
     fi
+   
   fi
 fi
 
 #__________________________________
 # replace memory usage stats
-if [ ! -f $gold_standard_dir/$testname/malloc_stats ]; then
-  echo "No memory stats to replace"
-else
-  
-  # replace the memory usage (both normal and restart)
-  if [ "$interactive" = "true" ]; then
-    echo "Replace $testname memory usage results? (Enter 'yes' or 'y' to continue.)"
-    read yesno
-  fi
+if [[ "$do_mem" = "true" || "$do_all" = "true" ]]; then
 
-  if [ "$yesno" = "y" -o "$yesno" = "yes" -o "$force" = "-m" ]; then
-    do_mem="true"
-    echo "Replacing $testname memory results"
-    rm $gold_standard_dir/$testname/*malloc* > /dev/null 2>&1
-    cp $replacement_dir/$testname/malloc_stats $gold_standard_dir/$testname/. > /dev/null 2>&1
-    if [ $? != "0" ]; then
-      echo "No malloc_stats -- ok"
-    fi
-    cp $replacement_dir/$testname/restart/restart_malloc_stats $gold_standard_dir/$testname/. > /dev/null 2>&1
-    if [ $? != "0" ]; then
-      echo "No restart_malloc_stats -- ok"
-    fi
+  if [ ! -f $gold_standard_dir/$testname/malloc_stats ]; then
+    echo "No memory stats to replace"
   else
-    echo "No memory usage results replaced"
+  
+    # replace the memory usage (both normal and restart)
+    echo "Replacing $testname memory results"
+    
+    rm $gold_standard_dir/$testname/*malloc* > /dev/null 2>&1
+    
+    if [ $? != "0" ]; then
+      echo "$testname memory usage replacement failed - could not remove old memory stats file"
+    fi
+    
+    cp $replacement_dir/$testname/malloc_stats $gold_standard_dir/$testname/. > /dev/null 2>&1
+    cp $replacement_dir/$testname/restart/restart_malloc_stats $gold_standard_dir/$testname/. > /dev/null 2>&1
+    
+    if [ $? != "0" ]; then
+     echo "$testname memory usage replacement failed - could not copy the new memory usage file"
+    fi
   fi
 fi
 
 #__________________________________
 # replace performance stats
-if [ ! -f $replacement_dir/$testname/timestamp ]; then
-  echo "No performance stats to replace"
-else
-
-  # replace the performance results (both normal and restart)
-  if [ "$interactive" = "true" ]; then
-    echo "Replace $testname performance results? (Enter 'yes' or 'y' to continue.)"
-    read yesno
-  fi
-
-  if [ "$yesno" = "y" -o "$yesno" = "yes" ]; then
-    do_perf="true"
-    echo "Replacing $testname performance results"
-    rm $gold_standard_dir/$testname/*timestamp > /dev/null 2>&1
-    cp $replacement_dir/$testname/timestamp $gold_standard_dir/$testname/. > /dev/null 2>&1
-    if [ $? != "0" ]; then
-      echo "Performance results not replaced"
-    fi
-    cp $replacement_dir/$testname/restart/restart_timestamp $gold_standard_dir/$testname/. > /dev/null 2>&1
-    if [ $? != "0" ]; then
-      echo "Restart performance results not replaced"
-    fi
+if  [[ "$do_perf" = "true" || "$do_all" = "true" ]]; then
+  if [ ! -f $replacement_dir/$testname/timestamp ]; then
+    echo "No performance stats to replace"
   else
-    echo "No performance results replaced"
+    # replace the performance results (both normal and restart)
+    echo "Replacing $testname performance results"
+    
+    rm $gold_standard_dir/$testname/*timestamp > /dev/null 2>&1
+    
+    if [ $? != "0" ]; then
+      echo "$testname performance replacement failed - could not remove old performance stats"
+    fi
+    
+    cp $replacement_dir/$testname/timestamp $gold_standard_dir/$testname/. > /dev/null 2>&1
+    cp $replacement_dir/$testname/restart/restart_timestamp $gold_standard_dir/$testname/. > /dev/null 2>&1
+    
+    if [ $? != "0" ]; then
+      echo "$testname performance replacement failed - could not copy the new performance stats"
+    fi
   fi
 fi
 
 #__________________________________
 # replace input file
-if [ "$interactive" = "true" -a "$do_uda" = "false" ]; then
-  echo "Replace $testname input file? (Enter 'yes' or 'y' to continue.)"
-  read yesno
-  
-  if [ "$yesno" = "y" -o "$yesno" = "yes" ]; then
-    do_input="true"
-    echo "Replacing $testname input file"
-    cp $replacement_dir/$testname/*.uda/input*.xml $gold_standard_dir/$testname/*.uda/. > /dev/null 2>&1
-  fi
+if [ "$do_input" = "true" ]; then
+  echo "Replacing $testname input file"
+  cp $replacement_dir/$testname/*.uda/input*.xml $gold_standard_dir/$testname/*.uda/. > /dev/null 2>&1
 fi
-
-
 
 #__________________________________
 # LOG FILE
-if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_input" = "true" -o "$do_checkpoint" = "true" ]; then
+if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_input" = "true" -o "$do_checkpoint" = "true" -o "$do_all" = "true" ]; then
   # make a log
   if [ ! -f $logfile ]; then
     echo "Replacement log for $gold_standard_dir/$testname" >> $logfile
@@ -231,31 +275,27 @@ if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_inp
   if [ "$do_uda" = "true" ]; then
     echo -n "replaced uda" >> $logfile
   fi
+  
   if [ "$do_checkpoint" = "true" ]; then
-    echo -n ", replaced checkpoints" >> $logfile
+    echo -n "replaced checkpoints" >> $logfile
   fi
+  
   if [ "$do_mem" = "true" ]; then
-    if [ "$do_uda" = "true" ]; then
-      echo -n ", memory usage" >> $logfile
-    else
       echo -n "replaced memory usage" >> $logfile
-    fi
   fi
+  
   if [ "$do_perf" = "true" ]; then
-    if [ "$do_uda" = "true" ]; then
-      echo -n ", performance results" >> $logfile
-    else
-      echo -n "replaced performance results" >> $logfile
-    fi
+    echo -n "replaced performance results" >> $logfile
   fi
+  
   if [ "$do_input" = "true" ]; then
     echo -n "replaced input file" >> $logfile
-  fi  
+  fi 
   
-  if [ "$interactive" = "true" ]; then
-    echo "Comment for the replaceLog file: "
-    read comment
-  fi
+  if [ "$do_all" = "true" ]; then
+    echo -n "replaced uda, checkpoints, memory usage performance results" >> $logfile
+  fi 
+  
   echo -n "       Comment: $comment" >> $logfile
   
   echo >> $logfile
@@ -264,7 +304,7 @@ if [ "$do_uda" = "true" -o "$do_mem" = "true" -o "$do_perf" = "true" -o "$do_inp
   #  email homebrew whenever there is a change to a GS
   if [ "$do_uda" = "true" ]; then
     tail -1 $logfile > message
-    mutt  -s "GoldStandard Change:$testname" john.schmidt@utah.edu < message
+    #mutt  -s "GoldStandard Change:$testname" john.schmidt@utah.edu < message
   fi
 
 # change groups and permissions so (hopefully) anybody can replace them later
