Only compare checkpoint directories if they exist in the test and the goldStandard. If the directories are not found warn the user.

diff --git a/R_Tester/helpers/compare_sus_runs_by_udas b/R_Tester/helpers/compare_sus_runs_by_udas
--- a/R_Tester/helpers/compare_sus_runs_by_udas
+++ b/R_Tester/helpers/compare_sus_runs_by_udas
@@ -67,27 +67,32 @@ fi
 echo
 echo "Comparing checkpoints"
 echo "======================================"
-echo
-echo "$SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints"
+if [[ -d "$TEST_UDADIR/checkpoints" &&  -d "$COMPARE_UDADIR/checkpoints" ]]; then
+  echo
+  echo "$SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints"
 
-$SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL -skip_unknown_types $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints
-chp_retval=$?
+  $SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL -skip_unknown_types $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints
+  chp_retval=$?
 
-if [ $chp_retval != "0" ]; then
-    echo 
-    echo "*** checkpoint comparison tests failed ***"
-    failed="1"
-fi
+  if [ $chp_retval != "0" ]; then
+      echo 
+      echo "*** checkpoint comparison tests failed ***"
+      failed="1"
+  fi
 
-if [ $failed != "0" ]; then
-    if [ $inputs_differ = "1" ]; then
-        exit 5;
-    fi
-    exit $failed
-fi
+  if [ $failed != "0" ]; then
+      if [ $inputs_differ = "1" ]; then
+          exit 5;
+      fi
+      exit $failed
+  fi
 
-if [ $inputs_differ = "1" ]; then
-    exit 10;
+  if [ $inputs_differ = "1" ]; then
+      exit 10;
+  fi
+else
+  echo "       WARNING: The checkpoint directory was not present in either the goldstandard or the test"
+  echo "                No comparison performed"
 fi
 
 exit 0
