Fixed --with-mpi tests to look for lib64 (if it exists).  This allows configure to pass on 64 bit linuxes that use a lib64 instead of just a lib.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -44021,8 +44021,45 @@ echo "$as_me: checking for required MPI components......" >&6;}
               _sci_optional=required
            else
               _sci_optional=specific
-              _sci_lib="$with_mpi/lib"
               _sci_inc="$with_mpi/include"
+              # Account for lib64 or lib32 or just lib...
+
+##
+## BASE_LIB_PATH:
+##
+## This macro takes the base path of a library and determines
+## if there is a lib32, lib64, or just plain lib that is
+## associated with it.  It sets the full path to the value of
+## the first argument.
+##
+## eg:  if arg 2 is /usr/sci/local, and the machine has a
+## /usr/sci/local/lib64, and configure is in 64 bit mode, then
+## /sur/sci/local/lib64 is set as the value of arg 1.
+##
+## arguments mean:
+## arg 1 : This argument will be written with the result
+## arg 2 : library base.  I.e. /usr, /usr/local, /usr/X11R6
+##
+## This function assums the enable_64bit variable is in scope
+##
+
+  _new_lib_path=$with_mpi/lib
+
+  ## if 64 bit is enabled, check for lib64 first, otherwise use lib
+  if test "$enable_64bit" = "yes"; then
+    _new_lib_path=$with_mpi/lib64
+    if test ! -e $_new_lib_path; then
+      _new_lib_path=$with_mpi/lib
+    fi
+  else
+  ## We should look for lib32 (IRIX), then default to lib
+    _new_lib_path=$with_mpi/lib32
+    if test ! -e $_new_lib_path; then
+      _new_lib_path=$with_mpi/lib
+    fi
+  fi
+  eval _sci_lib='"$_new_lib_path"'
+
            fi
         fi
 
@@ -44531,16 +44568,16 @@ _sci_includes=''
 
 
         if test "$HAVE_MPI" = "yes" && test "$_sci_optional" = "specific" &&
-           test ! -e $with_mpi/lib/$the_file.so &&
-           test ! -e $with_mpi/lib/$the_file.a &&
-           test ! -e $with_mpi/lib/$the_file.dylib; then
-             { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&5
-echo "$as_me: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&2;}
+           test ! -e $_sci_lib/$the_file.so &&
+           test ! -e $_sci_lib/$the_file.a &&
+           test ! -e $_sci_lib/$the_file.dylib; then
+             { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&5
+echo "$as_me: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&2;}
 	     HAVE_MPI="no"
         fi
 
         if test "$HAVE_MPI" != "yes"; then
-          # Try without pmpi (and with pthreads) (for the newer version
+          # Try without pmpi (and with pthreads) for the newer version
           # of lam mpi.
           # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
 
@@ -45043,11 +45080,11 @@ _sci_includes=''
 
           # verify that it was found in the location requested.
           if test "$HAVE_MPI" = "yes" && test "$_sci_optional" = "specific" &&
-             test ! -e $with_mpi/lib/$the_file.so &&
-             test ! -e $with_mpi/lib/$the_file.a &&
-             test ! -e $with_mpi/lib/$the_file.dylib; then
-             { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&5
-echo "$as_me: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&2;}
+             test ! -e $_sci_lib/$the_file.so &&
+             test ! -e $_sci_lib/$the_file.a &&
+             test ! -e $_sci_lib/$the_file.dylib; then
+             { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&5
+echo "$as_me: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&2;}
 	     HAVE_MPI="no"
           fi
 
@@ -45552,11 +45589,11 @@ _sci_includes=''
 
              # verify that it was found in the location requested
              if test "$HAVE_MPI" = "yes" && test "$_sci_optional" = "specific" &&
-                test ! -e $with_mpi/lib/$the_file.so &&
-                test ! -e $with_mpi/lib/$the_file.a &&
-                test ! -e $with_mpi/lib/$the_file.dylib; then
-                { echo "$as_me:$LINENO: WARNING: Found libmpi but not in the requested directory: $with_mpi/lib" >&5
-echo "$as_me: WARNING: Found libmpi but not in the requested directory: $with_mpi/lib" >&2;}
+                test ! -e $_sci_lib/$the_file.so &&
+                test ! -e $_sci_lib/$the_file.a &&
+                test ! -e $_sci_lib/$the_file.dylib; then
+                { echo "$as_me:$LINENO: WARNING: Found libmpi but not in the requested directory: $_sci_lib" >&5
+echo "$as_me: WARNING: Found libmpi but not in the requested directory: $_sci_lib" >&2;}
                 HAVE_MPI="no"
              fi
 
@@ -46060,11 +46097,11 @@ _sci_includes=''
 
                 # verify that it was found in the location requested.
                 if test "$HAVE_MPI" = "yes" && test "$_sci_optional" = "specific" &&
-                   test ! -e $with_mpi/lib/$the_file.so &&
-                   test ! -e $with_mpi/lib/$the_file.a &&
-                   test ! -e $with_mpi/lib/$the_file.dylib; then
-                   { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&5
-echo "$as_me: WARNING: Found libmpi but not in requested directory: $with_mpi/lib" >&2;}
+                   test ! -e $_sci_lib/$the_file.so &&
+                   test ! -e $_sci_lib/$the_file.a &&
+                   test ! -e $_sci_lib/$the_file.dylib; then
+                   { echo "$as_me:$LINENO: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&5
+echo "$as_me: WARNING: Found libmpi but not in requested directory: $_sci_lib" >&2;}
                    HAVE_MPI="no"
                 fi
 
@@ -47086,13 +47123,13 @@ _sci_includes=''
               fi
 
               # verify that it was found in the location requested.
-              if test ! -e $with_mpi/lib/$the_file.so &&
-                 test ! -e $with_mpi/lib/$the_file.a &&
-                 test ! -e $with_mpi/lib/$the_file.lib &&
-                 test ! -e $with_mpi/lib/$the_file.dylib; then
+              if test ! -e $_sci_lib/$the_file.so &&
+                 test ! -e $_sci_lib/$the_file.a &&
+                 test ! -e $_sci_lib/$the_file.lib &&
+                 test ! -e $_sci_lib/$the_file.dylib; then
                    echo
-                   { { echo "$as_me:$LINENO: error: Found libmpi but not in requested directory: $with_mpi/lib" >&5
-echo "$as_me: error: Found libmpi but not in requested directory: $with_mpi/lib" >&2;}
+                   { { echo "$as_me:$LINENO: error: Found libmpi but not in requested directory: $_sci_lib" >&5
+echo "$as_me: error: Found libmpi but not in requested directory: $_sci_lib" >&2;}
    { (exit 1); exit 1; }; }
               fi
            fi
