Added in configure flags to support Wasatch component:
--with-spatialops
--with-exprlib

M    CCA/Components/Wasatch/sub.mk

* Commented out hard coded paths... James, feel free to remove that entire
  block when things are working for you.

M    StandAlone/sub.mk

* Link in boost if it is configured.

M    configure.ac
M    configure
M    configVars.mk.in

* Fixes for handling spatialops, exprlib, tabprops, and boost.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -881,16 +881,26 @@ DEF_HDF5
 INC_HDF5_H
 HDF5_LIB_FLAG
 HDF5_LIB_DIR_FLAG
-HAVE_TABPROPS
-DEF_TABPROPS
-INC_TABPROPS_H
-TABPROPS_LIB_FLAG
-TABPROPS_LIB_DIR_FLAG
 HAVE_BOOST
 DEF_BOOST
 INC_BOOST_H
 BOOST_LIB_FLAG
 BOOST_LIB_DIR_FLAG
+HAVE_SPATIALOPS
+DEF_SPATIALOPS
+INC_SPATIALOPS_H
+SPATIALOPS_LIB_FLAG
+SPATIALOPS_LIB_DIR_FLAG
+HAVE_EXPRLIB
+DEF_EXPRLIB
+INC_EXPRLIB_H
+EXPRLIB_LIB_FLAG
+EXPRLIB_LIB_DIR_FLAG
+HAVE_TABPROPS
+DEF_TABPROPS
+INC_TABPROPS_H
+TABPROPS_LIB_FLAG
+TABPROPS_LIB_DIR_FLAG
 HAVE_HYPRE
 DEF_HYPRE
 INC_HYPRE_H
@@ -1539,6 +1549,8 @@ Optional Packages:
 --with-hypre=DIR        Use the hypre installation in DIR
 --with-petsc=DIR        Use the petsc installation in DIR
 --with-boost=DIR        Use the Boost library in DIR
+--with-spatialops=DIR   Use the SpatialOps library in DIR
+--with-exprlib=DIR      Use the ExprLib library in DIR
 --with-tabprops=DIR     Use the TabProps library in DIR
 --with-zoltan=DIR       Use the Zoltan installation in DIR
 --with-unipetsc=DIR     Use the unipetsc installation in DIR
@@ -2569,18 +2581,42 @@ echo "$as_me: error: The file or directory parameter ($boost) specified for --wi
   fi
 
 
-#SCI_ARG_WITH(spatialops,
-#  AC_HELP_STRING(--with-spatialops=DIR,
-#                 Use the SpatialOps library in DIR),
-#  [with_spatialops="$withval"
-#   sci_required_spatialops=yes],
-#  [with_spatialops=""])
-#SCI_ARG_WITH(exprlib,
-#  AC_HELP_STRING(--with-exprlib=DIR,
-#                 Use the ExprLib library in DIR),
-#  [with_exprlib="$withval"
-#   sci_required_exprlib=yes],
-#  [with_exprlib=""])
+
+
+# Check whether --with-spatialops was given.
+if test "${with_spatialops+set}" = set; then
+  withval=$with_spatialops; with_spatialops="$withval"
+   sci_required_spatialops=yes
+else
+  with_spatialops=""
+fi
+
+  sci_arg_with_list="$sci_arg_with_list --with-spatialops --without-spatialops"
+  if test -n "$spatialops" -a ! -e "$spatialops"; then
+    { { echo "$as_me:$LINENO: error: The file or directory parameter ($spatialops) specified for --with-spatialops does not exist!  Please verify that the path and file are correct." >&5
+echo "$as_me: error: The file or directory parameter ($spatialops) specified for --with-spatialops does not exist!  Please verify that the path and file are correct." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+# Check whether --with-exprlib was given.
+if test "${with_exprlib+set}" = set; then
+  withval=$with_exprlib; with_exprlib="$withval"
+   sci_required_exprlib=yes
+else
+  with_exprlib=""
+fi
+
+  sci_arg_with_list="$sci_arg_with_list --with-exprlib --without-exprlib"
+  if test -n "$exprlib" -a ! -e "$exprlib"; then
+    { { echo "$as_me:$LINENO: error: The file or directory parameter ($exprlib) specified for --with-exprlib does not exist!  Please verify that the path and file are correct." >&5
+echo "$as_me: error: The file or directory parameter ($exprlib) specified for --with-exprlib does not exist!  Please verify that the path and file are correct." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
 
 
 # Check whether --with-tabprops was given.
@@ -45007,6 +45043,183 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+##  --  search for Boost ------------------------
+
+if test "$with_boost"; then
+  if test "$with_boost" = "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-boost=DIR requires a DIRectory be provided. " >&5
+echo "$as_me: error: --with-boost=DIR requires a DIRectory be provided. " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    { echo "$as_me:$LINENO: checking for Boost files (For now we are just verifying the existence of lib and .h files)" >&5
+echo $ECHO_N "checking for Boost files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
+    if test ! -d $with_boost; then
+      echo ""
+      { { echo "$as_me:$LINENO: error: '$with_boost' directory does not exist. " >&5
+echo "$as_me: error: '$with_boost' directory does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    # Check for header files
+    BOOST_INCLUDE_DIR=$with_boost/include/boost
+    for file in signal.hpp shared_ptr.hpp bind.hpp signal.hpp shared_ptr.hpp ref.hpp graph/adjacency_list.hpp graph/graph_traits.hpp \
+                graph/topological_sort.hpp graph/graphviz.hpp graph/breadth_first_search.hpp graph/visitors.hpp graph/transpose_graph.hpp \
+                shared_ptr.hpp any.hpp; do
+      if test ! -f $BOOST_INCLUDE_DIR/$file; then
+        echo ""
+        { { echo "$as_me:$LINENO: error: '$BOOST_INCLUDE_DIR/$file' does not exist. " >&5
+echo "$as_me: error: '$BOOST_INCLUDE_DIR/$file' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+    done
+    # Check for libraries files
+    BOOST_LIB_DIR=$with_boost/lib
+    for file in libboost_thread-mt.a libboost_signals-mt.a; do
+      if test ! -f $BOOST_LIB_DIR/$file; then
+        echo ""
+        { echo "$as_me:$LINENO: WARNING: $file lib does not exist... looking for non-mt version..." >&5
+echo "$as_me: WARNING: $file lib does not exist... looking for non-mt version..." >&2;}
+        short_name="`echo $file | cut -f1 -d"-"`.a"
+        if test ! -f $BOOST_LIB_DIR/$short_name; then
+            { { echo "$as_me:$LINENO: error: $BOOST_LIB_DIR/$short_name lib does not exist!" >&5
+echo "$as_me: error: $BOOST_LIB_DIR/$short_name lib does not exist!" >&2;}
+   { (exit 1); exit 1; }; }
+        else
+            short_name=`echo $short_name | cut -f1 -d"." | cut -c4-`
+            BOOST_LIB_FLAG="$BOOST_LIB_FLAG -l$short_name"
+        fi
+      else
+        short_name=`echo $file | cut -f1 -d"." | cut -c4-`
+        BOOST_LIB_FLAG="$BOOST_LIB_FLAG -l$short_name"
+      fi
+    done
+  fi
+  { echo "$as_me:$LINENO: result: Found Boost" >&5
+echo "${ECHO_T}Found Boost" >&6; }
+  DEF_BOOST="#define HAVE_BOOST 1"
+  INC_BOOST_H="-I$with_boost/include"
+  BOOST_LIB_DIR_FLAG="-L$with_boost/lib"
+  HAVE_BOOST="yes"
+fi
+
+
+
+
+
+
+##  --  search for SpatialOps Library ------------------------
+
+if test "$with_spatialops"; then
+  if test "$HAVE_BOOST" != "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-spatialops=DIR requires Boost. " >&5
+echo "$as_me: error: --with-spatialops=DIR requires Boost. " >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  if test "$with_spatialops" = "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-spatialops=DIR requires a DIRectory be provided. " >&5
+echo "$as_me: error: --with-spatialops=DIR requires a DIRectory be provided. " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+
+    { echo "$as_me:$LINENO: checking for SpatialOps files (For now we are just verifying the existence of lib and .h files)" >&5
+echo $ECHO_N "checking for SpatialOps files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
+    if test ! -d $with_spatialops; then
+      echo ""
+      { { echo "$as_me:$LINENO: error: '$with_spatialops' directory does not exist. " >&5
+echo "$as_me: error: '$with_spatialops' directory does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    SPOPS_INCLUDE_DIR="include/spatialops"
+    # Check includes
+    for file in FieldFunctions.h LagrangePoly.h LinAlgTrilinos.h LinAlgUBlas.h LinearSystem.h OperatorDatabase.h SFIterator.h \
+                SpatialField.h SpatialFieldStore.h SpatialOperator.h SpatialOpsConfigure.h SpatialOpsDefs.h SpatialOpsTools.h \
+                particles structured; do
+      if test ! -e $with_spatialops/$SPOPS_INCLUDE_DIR/$file; then
+        echo ""
+        { { echo "$as_me:$LINENO: error: '$with_spatialops/$SPOPS_INCLUDE_DIR/$file' does not exist. " >&5
+echo "$as_me: error: '$with_spatialops/$SPOPS_INCLUDE_DIR/$file' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+    done
+    # Check lib
+    if test ! -f $with_spatialops/lib/spatialops/libspatialops.a; then
+      echo ""
+      { { echo "$as_me:$LINENO: error: '$with_spatialops/lib/spatialops/libspatialops.a' does not exist. " >&5
+echo "$as_me: error: '$with_spatialops/lib/spatialops/libspatialops.a' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  fi
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  DEF_SPATIALOPS="#define HAVE_SPATIALOPS 1"
+  INC_SPATIALOPS_H="-I$with_spatialops/include"
+  SPATIALOPS_LIB_DIR_FLAG="-L$with_spatialops/lib/spatialops"
+  SPATIALOPS_LIB_FLAG="-lspatialops"
+  HAVE_SPATIALOPS="yes"
+fi
+
+
+
+
+
+
+##  --  search for Exprlib Library ------------------------
+
+if test "$with_exprlib"; then
+  if test "$HAVE_SPATIALOPS" != "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-exprlib=DIR requires SpatialOps. " >&5
+echo "$as_me: error: --with-exprlib=DIR requires SpatialOps. " >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  if test "$with_exprlib" = "yes"; then
+    { { echo "$as_me:$LINENO: error: --with-exprlib=DIR requires a DIRectory be provided. " >&5
+echo "$as_me: error: --with-exprlib=DIR requires a DIRectory be provided. " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+
+    { echo "$as_me:$LINENO: checking for Exprlib files (For now we are just verifying the existence of lib and .h files)" >&5
+echo $ECHO_N "checking for Exprlib files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
+    if test ! -d $with_exprlib; then
+      echo ""
+      { { echo "$as_me:$LINENO: error: '$with_exprlib' directory does not exist. " >&5
+echo "$as_me: error: '$with_exprlib' directory does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    SPOPS_INCLUDE_DIR="include/expression"
+    # Check includes
+    for file in ExecuteExpression.h ExprDeps.h ExprLib.h Expr_Context.h Expr_Expression.h Expr_ExpressionID.h Expr_FieldManagerList.h \
+                ExpressionBase.h ExpressionFactory.h ExpressionRegistry.h ExpressionTree.h FieldDeps.h FieldManager.h FieldManagerBase.h \
+                Functions.h PlaceHolderExpr.h Tag.h TransportEquation.h uintah; do
+      if test ! -e $with_exprlib/$SPOPS_INCLUDE_DIR/$file; then
+        echo ""
+        { { echo "$as_me:$LINENO: error: '$with_exprlib/$SPOPS_INCLUDE_DIR/$file' does not exist. " >&5
+echo "$as_me: error: '$with_exprlib/$SPOPS_INCLUDE_DIR/$file' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+    done
+    # Check lib
+    if test ! -f $with_exprlib/lib/expression/libexprlib.a; then
+      echo ""
+      { { echo "$as_me:$LINENO: error: '$with_exprlib/lib/expression/libexprlib.a' does not exist. " >&5
+echo "$as_me: error: '$with_exprlib/lib/expression/libexprlib.a' does not exist. " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  fi
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  DEF_EXPRLIB="#define HAVE_EXPRLIB 1"
+  INC_EXPRLIB_H="-I$with_exprlib/include"
+  EXPRLIB_LIB_DIR_FLAG="-L$with_exprlib/lib/expression"
+  EXPRLIB_LIB_FLAG="-lexprlib"
+  HAVE_EXPRLIB="yes"
+fi
+
+
+
+
+
+
 ##  --  search for TabProps ------------------------
 
 if test "$with_tabprops"; then
@@ -45043,43 +45256,6 @@ echo "${ECHO_T}yes" >&6; }
   TABPROPS_LIB_DIR_FLAG="-L$with_tabprops/lib/tabprops"
   TABPROPS_LIB_FLAG="-ltabprops"
   HAVE_TABPROPS="yes"
-fi
-
-
-
-
-
-
-##  --  search for Boost ------------------------
-
-if test "$with_boost"; then
-  if test "$with_boost" = "yes"; then
-    { { echo "$as_me:$LINENO: error: --with-boost=DIR requires a DIRectory be provided. " >&5
-echo "$as_me: error: --with-boost=DIR requires a DIRectory be provided. " >&2;}
-   { (exit 1); exit 1; }; }
-  else
-    { echo "$as_me:$LINENO: checking for Boost files (For now we are just verifying the existence of lib and .h files)" >&5
-echo $ECHO_N "checking for Boost files (For now we are just verifying the existence of lib and .h files)... $ECHO_C" >&6; }
-    if test ! -d $with_boost; then
-      { { echo "$as_me:$LINENO: error: '$with_boost' directory does not exist. " >&5
-echo "$as_me: error: '$with_boost' directory does not exist. " >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    for file in include/boost/BSpline.h include/boost/LU.h include/boost/StateTable.h lib/boost/libboost.a; do
-      if test ! -f $with_boost/$file; then
-        { { echo "$as_me:$LINENO: error: '$with_boost/$file' does not exist. " >&5
-echo "$as_me: error: '$with_boost/$file' does not exist. " >&2;}
-   { (exit 1); exit 1; }; }
-      fi
-    done
-  fi
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-  DEF_BOOST="#define HAVE_BOOST 1"
-  INC_BOOST_H="-I$with_boost/include"
-  BOOST_LIB_DIR_FLAG="-L$with_boost/lib/boost"
-  BOOST_LIB_FLAG="-lboost"
-  HAVE_BOOST="yes"
 fi
 
 
@@ -46665,16 +46841,26 @@ DEF_HDF5!$DEF_HDF5$ac_delim
 INC_HDF5_H!$INC_HDF5_H$ac_delim
 HDF5_LIB_FLAG!$HDF5_LIB_FLAG$ac_delim
 HDF5_LIB_DIR_FLAG!$HDF5_LIB_DIR_FLAG$ac_delim
-HAVE_TABPROPS!$HAVE_TABPROPS$ac_delim
-DEF_TABPROPS!$DEF_TABPROPS$ac_delim
-INC_TABPROPS_H!$INC_TABPROPS_H$ac_delim
-TABPROPS_LIB_FLAG!$TABPROPS_LIB_FLAG$ac_delim
-TABPROPS_LIB_DIR_FLAG!$TABPROPS_LIB_DIR_FLAG$ac_delim
 HAVE_BOOST!$HAVE_BOOST$ac_delim
 DEF_BOOST!$DEF_BOOST$ac_delim
 INC_BOOST_H!$INC_BOOST_H$ac_delim
 BOOST_LIB_FLAG!$BOOST_LIB_FLAG$ac_delim
 BOOST_LIB_DIR_FLAG!$BOOST_LIB_DIR_FLAG$ac_delim
+HAVE_SPATIALOPS!$HAVE_SPATIALOPS$ac_delim
+DEF_SPATIALOPS!$DEF_SPATIALOPS$ac_delim
+INC_SPATIALOPS_H!$INC_SPATIALOPS_H$ac_delim
+SPATIALOPS_LIB_FLAG!$SPATIALOPS_LIB_FLAG$ac_delim
+SPATIALOPS_LIB_DIR_FLAG!$SPATIALOPS_LIB_DIR_FLAG$ac_delim
+HAVE_EXPRLIB!$HAVE_EXPRLIB$ac_delim
+DEF_EXPRLIB!$DEF_EXPRLIB$ac_delim
+INC_EXPRLIB_H!$INC_EXPRLIB_H$ac_delim
+EXPRLIB_LIB_FLAG!$EXPRLIB_LIB_FLAG$ac_delim
+EXPRLIB_LIB_DIR_FLAG!$EXPRLIB_LIB_DIR_FLAG$ac_delim
+HAVE_TABPROPS!$HAVE_TABPROPS$ac_delim
+DEF_TABPROPS!$DEF_TABPROPS$ac_delim
+INC_TABPROPS_H!$INC_TABPROPS_H$ac_delim
+TABPROPS_LIB_FLAG!$TABPROPS_LIB_FLAG$ac_delim
+TABPROPS_LIB_DIR_FLAG!$TABPROPS_LIB_DIR_FLAG$ac_delim
 HAVE_HYPRE!$HAVE_HYPRE$ac_delim
 DEF_HYPRE!$DEF_HYPRE$ac_delim
 INC_HYPRE_H!$INC_HYPRE_H$ac_delim
@@ -46687,7 +46873,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 63; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 73; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
