Updating configure to work on Franklin

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1503,7 +1503,8 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
 --enable-wasatch_3p
 ExprLibDownload and build the Wasatch Thirdparty libraries - TabProps
---enable-static         Build a statically linked version of Uintah
+--enable-static         Build a statically linked version of Uintah. Set to
+                          'full' to force full static link.
 --enable-verbosity      Turn on verbose configure output
 --enable-threads        Specify a thread implementation (pthreads or irix)
 --enable-debug          Turn on debugging (default is -g) or specify your
@@ -1564,7 +1565,9 @@ Optional Packages:
 --with-jpeg=DIR         Use the jpeg installation in DIR
 --with-tiff=DIR         Use the tiff installation in DIR
 --with-xalan=DIR        Use the xalan installation in DIR
---with-libxml2=DIR      Use the libxml2 installation in DIR
+--with-libxml2=DIR      Use the libxml2 installation in DIR. Set 'DIR' to
+                          'built-in' if explicit linking of xml2 is NOT
+                          required.
 --with-hdf5=DIR         Use the hdf5 installation in DIR
 --with-freetype=DIR     Use the Freetype2 installation in DIR
 --with-ftgl=DIR         Use the Freetype GL installation in DIR
@@ -2910,7 +2913,7 @@ fi
 
   # Check whether --enable-static was given.
 if test "${enable_static+set}" = set; then
-  enableval=$enable_static; static="yes"
+  enableval=$enable_static; static="$enableval"
 else
   static="no"
 fi
@@ -3137,7 +3140,7 @@ myargs=`echo $args | sed 's%\^% %g'`
 ## Cut off the /configure from the configure command (eg: ../src/configure)
 path_to_src=`echo $0 | sed 's/\/configure//'`
 
-if test "$sci_required_petsc" = "yes"; then
+if test "$sci_required_petsc" = "yes" -a "$with_petsc" != "built-in"; then
    sci_required_blas=yes
    sci_required_lapack=yes
 fi
@@ -7365,12 +7368,23 @@ fi
 IS_STATIC_BUILD="no"
 
 # If --enable-static, or if lib extension already set to 'a' (eg: AIX):
-if test "$static" = "yes" -o "$SO_OR_ARCHIVE_EXTENSION" = "a"; then
+if test "$static" != "no" -o "$SO_OR_ARCHIVE_EXTENSION" = "a"; then
   { echo "$as_me:$LINENO: WARNING: Building a statically linked version of Uintah! " >&5
 echo "$as_me: WARNING: Building a statically linked version of Uintah! " >&2;}
   IS_STATIC_BUILD="yes"
   SO_OR_ARCHIVE_EXTENSION=a
-#  LDFLAGS="$LDFLAGS -static"   # FIXME... need -static (at least for gcc)...
+  if test "$static" == "full"; then
+
+    # If we don't use the 'full' option, then some shared libs may be
+    # linked in.  While we probably should make 'full' the default, this
+    # ends up breaking a number of (our test) machines that don't have (all the) static
+    # libraries installed.  As 'static' is really used only on specific/large
+    # supercomputers (Crays mostly), and we only/mostly use it on
+    # small machines to check for circular dependancies, it is ok to not use
+    # '-static' in most cases.
+
+    LDFLAGS="${LDFLAGS} -static"
+  fi
   MAKE_ARCHIVES="yes"
   STATIC_BUILD_DEF="#define STATIC_BUILD 1"
 else
@@ -16734,50 +16748,56 @@ if test "$with_libxml2"; then
    _sci_optional=specific
 fi
 
-{ echo "$as_me:$LINENO: checking for $_sci_optional libxml2" >&5
+if test "$with_libxml2" == "built-in"; then
+  XML2_LIB_FLAG="-lxml2"
+  { echo "$as_me:$LINENO: result: \"Using built in libxml2... no explicit linking will be done.\" " >&5
+echo "${ECHO_T}\"Using built in libxml2... no explicit linking will be done.\" " >&6; }
+else
+
+  { echo "$as_me:$LINENO: checking for $_sci_optional libxml2" >&5
 echo $ECHO_N "checking for $_sci_optional libxml2... $ECHO_C" >&6; }
-if test ! -e $_sci_lib/../bin/xml2-config; then
-   { echo "$as_me:$LINENO: result: Not found under $_sci_lib" >&5
+  if test ! -e $_sci_lib/../bin/xml2-config; then
+     { echo "$as_me:$LINENO: result: Not found under $_sci_lib" >&5
 echo "${ECHO_T}Not found under $_sci_lib" >&6; }
-   { echo "$as_me:$LINENO: checking for xml2-config in your path" >&5
+     { echo "$as_me:$LINENO: checking for xml2-config in your path" >&5
 echo $ECHO_N "checking for xml2-config in your path... $ECHO_C" >&6; }
-   XML2_DIR=`xml2-config --prefix`
-   if test -e "$XML2_DIR/lib"; then
-      _sci_lib=$XML2_DIR/lib
-      { echo "$as_me:$LINENO: result: xml2-config found..." >&5
+     XML2_DIR=`xml2-config --prefix`
+     if test -e "$XML2_DIR/lib"; then
+        _sci_lib=$XML2_DIR/lib
+        { echo "$as_me:$LINENO: result: xml2-config found..." >&5
 echo "${ECHO_T}xml2-config found..." >&6; }
-   else
-      { echo "$as_me:$LINENO: result: xml2-config program not found..." >&5
+     else
+        { echo "$as_me:$LINENO: result: xml2-config program not found..." >&5
 echo "${ECHO_T}xml2-config program not found..." >&6; }
-   fi
-fi
+     fi
+  fi
 
-found_xml2_config="no"
+  found_xml2_config="no"
 
-if test -e $_sci_lib/../bin/xml2-config; then
-    found_xml2_config="yes"
-    { echo "$as_me:$LINENO: WARNING: Using $_sci_lib/../bin/xml2-config to set libxml2 variables." >&5
+  if test -e $_sci_lib/../bin/xml2-config; then
+      found_xml2_config="yes"
+      { echo "$as_me:$LINENO: WARNING: Using $_sci_lib/../bin/xml2-config to set libxml2 variables." >&5
 echo "$as_me: WARNING: Using $_sci_lib/../bin/xml2-config to set libxml2 variables." >&2;}
 
-    if test "$IS_STATIC_BUILD" = "yes" -a "$IS_OSX" != "yes"; then
-       STATIC_FLAG=--static
-    fi
-
-    XML2_LIB_DIR_FLAG=`$_sci_lib/../bin/xml2-config --libs $STATIC_FLAG`
-    XML2_LDFLAGS=""
-    XML2_LIB_PATH=""
-    for i in $XML2_LIB_DIR_FLAG;do
-      is_lib_path=`echo $i | sed -n -e "s/-L//p"`
-      if test -z "$is_lib_path";then
-        XML2_LDFLAGS="$XML2_LDFLAGS $i"
-      else
-        if ! test $i = "-L/usr/lib";then
-    	XML2_LIB_PATH="$XML2_LIB_PATH $i"
-        fi
+      if test "$IS_STATIC_BUILD" = "yes" -a "$IS_OSX" != "yes"; then
+        STATIC_FLAG=--static
       fi
-    done
-    includes=`$_sci_lib/../bin/xml2-config --cflags`
-fi
+
+      XML2_LIB_DIR_FLAG=`$_sci_lib/../bin/xml2-config --libs $STATIC_FLAG`
+      XML2_LDFLAGS=""
+      XML2_LIB_PATH=""
+      for i in $XML2_LIB_DIR_FLAG;do
+        is_lib_path=`echo $i | sed -n -e "s/-L//p"`
+        if test -z "$is_lib_path";then
+          XML2_LDFLAGS="$XML2_LDFLAGS $i"
+        else
+          if ! test $i = "-L/usr/lib";then
+            XML2_LIB_PATH="$XML2_LIB_PATH $i"
+          fi
+        fi
+      done
+      includes=`$_sci_lib/../bin/xml2-config --cflags`
+  fi
 
 ##
 ## SCI_TRY_LINK (XML2):  xml2 library and headers
@@ -17082,25 +17102,25 @@ int
 main ()
 {
 
-#if defined(LIBXML_TREE_ENABLED) && defined(LIBXML_OUTPUT_ENABLED)
-xmlDocPtr doc = NULL;       /* document pointer */
-xmlNodePtr root_node = NULL, node = NULL, node1 = NULL;/* node pointers */
-xmlDtdPtr dtd = NULL;       /* DTD pointer */
-char buff[256];
-int i, j;
+  #if defined(LIBXML_TREE_ENABLED) && defined(LIBXML_OUTPUT_ENABLED)
+  xmlDocPtr doc = NULL;       /* document pointer */
+  xmlNodePtr root_node = NULL, node = NULL, node1 = NULL;/* node pointers */
+  xmlDtdPtr dtd = NULL;       /* DTD pointer */
+  char buff[256];
+  int i, j;
 
-LIBXML_TEST_VERSION;
+  LIBXML_TEST_VERSION;
 
-/*
-  * Creates a new document, a node and set it as a root node
-  */
-doc = xmlNewDoc(BAD_CAST "1.0");
-root_node = xmlNewNode(NULL, BAD_CAST "root");
-xmlDocSetRootElement(doc, root_node);
-#else
-//create compile error so configure fails
-WrongVersionOrNotInstalled *x = 0;
-#endif
+  /*
+    * Creates a new document, a node and set it as a root node
+    */
+  doc = xmlNewDoc(BAD_CAST "1.0");
+  root_node = xmlNewNode(NULL, BAD_CAST "root");
+  xmlDocSetRootElement(doc, root_node);
+  #else
+  //create compile error so configure fails
+  WrongVersionOrNotInstalled *x = 0;
+  #endif
 
   ;
   return 0;
@@ -17282,14 +17302,15 @@ _sci_includes=''
 
 
 
-DEF_XML2="#define HAVE_XML2 1"
-break
+  DEF_XML2="#define HAVE_XML2 1"
+  break
 
-if test ! "$DEF_XML2"; then
-  echo
-  { { echo "$as_me:$LINENO: error: One or more of the xml2 components is missing." >&5
+  if test ! "$DEF_XML2"; then
+    echo
+    { { echo "$as_me:$LINENO: error: One or more of the xml2 components is missing." >&5
 echo "$as_me: error: One or more of the xml2 components is missing." >&2;}
    { (exit 1); exit 1; }; }
+  fi
 fi
 
 
@@ -41727,69 +41748,71 @@ echo "$as_me: error: PETSC_ARCH environment var is not set.  Please set." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-# Handle --without option
-
-if test "$with_petsc" == "no"; then
+if test "$with_petsc" == "no"; then # Handle --without option
   { echo "$as_me:$LINENO: WARNING: \"PETSc disabled.\" " >&5
 echo "$as_me: WARNING: \"PETSc disabled.\" " >&2;}
 else
 
-  # Make sure we have either mpi or mpi-uni, blas, and lapack
-  # It seems that under AIX and OSF, the libs that cover blas also cover lapack
-  if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") && test "$HAVE_BLAS" = "yes" &&
-     (test "$PETSC_ARCH" = "aix5.1.0.0" || test "$PETSC_ARCH" = "dec" ||
-      test "$HAVE_LAPACK" = "yes"); then
+  if test "$with_petsc" == "built-in"; then
+     HAVE_PETSC="yes"
+     DEF_PETSC="#define HAVE_PETSC 1"
+  else
+    # Make sure we have either mpi or mpi-uni, blas, and lapack
+    # It seems that under AIX and OSF, the libs that cover blas also cover lapack
+    if (test "$HAVE_MPI" = "yes" || test "$HAVE_MPI_UNI" = "yes") && test "$HAVE_BLAS" = "yes" &&
+       (test "$PETSC_ARCH" = "aix5.1.0.0" || test "$PETSC_ARCH" = "dec" ||
+        test "$HAVE_LAPACK" = "yes"); then
 
-    _sci_lib_dir=
-    _sci_inc=
+      _sci_lib_dir=
+      _sci_inc=
 
-    for petsc_arch in "$PETSC_ARCH" linux-gnu linux-gnu-c-opt; do
-      if test "$HAVE_PETSC" = "yes"; then
-        break
-      fi
-
-      PETSC_SUB=lib/libO
-
-      if test "$with_petsc"; then
-
-        ####################################################
-        # The newer (2.3+) versions of petsc don't use the libO anymore...
-        have23=`echo "$with_petsc" | grep "2.3."`
-        if test -z "$have23" ; then
-           petsc_version_major=`grep PETSC_VERSION_MAJOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
-           petsc_version_minor=`grep PETSC_VERSION_MINOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
-           if test "$petsc_version_major" -eq 2 ; then
-              if test "$petsc_version_minor" -eq 3 ; then
-                 have23=true
-              fi
-           fi
+      for petsc_arch in "$PETSC_ARCH" linux-gnu linux-gnu-c-opt; do
+        if test "$HAVE_PETSC" = "yes"; then
+          break
         fi
-        if test "$have23"; then
-           PETSC_SUB=lib
+
+        PETSC_SUB=lib/libO
+
+        if test "$with_petsc"; then
+
+          ####################################################
+          # The newer (2.3+) versions of petsc don't use the libO anymore...
+          have23=`echo "$with_petsc" | grep "2.3."`
+          if test -z "$have23" ; then
+             petsc_version_major=`grep PETSC_VERSION_MAJOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
+             petsc_version_minor=`grep PETSC_VERSION_MINOR $with_petsc/include/petscversion.h | grep define | awk '{print $3}'`
+             if test "$petsc_version_major" -eq 2 ; then
+                if test "$petsc_version_minor" -eq 3 ; then
+                   have23=true
+                fi
+             fi
+          fi
+          if test "$have23"; then
+             PETSC_SUB=lib
+          fi
+          ####################################################
+
+          _sci_lib_dir="$with_petsc/$PETSC_SUB/$petsc_arch"
+          _sci_inc="$with_petsc/bmake/$petsc_arch $with_petsc/include"
+        else
+          # Modify _sci_dirs to have correct path information:
+          for i in $sci_thirdparty_dir; do
+            if test ! -d "$i"; then
+              continue
+            fi
+
+            # This is where the lib actually lives
+            if test ! -d "$i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"; then
+              continue
+            fi
+
+            _sci_lib_dir="$_sci_lib_dir $i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"
+            _sci_inc="$_sci_inc $i/$PETSC_VERSION_DIR/include $i/$PETSC_VERSION_DIR/bmake/$petsc_arch"
+          done
         fi
-        ####################################################
 
-        _sci_lib_dir="$with_petsc/$PETSC_SUB/$petsc_arch"
-        _sci_inc="$with_petsc/bmake/$petsc_arch $with_petsc/include"
-      else
-        # Modify _sci_dirs to have correct path information:
-        for i in $sci_thirdparty_dir; do
-          if test ! -d "$i"; then
-            continue
-          fi
-
-          #this is where the lib actually lives
-          if test ! -d "$i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"; then
-            continue
-          fi
-
-          _sci_lib_dir="$_sci_lib_dir $i/$PETSC_VERSION_DIR/$PETSC_SUB/$petsc_arch"
-          _sci_inc="$_sci_inc $i/$PETSC_VERSION_DIR/include $i/$PETSC_VERSION_DIR/bmake/$petsc_arch"
-        done
-      fi
-
-      # For Petsc 2.2 use this line below:   petsc petscvec petscmat petscdm petscsnes petscts petscksp $LAPACK_LIB_FLAG $BLAS_LIB_FLAG $M_LIB_FLAG $MPI_LIB_FLAG $F_LIB_DIR_FLAG $F_LIB_FLAG $DL_LIB_FLAG,
-      # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
+        # For Petsc 2.2 use this line below:   petsc petscvec petscmat petscdm petscsnes petscts petscksp $LAPACK_LIB_FLAG $BLAS_LIB_FLAG $M_LIB_FLAG $MPI_LIB_FLAG $F_LIB_DIR_FLAG $F_LIB_FLAG $DL_LIB_FLAG,
+        # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
 
 
 ##
@@ -42275,33 +42298,33 @@ _sci_includes=''
 
 
 
-      if test "$HAVE_PETSC" = "yes" ; then
-        DEF_PETSC="#define HAVE_PETSC 1"
-      fi
-    done
-    if test "$with_petsc" && test ! "$DEF_PETSC"; then
-      echo
-      { { echo "$as_me:$LINENO: error: One or more of the PETSc components is missing." >&5
+        if test "$HAVE_PETSC" = "yes" ; then
+          DEF_PETSC="#define HAVE_PETSC 1"
+        fi
+      done
+      if test "$with_petsc" && test ! "$DEF_PETSC"; then
+        echo
+        { { echo "$as_me:$LINENO: error: One or more of the PETSc components is missing." >&5
 echo "$as_me: error: One or more of the PETSc components is missing." >&2;}
    { (exit 1); exit 1; }; }
-      echo
-    fi
-
-    #  --  search for uni-petsc  --------------------------------------------
-
-    if test "$HAVE_PETSC" != "yes" ; then
-
-      # Only check for uni petsc if petsc not found.
-      _sci_lib=""
-      _sci_inc=""
-
-      if test "$with_unipetsc"; then
-        _sci_lib="$with_unipetsc/$PETSC_SUB/$PETSC_ARCH"
-        _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
+        echo
       fi
 
-      # For petsc 2.2 use this line below:  petsc petscvec petscmat petscdm petscsnes petscts petscksp,
-      # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
+      #  --  search for uni-petsc  --------------------------------------------
+
+      if test "$HAVE_PETSC" != "yes" ; then
+
+        # Only check for uni petsc if petsc not found.
+        _sci_lib=""
+        _sci_inc=""
+
+        if test "$with_unipetsc"; then
+          _sci_lib="$with_unipetsc/$PETSC_SUB/$PETSC_ARCH"
+          _sci_inc="$with_unipetsc/bmake/$PETSC_ARCH $with_unipetsc/include"
+        fi
+
+        # For petsc 2.2 use this line below:  petsc petscvec petscmat petscdm petscsnes petscts petscksp,
+        # Use -DMPIPP_H so we don't include mpi++.h where we don't want it.
 
 ##
 ## SCI_TRY_LINK (PETSC_UNI):  petsc-uni libraries and headers
@@ -42786,10 +42809,10 @@ _sci_includes=''
 
 
 
-      if test "$HAVE_PETSC_UNI" = "yes" ; then
-        DEF_PETSC_UNI="#define PETSC_UNI 1"
-      else
-        # Give it a shot on the old petsc-uni version
+        if test "$HAVE_PETSC_UNI" = "yes" ; then
+          DEF_PETSC_UNI="#define PETSC_UNI 1"
+        else
+          # Give it a shot on the old petsc-uni version
 
 ##
 ## SCI_TRY_LINK (PETSC_UNI):  petsc libraries and headers - old2
@@ -43273,33 +43296,33 @@ _sci_includes=''
 ##
 
 
-        if test "$HAVE_PETSC_UNI" = "yes" ; then
-          DEF_PETSC_UNI="#define PETSC_UNI 1"
+          if test "$HAVE_PETSC_UNI" = "yes" ; then
+            DEF_PETSC_UNI="#define PETSC_UNI 1"
+          fi
         fi
-      fi
 
-      if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
-        echo
-        { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
+        if test "$with_unipetsc" && test ! "$DEF_PETSC_UNI"; then
+          echo
+          { { echo "$as_me:$LINENO: error: One or more of the UNI-PETSC components is missing." >&5
 echo "$as_me: error: One or more of the UNI-PETSC components is missing." >&2;}
    { (exit 1); exit 1; }; }
-        echo
+          echo
+        fi
       fi
-    fi
-
-  else
-    { echo "$as_me:$LINENO: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&5
+    else
+      { echo "$as_me:$LINENO: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&5
 echo "$as_me: WARNING: One or more of MPI or BLAS or LAPACK is missing." >&2;}
-    { echo "$as_me:$LINENO: WARNING: HAVE_MPI: $HAVE_MPI" >&5
+      { echo "$as_me:$LINENO: WARNING: HAVE_MPI: $HAVE_MPI" >&5
 echo "$as_me: WARNING: HAVE_MPI: $HAVE_MPI" >&2;}
-    { echo "$as_me:$LINENO: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&5
+      { echo "$as_me:$LINENO: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&5
 echo "$as_me: WARNING: HAVE_MPI_UNI: $HAVE_MPI_UNI" >&2;}
-    { echo "$as_me:$LINENO: WARNING: HAVE_BLAS: $HAVE_BLAS" >&5
+      { echo "$as_me:$LINENO: WARNING: HAVE_BLAS: $HAVE_BLAS" >&5
 echo "$as_me: WARNING: HAVE_BLAS: $HAVE_BLAS" >&2;}
-    { echo "$as_me:$LINENO: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&5
+      { echo "$as_me:$LINENO: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&5
 echo "$as_me: WARNING: HAVE_LAPACK: $HAVE_LAPACK" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Not configuring PETSc." >&5
+      { echo "$as_me:$LINENO: WARNING: Not configuring PETSc." >&5
 echo "$as_me: WARNING: Not configuring PETSc." >&2;}
+    fi
   fi
 fi
 
@@ -45336,10 +45359,12 @@ fi
 ##  --  search for TabProps ------------------------
 
 if test "$with_tabprops"; then
+
   if test "$HAVE_HDF5" != "yes"; then
-    { { echo "$as_me:$LINENO: error: --with-tabprops=DIR requires HDF5. " >&5
-echo "$as_me: error: --with-tabprops=DIR requires HDF5. " >&2;}
-   { (exit 1); exit 1; }; }
+    # I think HDF5 is optional now for TabProps, but am not quite sure...
+    { echo "$as_me:$LINENO: WARNING: --with-tabprops=DIR might require HDF5... " >&5
+echo "$as_me: WARNING: --with-tabprops=DIR might require HDF5... " >&2;}
+    add_important_warning "--with-tabprops was specified, but HDF5 was not... this might cause a problem."
   fi
 
   if test "$with_tabprops" = "yes"; then
