added blt stuff

diff --git a/src/configure.in b/src/configure.in
--- a/src/configure.in
+++ b/src/configure.in
@@ -498,6 +498,26 @@ AC_SUBST(ITCL_LIB_DIR)
 AC_SUBST(ITCL_LIB_FLAG)
 AC_SUBST(ITCL_WIDGETS)
 
+##-- Find BLT ---------------------------------------------------------------
+
+echo -n "Looking for Pre-built blt2.4... "
+if sh="`which bltwish24`" ; then
+  shdir="`dirname $sh`"
+  BLT_PREFIX="`cd $shdir/.. ; pwd`"
+  BLT_INCLUDE_DIR="${BLT_PREFIX}/include"
+  BLT_LIB_DIR="${BLT_PREFIX}/lib"
+  BLT_LIB_FLAG="-lBLT24"
+  echo -L$BLT_PREFIX $BLT_LIB_FLAG
+else
+  echo "not found -- must build"
+  echo "  Implement me."
+  exit 1
+fi
+
+AC_SUBST(BLT_INCLUDE_DIR)
+AC_SUBST(BLT_LIB_DIR)
+AC_SUBST(BLT_LIB_FLAG)
+
 ##-- Check for option to build new parallel (distributed memory) SCIRun ------
 
 AC_ARG_ENABLE(enable_parallel,
